// flow-typed signature: 2d4fdd9664c2ef7dd628c833c4a52e36
// flow-typed version: <<STUB>>/@tinymce/tinymce-react_v=4.3.0/flow_v0.206.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@tinymce/tinymce-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@tinymce/tinymce-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@tinymce/tinymce-react/lib/cjs/main/ts/components/Editor' {
  declare module.exports: any;
}

declare module '@tinymce/tinymce-react/lib/cjs/main/ts/components/EditorPropTypes' {
  declare module.exports: any;
}

declare module '@tinymce/tinymce-react/lib/cjs/main/ts/Events' {
  declare module.exports: any;
}

declare module '@tinymce/tinymce-react/lib/cjs/main/ts' {
  declare module.exports: any;
}

declare module '@tinymce/tinymce-react/lib/cjs/main/ts/ScriptLoader2' {
  declare module.exports: any;
}

declare module '@tinymce/tinymce-react/lib/cjs/main/ts/TinyMCE' {
  declare module.exports: any;
}

declare module '@tinymce/tinymce-react/lib/cjs/main/ts/Utils' {
  declare module.exports: any;
}

declare module '@tinymce/tinymce-react/lib/es2015/main/ts/components/Editor' {
  declare module.exports: any;
}

declare module '@tinymce/tinymce-react/lib/es2015/main/ts/components/EditorPropTypes' {
  declare module.exports: any;
}

declare module '@tinymce/tinymce-react/lib/es2015/main/ts/Events' {
  declare module.exports: any;
}

declare module '@tinymce/tinymce-react/lib/es2015/main/ts' {
  declare module.exports: any;
}

declare module '@tinymce/tinymce-react/lib/es2015/main/ts/ScriptLoader2' {
  declare module.exports: any;
}

declare module '@tinymce/tinymce-react/lib/es2015/main/ts/TinyMCE' {
  declare module.exports: any;
}

declare module '@tinymce/tinymce-react/lib/es2015/main/ts/Utils' {
  declare module.exports: any;
}

// Filename aliases
declare module '@tinymce/tinymce-react/lib/cjs/main/ts/components/Editor.js' {
  declare module.exports: $Exports<'@tinymce/tinymce-react/lib/cjs/main/ts/components/Editor'>;
}
declare module '@tinymce/tinymce-react/lib/cjs/main/ts/components/EditorPropTypes.js' {
  declare module.exports: $Exports<'@tinymce/tinymce-react/lib/cjs/main/ts/components/EditorPropTypes'>;
}
declare module '@tinymce/tinymce-react/lib/cjs/main/ts/Events.js' {
  declare module.exports: $Exports<'@tinymce/tinymce-react/lib/cjs/main/ts/Events'>;
}
declare module '@tinymce/tinymce-react/lib/cjs/main/ts/index' {
  declare module.exports: $Exports<'@tinymce/tinymce-react/lib/cjs/main/ts'>;
}
declare module '@tinymce/tinymce-react/lib/cjs/main/ts/index.js' {
  declare module.exports: $Exports<'@tinymce/tinymce-react/lib/cjs/main/ts'>;
}
declare module '@tinymce/tinymce-react/lib/cjs/main/ts/ScriptLoader2.js' {
  declare module.exports: $Exports<'@tinymce/tinymce-react/lib/cjs/main/ts/ScriptLoader2'>;
}
declare module '@tinymce/tinymce-react/lib/cjs/main/ts/TinyMCE.js' {
  declare module.exports: $Exports<'@tinymce/tinymce-react/lib/cjs/main/ts/TinyMCE'>;
}
declare module '@tinymce/tinymce-react/lib/cjs/main/ts/Utils.js' {
  declare module.exports: $Exports<'@tinymce/tinymce-react/lib/cjs/main/ts/Utils'>;
}
declare module '@tinymce/tinymce-react/lib/es2015/main/ts/components/Editor.js' {
  declare module.exports: $Exports<'@tinymce/tinymce-react/lib/es2015/main/ts/components/Editor'>;
}
declare module '@tinymce/tinymce-react/lib/es2015/main/ts/components/EditorPropTypes.js' {
  declare module.exports: $Exports<'@tinymce/tinymce-react/lib/es2015/main/ts/components/EditorPropTypes'>;
}
declare module '@tinymce/tinymce-react/lib/es2015/main/ts/Events.js' {
  declare module.exports: $Exports<'@tinymce/tinymce-react/lib/es2015/main/ts/Events'>;
}
declare module '@tinymce/tinymce-react/lib/es2015/main/ts/index' {
  declare module.exports: $Exports<'@tinymce/tinymce-react/lib/es2015/main/ts'>;
}
declare module '@tinymce/tinymce-react/lib/es2015/main/ts/index.js' {
  declare module.exports: $Exports<'@tinymce/tinymce-react/lib/es2015/main/ts'>;
}
declare module '@tinymce/tinymce-react/lib/es2015/main/ts/ScriptLoader2.js' {
  declare module.exports: $Exports<'@tinymce/tinymce-react/lib/es2015/main/ts/ScriptLoader2'>;
}
declare module '@tinymce/tinymce-react/lib/es2015/main/ts/TinyMCE.js' {
  declare module.exports: $Exports<'@tinymce/tinymce-react/lib/es2015/main/ts/TinyMCE'>;
}
declare module '@tinymce/tinymce-react/lib/es2015/main/ts/Utils.js' {
  declare module.exports: $Exports<'@tinymce/tinymce-react/lib/es2015/main/ts/Utils'>;
}
