//@flow
/* eslint-disable no-undefined */
import React from "react";
import { type BarcodeRecord } from "../../../../stores/definitions/Barcode";
import { type GlobalId } from "../../../../stores/definitions/BaseRecord";
import { type RecordType } from "../../../../stores/definitions/InventoryRecord";

/* mocking barcode objects */

export const generatedBarcode = (
  recordType: RecordType,
  globalId: GlobalId
): BarcodeRecord => {
  return {
    data: `http://localhost:8080/inventory/${recordType.toLowerCase()}/${globalId}`,
    deleteBarcodeRequest: false,
    description: "Generated by RSpace",
    id: null,
    image: undefined,
    imageUrl: `barcodes?content=http://localhost:8080/inventory/${recordType.toLowerCase()}/${globalId}&barcodeType=QR`,
    newBarcodeRequest: true,
    paramsForBackend: {},
    isDeleted: false,
    isDeletable: true,
    deletedCopy: () => null,
    descriptionIsEditable: true,
    setDescription: () => undefined,
    fetchImage: () => Promise.resolve(new File([], "", { type: "image/png" })),
    renderedDescription: <></>,
  };
};

export const persistedBarcode1: BarcodeRecord = {
  data: "50404957",
  deleteBarcodeRequest: false,
  description: "Scanned EAN-8: 50404957",
  id: null,
  image: undefined,
  imageUrl: undefined,
  newBarcodeRequest: true,
  paramsForBackend: {},
  isDeleted: false,
  isDeletable: true,
  deletedCopy: () => null,
  descriptionIsEditable: true,
  setDescription: () => undefined,
  fetchImage: () => Promise.resolve(new File([], "", { type: "image/png" })),
  renderedDescription: <></>,
};
