// This file is automatically generated by i18next-cli. Do not edit manually.
export default interface Resources {
  "about": {
    "copyright": "© 2026 ResearchSpace",
    "license": {
      "agpl": "RSpace is licensed under AGPL.",
      "oss": "RSpace is open-source, and powered by open-source libraries."
    },
    "links": {
      "changelog": "Changelog",
      "sourceCode": "Source Code",
      "website": "Website"
    },
    "logo": {
      "alt": "RSpace Logo"
    },
    "support": {
      "accountLabel": "For account and group queries, email:",
      "generalLabel": "For general support, email:"
    },
    "title": "About RSpace",
    "version": {
      "loading": "Loading version...",
      "unavailable": "Version unavailable"
    }
  },
  "admin": {

  },
  "apps": {
    "disconnect": {
      "error": "Could not disconnect from {appName}.",
      "success": "Successfully disconnected from {appName}."
    },
    "externalWorkflows": {
      "columns": {
        "container": "Container/Galaxy History",
        "created": "Invocation Created",
        "dataUploaded": "Data Uploaded",
        "invocation": "Invocation",
        "status": "Invocation Status"
      },
      "dataUploadedDesc": "Data uploaded and Workflow Invocations using that data",
      "dialogTitle": "Galaxy WorkFlow Data",
      "error": {
        "notFound": "Unable to retrieve any relevant results. Error message was: {errorMessage}",
        "seeError": "See Galaxy error",
        "timeout": "Request timed out.",
        "title": "Error",
        "unauthorized": "Invalid Galaxy API Key Please re-enter your API Key on the Apps page.",
        "unknown": "Unknown issue, please investigate whether your Galaxy Server(s) is/are running. Error message was: {errorMessage}"
      },
      "loadingAria": "Please wait, loading computational workflows associated with this field",
      "noRows": "No Data is attached to this document",
      "queryingAria": "Please wait, querying galaxy is in progress",
      "queryingTitle": "Galaxy Query In Progress",
      "showWorkflowsAria": "Show computational workflows associated with this field"
    },
    "pyrat": {
      "columnVisibility": {
        "hideSettings": "Hide column visibility settings",
        "label": "Column Visibility",
        "selectVisibleColumns": "Select visible columns",
        "showSettings": "Show column visibility settings"
      },
      "error": {
        "apiVersion": "Only version 2 of the PyRAT API is supported.",
        "badRequest": "Bad Request.",
        "network": "Network Error. Please check your connections.",
        "timeout": "Request timed out.",
        "title": "Error",
        "unauthorized": "Invalid PyRAT user or client token.",
        "unknown": "Unknown error"
      },
      "filter": {
        "hideOptions": "Hide filtering options",
        "label": "Filter",
        "showOptions": "Show filtering options"
      }
    }
  },
  "common": {
    "actions": {
      "add": "Add",
      "back": "Back",
      "cancel": "Cancel",
      "close": "Close",
      "confirm": "Confirm",
      "create": "Create",
      "delete": "Delete",
      "dismiss": "Dismiss",
      "edit": "Edit",
      "export": "Export",
      "next": "Next",
      "ok": "OK",
      "retry": "Retry",
      "save": "Save",
      "search": "Search",
      "share": "Share",
      "sign": "Sign",
      "submit": "Submit",
      "witness": "Witness"
    },
    "apiAuthentication": {
      "warningMessage": "Some functionality will not be available until an authenticated session can be established. Please try logging in again in another window. If the issue persists, please contact support.",
      "warningTitle": "Could not authenticate via API"
    },
    "confirmationDialog": {
      "inputMismatch": "Input does not match confirmation text"
    },
    "inputs": {
      "dateField": {
        "invalidDate": "Invalid date."
      },
      "optionField": {
        "deleteNewOption": "Delete New Option",
        "deleteOption": "Delete Option: {option}",
        "emptyOption": "Option value cannot be empty",
        "noOptionSelected": "No option selected"
      },
      "referenceField": {
        "notYetSupported": "Not yet supported."
      },
      "selectedFileInfo": {
        "invalidFile": "Invalid file."
      },
      "unitSelect": {
        "quantityUnits": "Quantity units"
      }
    },
    "profile": {
      "groups": {
        "activity": {
          "action": "Action",
          "show": "Show group activity",
          "time": "Time",
          "title": "User's group activity"
        },
        "autosharing": {
          "disable": "Disable autosharing",
          "disableStarted": "Reverting autoshare for {group} started successfully. You will receive a notification once it is complete.",
          "disableSuccess": "Autoshare for {group} was disabled successfully.",
          "disabled": "Disabled",
          "enable": "Enable autosharing",
          "enableAsyncSuccess": "Autoshare for {group} was enabled successfully. You will receive a notification once it is complete.",
          "enableSuccess": "Autoshare for {group} was enabled successfully.",
          "enabled": "Enabled",
          "folderName": "Folder name",
          "genericError": "Something went wrong. Please, contact support if the issue persists.",
          "inProgress": "Autosharing is in progress",
          "notApplicable": "n/a",
          "onlyLabGroups": "Autosharing is only possible for LabGroups"
        },
        "table": {
          "actions": "Actions",
          "ariaLabel": "enhanced table",
          "autosharing": "Autosharing",
          "group": "Group",
          "role": "Role"
        },
        "title": "Groups"
      },
      "oauth": {
        "connectedApps": {
          "confirmDisconnectTitle": "Confirm Disconnect",
          "disconnect": "Disconnect",
          "disconnectErrorMessage": "There was a problem disconnecting app with client ID {clientId}. Please contact support if the problem persists.",
          "disconnectErrorTitle": "Unable to disconnect app",
          "disconnectSuccessMessage": "App with client ID {clientId} was successfully disconnected.",
          "disconnectSuccessTitle": "App disconnected",
          "show": "Show Connected Apps",
          "title": "Connected Apps"
        },
        "createdApps": {
          "confirmDeleteTitle": "Confirm Deletion",
          "deleteErrorMessage": "There was a problem deleting app with client ID {clientId}.",
          "deleteErrorTitle": "Unable to delete app",
          "deleteExceptionMessage": "There was a problem deleting app with client ID {clientId}: {error}.",
          "deleteSuccessMessage": "App with client ID {clientId} was successfully deleted.",
          "deleteSuccessTitle": "App successfully deleted",
          "show": "Show Created OAuth Apps",
          "title": "OAuth Apps"
        },
        "dialog": {
          "addNewApp": "Add a new app",
          "appName": "App name",
          "clientSecret": "Client Secret",
          "confirmAppName": "Type OAuth app name to confirm",
          "copy": "Copy",
          "copyError": "Couldn't copy to clipboard. Try again manually.",
          "copySuccess": "Copied to clipboard",
          "createError": "There was a problem while creating your application. Please, try again later or contact support.",
          "createTitle": "Create an OAuth application",
          "createdTitle": "App Successfully Created",
          "validation": {
            "alphanumeric": "The application name should only contain alphanumeric symbols.",
            "maxLength": "The application name should be less than 100 symbols."
          }
        },
        "fetchError": "There was a problem fetching your apps. Please, try again.",
        "table": {
          "actions": "Actions",
          "appName": "App Name",
          "ariaLabel": "enhanced table",
          "clientId": "Client ID",
          "scope": "Scope"
        }
      },
      "raidConnections": {
        "adding": "Adding...",
        "identifier": "RAiD Identifier",
        "loadOptionsError": "Error loading RAiD identifier options: {error}",
        "noOptions": "No valid available RAiD found, or the RAiD has been used by another project group.",
        "validation": {
          "identifierMinLength": "RAiD identifier must be at least 3 characters",
          "identifierRequired": "RAiD identifier is required"
        }
      }
    },
    "search": {
      "clearTooltip": "Clear search",
      "placeholder": "Search..."
    },
    "tags": {
      "addTag": "Add Tag",
      "checkOntologyFiles": "Please check that the ontology files are correctly configured.",
      "errorFetchingTags": "Error fetching tags",
      "filterSuggestedTags": "Filter suggested tags",
      "loading": "Loading...",
      "noMatchingSuggestions": "No matching tag suggestions.",
      "noMatchingSuggestionsFromOntologies": "No matching tag suggestions from ontologies.",
      "noName": "no name",
      "noTagsAvailable": "No tags available",
      "typeTagInstead": "Simply type in the tag and press enter instead.",
      "useNewTagHint": "To use a new tag, press Enter.",
      "validation": {
        "alreadySelected": "Tag is already selected.",
        "fromSource": "From version {version} of {filename}",
        "invalidChar": "Tag contains invalid character \"{char}\".",
        "notFromOntology": "Not from an ontology",
        "tooLong": "Tag cannot exceed {maxLength} characters.",
        "tooShort": "Tag must be at least {minLength} characters long.",
        "whitespaceConsecutive": "Tags cannot contain consecutive whitespace characters.",
        "whitespacePrefix": "Tags cannot start with whitespace characters.",
        "whitespaceSuffix": "Tags cannot end with whitespace characters."
      }
    },
    "toolbar": {
      "createDocument": "CREATE DOCUMENT",
      "createRecord": "Create a record",
      "displayingLockedVersion": "Displaying version {version} of the document - this is locked for editing.",
      "folder": "Folder",
      "folderIcon": "Folder icon",
      "fromEvernote": "From Evernote",
      "fromForm": "From Form",
      "fromProtocolsIo": "From Protocols.io",
      "fromTemplate": "From Template",
      "fromWord": "From Word",
      "hideTreeBrowser": "Hide tree browser",
      "microsoftTeams": "Microsoft Teams",
      "newEntry": "New entry",
      "newForm": "New Form",
      "notebook": "Notebook",
      "notebookIcon": "Notebook Icon",
      "notifications": "Notifications",
      "protocolsIoIcon": "Protocols.io Icon",
      "receivedMessages": "Received messages",
      "saveAndClone": "Save & Clone",
      "saveAndClose": "Save & Close",
      "saveAndNew": "Save & New",
      "saveAndView": "Save & View",
      "saveAsTemplate": "SAVE AS TEMPLATE",
      "saveAsTemplateTitle": "Save as Template",
      "sendMessage": "Send a message",
      "sendMessageOnMicrosoftTeams": "Send message on MicrosoftTeams",
      "sendMessageOnSlack": "Send message on Slack",
      "slack": "Slack"
    },
    "values": {
      "none": "None"
    }
  },
  "dashboard": {

  },
  "gallery": {

  },
  "groups": {
    "createGroup": {
      "errors": {
        "requestFailed": "Your request failed due to: {message}. If this problem persists, please contact RSpace Support."
      },
      "nav": {
        "back": "Back",
        "create": "Create {groupType}",
        "next": "Next"
      },
      "openButton": "Create Group",
      "step1": {
        "heading": "Group Name",
        "hint": "Enter a name to identify the new group"
      },
      "step2": {
        "createOption": "Select {userInput}",
        "heading": "Select PI",
        "nominateHint": "Enter a single email address of a new or existing user to be asked to be group PI.",
        "nominateOtherPi": "Nominate a PI, make me Lab Admin, and supply users for pending invitations.",
        "piInvitationNote": "Note: group wont be created until PI accepts invitation",
        "roleAriaLabel": "Pi Role",
        "searchPlaceholder": "Start typing...",
        "selfPi": "Make me the group PI and invite users"
      },
      "step3": {
        "emailPlaceholder": "Enter email address",
        "inviteExistingHeading": "Invite RSpace users",
        "inviteNewHeading": "Invite new users",
        "typeHint": "type at least 3 characters"
      },
      "step4": {
        "groupNameLabel": "Group name:",
        "groupNameRequired": "You require a group name",
        "groupOwnerLabel": "Group Owner:",
        "heading": "Summary",
        "invitedMembersLabel": "Invited members:",
        "invitedNonMembersLabel": "Invited non-members:",
        "piLabel": "PI:",
        "piRequired": "You must select a PI"
      },
      "title": "Create group",
      "toast": {
        "created": "{groupName} group created successfully!",
        "requestSent": "Group creation request for {groupName} sent successfully"
      },
      "validation": {
        "invalidEmail": "Please enter a valid email address"
      }
    },
    "errors": {
      "selectGroupOwner": "Please select at least one group owner",
      "selectPi": "Please, select a PI"
    },
    "fields": {
      "groupName": "Group's identifying name",
      "optional": "(optional)",
      "selectGroupOwners": "Select group owners *",
      "selectGroupType": "Select a group type*",
      "selectMembers": "Select group members",
      "selectPi": "Select one LabGroup PI *"
    },
    "groupType": {
      "lab": "Lab Group",
      "project": "Project Group"
    },
    "raidHint": "If RAiD has been set up, you can associate a RAiD identifier with the project group after it has been created.",
    "userBox": {
      "availablePis": "Available PIs",
      "availableUsers": "Available users",
      "groupMembers": "Group members",
      "groupOwners": "Group owners",
      "groupPis": "Group PIs",
      "noUsersFound": "No users found",
      "one": "one",
      "pi": "PI",
      "search": "Search...",
      "selectOnlyPrefix": "Please, select only"
    }
  },
  "inventory": {
    "associatedRecords": {
      "button": "Inventory Items",
      "empty": "The document has no connected Inventory items.",
      "loading": "Loading"
    },
    "container": {
      "fields": {
        "canStore": {
          "containers": "Containers",
          "label": "Can Store",
          "selectAtLeastOne": "Select at least one.",
          "subsamples": "Subsamples"
        },
        "gridDimensions": {
          "chooseCommonSize": "Choose a common size",
          "columns": "Columns",
          "commonSizes": {
            "custom": "Custom",
            "freezerBox100": "100 place freezer box",
            "freezerBox169": "169 place freezer box",
            "freezerBox196": "196 place freezer box",
            "freezerBox64": "64 place freezer box",
            "freezerBox81": "81 place freezer box",
            "wellPlate12": "12 well plate",
            "wellPlate24": "24 well plate",
            "wellPlate6": "6 well plate",
            "wellPlate96": "96 well plate"
          },
          "error": "Must be at least {min}, and not more than {max}.",
          "label": "Grid Dimensions",
          "rows": "Rows",
          "specifyDimensions": "Or specify the dimensions"
        },
        "gridLabels": {
          "expandAria": "Expand grid dimension controls group",
          "title": "Configure Grid Labels"
        },
        "gridLayout": {
          "columnLabels": "Column Labels",
          "rowLabels": "Row Labels"
        },
        "organization": {
          "options": {
            "grid": {
              "explanation": "Two-dimensional container with rows and columns e.g. a well plate.",
              "label": "Grid"
            },
            "list": {
              "explanation": "Generic container for storing unordered content.",
              "label": "List"
            },
            "visual": {
              "explanation": "Container showing exact locations on an image background.",
              "label": "Visual"
            }
          },
          "type": "Type"
        }
      }
    },
    "createNew": {
      "button": "Create",
      "containers": "Containers",
      "csvImport": "CSV Import",
      "newContainer": "New Container",
      "newSample": "New Sample",
      "newTemplate": "New Template",
      "samples": "Samples",
      "subsamples": "Subsamples",
      "thirdPartyImport": "Third-Party Import"
    },
    "fields": {
      "description": {
        "label": "Description",
        "maxLength": "Description must be no longer than {max} characters (including HTML tags)."
      },
      "extraFields": {
        "addCustomField": "Add custom field.",
        "addNewField": "Add new field",
        "addOneFieldAtATime": "You can only create one field at a time.",
        "deleteField": "Delete field",
        "fieldSettings": "Field settings",
        "maxCharacters": "Must be no more than {max} characters.",
        "noLinkSet": "No link set",
        "noMoreFields": "No more fields",
        "validNumber": "Must be a valid number."
      },
      "location": {
        "label": "Location"
      },
      "name": {
        "label": "Name",
        "maxLength": "Name must be no longer than {max} characters.",
        "minLength": "Name must be at least {min} characters.",
        "nonWhitespace": "Name must include at least one non-whitespace character.",
        "suffix": {
          "alphabeticalIndex": "Alphabetical Index: A, B, C...",
          "dateOfCreation": "Date of Creation",
          "label": "Suffix:",
          "none": "None",
          "numericalIndex": "Numerical Index: 1, 2, 3..."
        }
      },
      "notes": {
        "clear": "Clear",
        "createNote": "Create note",
        "immutableNote": "Please note that once created, notes can be neither edited nor deleted.",
        "label": "Notes",
        "newNote": "New note",
        "showFewer": "Show fewer",
        "showMore": "Show more",
        "validation": {
          "empty": "Note cannot be empty.",
          "notEditable": "Notes are not editable",
          "tooLong": "Note cannot exceed {max} characters."
        }
      },
      "owner": {
        "label": "Owner",
        "unknownOwner": "Unknown Owner"
      },
      "quantity": {
        "label": "Quantity",
        "validation": {
          "positiveOrZero": "Should be a positive number or zero."
        }
      },
      "templateFields": {
        "addField": "Add field"
      }
    },
    "layout": {
      "initialScreen": {
        "navigateTo": "Navigate to:"
      },
      "sidebar": {
        "containers": "Containers",
        "exportData": "Export Data",
        "igsnIds": "IGSN IDs",
        "itemsListAriaLabel": "List existing Inventory items",
        "myBench": "My Bench",
        "navigationAriaLabel": "Inventory Sidebar Navigation",
        "otherActionsAriaLabel": "Other places and action",
        "samples": "Samples",
        "settings": "Settings",
        "subsamples": "Subsamples",
        "templates": "Templates"
      }
    },
    "permalinkNotFound": {
      "latestLink": "View the latest version",
      "typeLabels": {
        "container": "container",
        "sample": "sample",
        "sampleTemplate": "sample template",
        "subsample": "subsample"
      },
      "unversionedBody": "It may have been deleted, or you may not have permission to view it.",
      "unversionedTitle": "This {typeLabel} could not be found.",
      "versionedBody": "The version may never have existed.",
      "versionedTitle": "Version {version} of this {typeLabel} could not be found."
    },
    "sample": {
      "fields": {
        "expiryDate": {
          "expiredWarning": "This sample has expired.",
          "label": "Expiry Date"
        },
        "storageTemperature": {
          "belowAbsoluteZero": "One or more values are below absolute zero.",
          "between": "Between {min} and {max}.",
          "invalidValues": "Invalid values.",
          "label": "Storage Temperature",
          "max": "Max",
          "min": "Min",
          "none": "None",
          "notSpecified": "The storage temperature for this item is currently not specified.",
          "presets": {
            "ambient": "Ambient",
            "frozen": "Frozen",
            "liquidNitrogen": "Liquid Nitrogen",
            "refrigerated": "Refrigerated",
            "ultFrozen": "ULT Frozen"
          },
          "specify": "Specify",
          "unit": "Unit"
        }
      }
    },
    "search": {
      "controls": {
        "nameDialog": {
          "cancel": "Cancel",
          "duplicateName": "This name is already taken. Please modify it.",
          "helperText": "Please enter a unique name, no longer than 32 characters.",
          "invalidLength": "Please enter minimum 1 and maximum 32 characters.",
          "name": "Name",
          "save": "Save"
        },
        "saveSearch": {
          "defaultName": "New saved search",
          "saveSearch": "Save search"
        },
        "searchbar": {
          "clearSearch": "Clear search",
          "search": "Search"
        },
        "sort": {
          "ascending": "(A-Z)",
          "cannotSortView": "Cannot sort {view} view.",
          "descending": "(Z-A)",
          "sortBy": "Sort by"
        },
        "status": {
          "current": "Current",
          "currentAndInTrash": "Current & In Trash",
          "inTrash": "In Trash"
        },
        "type": {
          "all": "All",
          "container": "Container",
          "containers": "Containers",
          "enterQueryFirst": "Enter a search query first.",
          "sample": "Sample",
          "samples": "Samples",
          "samplesNotInContainers": "Samples cannot be found in containers.",
          "samplesNotOnBenches": "Samples cannot be found on benches.",
          "subsample": "Subsample",
          "subsamples": "Subsamples",
          "template": "Template",
          "templates": "Templates",
          "templatesNotInContainers": "Templates cannot be found in containers.",
          "templatesNotOnBenches": "Templates cannot be found on benches."
        },
        "view": {
          "card": "Card View",
          "changeView": "Change view",
          "grid": "Grid View",
          "image": "Image View",
          "list": "List View",
          "tree": "Tree View"
        }
      },
      "details": {
        "loadingBatchEditing": "Loading batch editing"
      },
      "emptyListing": {
        "alt": "Empty Listing",
        "body": "Nothing here yet.",
        "title": "Empty {recordType}"
      },
      "helpTitle": "Info on searching Inventory.",
      "navigation": {
        "ariaLabel": "Search and Navigation"
      },
      "noActiveResult": {
        "body": "Let's get you started with the system.",
        "guideLink": "Get Started Guide",
        "title": "Welcome to RSpace Inventory!"
      },
      "noResults": {
        "title": "No results.",
        "tryDifferentSearch": "Try searching for a different term, or use the advanced search to change search filters."
      },
      "resultsTable": {
        "actionInProgress": "Action In Progress",
        "allRows": "{count} (All)",
        "ariaLabel": "Search results",
        "select": "Select",
        "selectAll": "Select all",
        "selection": {
          "all": "All",
          "current": "Current",
          "inTrash": "In Trash",
          "invert": "Invert",
          "mine": "Mine",
          "none": "None",
          "notMine": "Not Mine"
        }
      }
    },
    "subsample": {
      "batch": {
        "imageAlt": "What the {count} subsamples look like",
        "itemsTableLabel": "Subsamples being edited",
        "largeImageWarning": "Please note, on slower network connections uploading large images may trigger an error.",
        "quantityMixedUnitsWarning": "Quantity cannot be edited as the subsamples use a variety of different units.",
        "sections": {
          "barcodes": "Barcodes",
          "details": "Details",
          "information": "Information",
          "overview": "Overview"
        },
        "title": "Batch editing {count} subsamples"
      }
    }
  },
  "public": {
    "footer": {
      "contactInfo": "If you wish to obtain more information about this item, please contact the research data management department at {institution}.",
      "generatedBy": "This page was generated by {institution} using RSpace Public Pages."
    },
    "geolocation": {
      "boxHeading": "Box",
      "description": "Description",
      "eastboundLongitude": "Eastbound Longitude",
      "inPolygonPointHeading": "In Polygon Point",
      "latitude": "Latitude",
      "longitude": "Longitude",
      "northboundLatitude": "Northbound Latitude",
      "placeHeading": "Place",
      "pointHeading": "Point",
      "pointLatitude": "Point {index} Latitude",
      "pointLongitude": "Point {index} Longitude",
      "polygonHeading": "Polygon",
      "southboundLatitude": "Southbound Latitude",
      "westboundLongitude": "Westbound Longitude"
    },
    "headings": {
      "alternateIdentifiers": "Alternate Identifiers",
      "customFields": "Custom Fields",
      "dates": "Dates",
      "descriptions": "Descriptions",
      "extraFields": "Extra Fields",
      "general": "General",
      "geolocations": "Geolocations",
      "inventory": "Inventory",
      "optionalFields": "Optional Fields",
      "otherInformation": "Other Information",
      "rspacePublicPages": "RSpace Public Pages",
      "subjects": "Subjects"
    },
    "images": {
      "igsnLogoAlt": "IGSN Logo",
      "institutionLogoAlt": "Institution Logo"
    },
    "labels": {
      "creator": "Creator:",
      "creatorAffiliation": "Creator Affiliation:",
      "creatorAffiliationIdentifier": "Creator Affiliation Identifier:",
      "igsnId": "IGSN ID:",
      "name": "Name:",
      "organisation": "Organisation:",
      "publicationYear": "Publication Year:",
      "resourceType": "Resource Type:",
      "urlAvailableAfterPublishing": "URL available after publishing"
    },
    "links": {
      "doiAddressTitle": "DOI - address",
      "igsnHomepageTitle": "IGSN Homepage",
      "itemLandingPageTitle": "Item landing page"
    },
    "table": {
      "name": "Name",
      "value": "Value"
    },
    "values": {
      "none": "None"
    }
  },
  "system": {
    "errors": {
      "networkProblem": "There is a problem, please try again later"
    },
    "ror": {
      "curationRequestLink": "curation request form.",
      "heading": "Research Organization Registry (ROR) Integration",
      "institutionalIdHeading": "Institutional ROR ID",
      "introPrefix": "By associating a",
      "introSuffix": "with your RSpace instance, you ensure the research outputs produced in RSpace are connected with your research organisation. All research outputs with a DOI will automatically include the ROR ID in their affiliation metadata.",
      "invalidFormatHelp": "Please ensure the ROR ID is one of the following formats:",
      "linkButton": "Link",
      "linkHelpAction": "Link",
      "linkHelpPrefix": "ROR ID found. Click",
      "linkHelpSuffix": "to associate with this RSpace Instance.",
      "registryLink": "ROR registry",
      "rorIdLink": "ROR ID",
      "searchHelpMiddle": "to ensure you are adding the correct ROR ID. If your institution does not have a ROR ID, you can submit a",
      "searchHelpPrefix": "You can search the",
      "searchTooltip": "Search Registry",
      "statusLabel": "Status:",
      "unlinkButton": "UnLink",
      "unlinkHelpAction": "UNLINK",
      "unlinkHelpPrefix": "A ROR ID is linked to this RSpace Instance. Click on",
      "unlinkHelpSuffix": "to remove the association. Future published or updated DOIs will not include the ROR ID."
    }
  },
  "workspace": {
    "export": {
      "dialog": {
        "defaultExportName": {
          "exportData": "Export Data",
          "groupAllWork": "{groupName} - all work",
          "userAllWork": "{username} - all work"
        },
        "panes": {
          "export": "Export",
          "filestoreExportConfiguration": "Filestore Links Export Configuration",
          "raid": "RAiD",
          "setupRepository": "Setup Repository"
        }
      },
      "fileStore": {
        "filters": {
          "changeButton": "Change file filtering options",
          "dialogTitle": "Filtering options for filestore files",
          "excludeLabel": "File types to exclude (comma-separated list)",
          "heading": "File filters",
          "sizeLimitLabel": "Individual file size limit (MB)"
        },
        "foundLinks": {
          "columns": {
            "linkType": "Link type",
            "notes": "Notes",
            "path": "Full path on the File System"
          },
          "heading": "Filestore links found in exported content",
          "showButton": "Show found filestore links",
          "summary": "Exported content contains {filesCount} filestore link from {fileSystemsCount} File System."
        },
        "login": {
          "allLoggedIn": "You are logged into all File Systems referenced by filestore links.",
          "authProblem": "Authentication problem, check your username and password or contact your System Admin",
          "checkButton": "Check File Systems login details",
          "columns": {
            "loggedInAs": "Logged in as",
            "name": "File System Name"
          },
          "dialogTitle": "File Systems login status",
          "heading": "File Systems that require login",
          "loggedInToast": "Logged in as {userName}",
          "loginButton": "Login to remaining File Systems",
          "notAllLoggedIn": "You are not logged into all File Systems referenced by filestore links. Please login to remaining File Systems or some linked files may be omitted during the export.",
          "notLoggedIn": "Not logged in",
          "passwordBlank": "Password cannot be blank",
          "passwordLabel": "Password",
          "submitButton": "Login",
          "usernameBlank": "Username cannot be blank",
          "usernameLabel": "Username"
        },
        "scan": {
          "columns": {
            "path": "Full path on the File System",
            "reason": "Reason",
            "size": "Size",
            "type": "Type"
          },
          "dialogTitle": "Availability scan results",
          "heading": "Link availability scan",
          "includedHeading": "Included files from {name}",
          "runHint": "Before continuing please run the filestore links availability scan, which will report on any unaccessible or filtered links.",
          "scanButton": "Scan filestore links",
          "showLastButton": "Show last scan results",
          "skippedHeading": "Skipped files from {name}"
        }
      },
      "format": {
        "htmlXml": {
          "depthInfinity": "Include linked documents to depth infinity",
          "depthLevel": "Include linked documents to depth {level}",
          "depthNone": "Don't include linked documents",
          "descriptionLabel": "Export Description (optional)",
          "foldersNote": "Linked folders and notebooks are never included",
          "includeLinksLabel": "Should linked RSpace documents be included in export?"
        },
        "pdf": {
          "checkboxes": {
            "annotations": "Include image annotations",
            "comments": "Include comments",
            "footerEndOnly": "Insert date footer at file end only",
            "lastModified": "Include last modified dates for fields",
            "provenance": "Include provenance information",
            "restartPageNumbers": "Restart page numbering for each document"
          },
          "dateFooterLabel": "Date on page footer",
          "dateType": {
            "created": "Created",
            "exported": "Exported",
            "lastModified": "Last modified date"
          },
          "nameHelper": "Name your file",
          "nameLabel": "File name *",
          "pageFormatLabel": "Page format: ",
          "pageSize": {
            "a4": "A4",
            "letter": "Letter"
          },
          "setDefault": "Set {pageSize} as default"
        },
        "word": {
          "nameLabel": "Name your file",
          "pageFormatLabel": "Page format: ",
          "pageSize": {
            "a4": "A4",
            "letter": "Letter"
          },
          "setDefault": "Set {pageSize} as default."
        }
      },
      "repositories": {
        "choiceAriaLabel": "Repository choice",
        "choiceLabel": "Please choose one of your configured repositories to submit your export to:",
        "common": {
          "descriptionLabel": "Description *",
          "titleLabel": "Title *"
        },
        "dataverse": {
          "descriptionHelper": "Please add a relevant description for your export",
          "licenseHelper": "Please select your license",
          "licenseLabel": "License *",
          "metadataLanguageHelper": "Please select your metadata language (only if target Dataverse supports it)",
          "metadataLanguageLabel": "Metadata language",
          "subjectHelper": "Please select your subject",
          "subjectLabel": "Subject *",
          "titleHelper": "Please choose a title, >3 symbols"
        },
        "dmp": {
          "associateLabel": "Associate export with a Data Management Plans (DMPs)",
          "zenodoLimit": "Only one DMP can be associated with an export to Zenodo."
        },
        "dryad": {
          "abstractHelper": "Please add a relevant abstract for your export",
          "abstractLabel": "Add an abstract *",
          "grantingOrgHelper": "Enter 3 of more characters to filter list",
          "grantingOrgLabel": "Granting Organization *",
          "licenseHelper": "Please select your license",
          "licenseLabel": "License *",
          "researchDomainHelper": "Please select your research domain",
          "researchDomainLabel": "Research Domain *",
          "titleHelper": "Please choose a title, >3 symbols"
        },
        "figshare": {
          "descriptionHelper": "Please add a relevant description for your export",
          "draft": "Draft",
          "licenseHelper": "Please select your license",
          "licenseLabel": "License *",
          "publish": "Publish",
          "publishingStatus": "Publishing status",
          "subjectHelper": "Please select your subject",
          "subjectLabel": "Subject *",
          "titleHelper": "Please choose a title, >3 symbols"
        },
        "tags": {
          "clearButton": "Clear Tags",
          "label": "Tags and Controlled Vocabulary Terms"
        },
        "user": {
          "addDialogTitle": "Add new person",
          "addTooltip": "Add author/contact",
          "author": "Author",
          "contact": "Contact",
          "emailLabel": "Email *",
          "nameLabel": "Name *",
          "peopleHelper": "Add author(s) AND contact(s) to your repository export.",
          "peopleLabel": "People",
          "typeLabel": "Type *"
        }
      }
    }
  }
}
