// This file is automatically generated by i18next-cli. Do not edit manually.
export default interface Resources {
  "about": {
    "copyright": "© 2026 ResearchSpace",
    "license": {
      "agpl": "RSpace is licensed under AGPL.",
      "oss": "RSpace is open-source, and powered by open-source libraries."
    },
    "links": {
      "changelog": "Changelog",
      "sourceCode": "Source Code",
      "website": "Website"
    },
    "logo": {
      "alt": "RSpace Logo"
    },
    "support": {
      "accountLabel": "For account and group queries, email:",
      "generalLabel": "For general support, email:"
    },
    "title": "About RSpace",
    "version": {
      "loading": "Loading version...",
      "unavailable": "Version unavailable"
    }
  },
  "admin": {

  },
  "apps": {
    "disconnect": {
      "error": "Could not disconnect from {appName}.",
      "success": "Successfully disconnected from {appName}."
    },
    "dmpIntegrations": {
      "argos": "Argos",
      "dialog": {
        "argosDocsLink": "See <0>argos.openaire.eu</0> and our <1>Argos integration docs</1> for more.",
        "argosImportDesc": "Importing a DMP from <strong>argos.openaire.eu</strong> will make it available to view and reference within RSpace.",
        "cancelButton": "Cancel",
        "closeButton": "Close",
        "columns": {
          "contactAffiliation": "Contact Affiliation",
          "contactName": "Contact Name",
          "created": "Created",
          "createdAt": "Created At",
          "description": "Description",
          "grant": "Grant",
          "id": "Id",
          "label": "Label",
          "modified": "Modified",
          "modifiedAt": "Modified At",
          "name": "Name",
          "select": "Select",
          "title": "Title",
          "updatedAt": "Updated At"
        },
        "dmpassistantDocsLink": "See <0>dmp-pgd.ca</0> and our <1>DMP Assistant integration docs</1> for more.",
        "dmpassistantImportDesc": "Importing DMPs from <strong>dmp-pgd.ca</strong> will make them available to view and reference within RSpace. Select one or more and click Import.",
        "dmponlineDocsLink": "See <0>dmponline.dcc.ac.uk</0> and our <1>DMPonline integration docs</1> for more.",
        "dmponlineImportDesc": "Importing a DMP from <strong>dmponline.dcc.ac.uk</strong> will make it available to view and reference within RSpace.",
        "dmptoolDocsLink": "See <0>dmptool.org</0> and our <1>DMPTool integration docs</1> for more.",
        "dswDocsLink": "See <0>https://guide.ds-wizard.org/en/latest</0> and our <1>DSW / FAIR Wizard integration docs</1> for more.",
        "dswImportDesc": "Importing a project from <strong>{serverAlias}</strong> will make it available to view and reference as a DMP within RSpace.",
        "error": {
          "couldNotGet": "Could not get DMPs: {message}",
          "couldNotImport": "Could not import DMP",
          "fetchFailed": "Fetch failed.",
          "importFailed": "Import failed.",
          "loadFailed": "Failed to load listing of DMPs. Please try refreshing.",
          "unableToLoad": "Unable to load DMPs.",
          "unableToLoadProjects": "Unable to load projects."
        },
        "forMoreInfo": "For more information <a>visit our docs</a>.",
        "importButton": "Import",
        "importButtonCount": "Import ({count})",
        "importDmpIntoGallery": "Import a DMP into the Gallery",
        "importDmpsIntoGallery": "Import DMPs into the Gallery",
        "importSuccess": "Success.",
        "importSuccessMessage": "DMP {planId} was successfully imported.",
        "loadingDmps": "Loading listing of DMPs.",
        "noDmpIsSelected": "No DMP is selected.",
        "noDmpSelected": "No DMP selected.",
        "noDmps": "No DMPs",
        "noProjects": "No projects found",
        "notSpecified": "Not Specified",
        "selectAllAriaLabel": "Select all DMPs on this page",
        "selectDmpAriaLabel": "Select {title}",
        "selectPlanAriaLabel": "Select plan: {label}"
      },
      "dmpAssistant": "DMP Assistant",
      "dmponline": "DMPonline",
      "dmptool": "DMPTool",
      "dsw": "DSW / FAIR Wizard",
      "scope": {
        "both": "Both",
        "mine": "Mine",
        "name": "DMP Scope Options",
        "public": "Public"
      }
    },
    "externalWorkflows": {
      "columns": {
        "container": "Container/Galaxy History",
        "created": "Invocation Created",
        "dataUploaded": "Data Uploaded",
        "invocation": "Invocation",
        "status": "Invocation Status"
      },
      "dataUploadedDesc": "Data uploaded and Workflow Invocations using that data",
      "dialogTitle": "Galaxy WorkFlow Data",
      "error": {
        "notFound": "Unable to retrieve any relevant results. Error message was: {errorMessage}",
        "seeError": "See Galaxy error",
        "timeout": "Request timed out.",
        "title": "Error",
        "unauthorized": "Invalid Galaxy API Key Please re-enter your API Key on the Apps page.",
        "unknown": "Unknown issue, please investigate whether your Galaxy Server(s) is/are running. Error message was: {errorMessage}"
      },
      "loadingAria": "Please wait, loading computational workflows associated with this field",
      "noRows": "No Data is attached to this document",
      "queryingAria": "Please wait, querying galaxy is in progress",
      "queryingTitle": "Galaxy Query In Progress",
      "showWorkflowsAria": "Show computational workflows associated with this field"
    },
    "page": {
      "nothingHere": "Nothing here!",
      "sections": {
        "disabled": {
          "description": "The following Apps are not currently enabled on this account. Click on an App card for setup instructions on how to enable the integration.",
          "title": "Disabled"
        },
        "enabled": {
          "description": "The following Apps are enabled on this account. Click on an App card to modify or disable the integration.",
          "title": "Enabled"
        },
        "external": {
          "description": "These RSpace applications have been built by partners or other external software developers. Note, ResearchSpace does not provide direct support for these integrations.",
          "title": "Third-party RSpace Integrations"
        },
        "unavailable": {
          "description": "The following Apps need to be enabled by your System Administrator before they can be used; please get in touch with them directly to set this up.",
          "title": "Unavailable"
        }
      },
      "title": "Apps"
    },
    "pyrat": {
      "columnVisibility": {
        "hideSettings": "Hide column visibility settings",
        "label": "Column Visibility",
        "selectVisibleColumns": "Select visible columns",
        "showSettings": "Show column visibility settings"
      },
      "error": {
        "apiVersion": "Only version 2 of the PyRAT API is supported.",
        "badRequest": "Bad Request.",
        "network": "Network Error. Please check your connections.",
        "timeout": "Request timed out.",
        "title": "Error",
        "unauthorized": "Invalid PyRAT user or client token.",
        "unknown": "Unknown error"
      },
      "filter": {
        "hideOptions": "Hide filtering options",
        "label": "Filter",
        "showOptions": "Show filtering options"
      },
      "insertButton": "Insert"
    },
    "tinyMce": {
      "chemCard": {
        "atoms": "Atoms",
        "bonds": "Bonds",
        "charge": "Charge",
        "formula": "Formula",
        "mass": "Mass",
        "monoisotopicMassSubscript": "mi",
        "name": "Name",
        "structureAlt": "Chemical structure"
      },
      "galaxy": {
        "allSelectedFilesCombined": "All selected files will be combined into a 'list dataset', which will be available for immediate use. The list dataset will be named after this RSpace document, using the format:",
        "annotationMetadata": "The data you have uploaded to Galaxy has links back to RSpace present in its 'annotation' metadata.",
        "chooseAttachedFiles": "Choose attached files to be uploaded to Galaxy.",
        "chooseGalaxyServer": "Choose a Galaxy Server",
        "datasetNameFormat": "\"RSPACE_\" + document name + \"_\" + global ID of document + \"_\" + name of field data was attached to + \"_\" + global ID of that field.",
        "historyViewedHere": "Your new history can be viewed here:",
        "opensInNewTab": "(Opens in new tab.) (You must be logged into Galaxy or you will see 'Unnamed History')",
        "rspaceWillStoreDetails": "RSpace will store the details of the files you have uploaded and also any use of these files on Galaxy in Invocations will be tracked.",
        "uploadToGalaxyNote": "When you click 'Upload to Galaxy', a new history will be created in Galaxy named after your RSpace document with the same name as the 'list dataset' described above. Your chosen data will be uploaded to this new history. You can make this history active in Galaxy by switching to it.",
        "workflowIconNote": "Data uploaded to this history is now viewable by clicking on the 'workflow' icon which will appear in your document. Any invocations in Galaxy which use this data will be tracked in RSpace, the data being updated whenever you click on this 'workflow' icon. The badge count on the workflow icon indicates how many Galaxy Invocations are using the uploaded data."
      },
      "internalLink": {
        "alwaysLatest": "Always automatically update link to latest version",
        "dialogTitle": "Internal link version options",
        "headCells": {
          "modified": "Modified",
          "modifiedBy": "Modified by",
          "name": "Name",
          "version": "Version"
        },
        "updateRevisionLink": "Update revision link"
      },
      "omero": {
        "filterResults": "Filter results",
        "hideImageGrid": "hide image grid",
        "noImage": "no image",
        "seeInOmero": "see in omero",
        "unavailableAlt": "Unavailable"
      },
      "pubchem": {
        "casNumber": "CAS Number",
        "formula": "Formula",
        "pubchemId": "PubChem ID",
        "viewOnPubChem": "View on PubChem"
      },
      "shortcuts": {
        "instructions": {
          "actions": {
            "clickInput": "Click on the input field next to the command you would like to configure.",
            "clickSave": "Click on 'Save'.",
            "pressKey": "On your keyboard, press the key combination you would like to use for that command."
          },
          "symbols": {
            "clickInput": "Click on the input field next to the symbol you would like to configure.",
            "clickSave": "Click on 'Save'.",
            "clickSymbol": "Click on the symbol to configure its shortcut.",
            "pressKey": "On your keyboard, press the key combination you would like to use for that symbol.",
            "sectionsHint": "All configurable symbols are divided into sections. Click on a section to find the desired symbol. For example, Greek characters are in the 'Extended Latin' section."
          }
        },
        "instructionsTitle": "Instructions",
        "reservedShortcutsNote": "Here's <0>a list</0> of reserved shortcuts already used by the editor. Please note that single keys, or Shift + single key, are not accepted, as these shortcuts will interfere with editing. Good choices for shortcuts are Ctrl + Shift + number/letter, or Alt + Shift + number/letter.",
        "tabActions": "Actions",
        "tabSymbols": "Symbols",
        "toggleInstructions": "Toggle instructions"
      },
      "sidebarInfo": {
        "closeAll": "Close All"
      },
      "snapGene": {
        "applySettings": "Apply Settings",
        "circular": "Circular",
        "copyToClipboard": "Copy to Clipboard",
        "dnaPreviewAlt": "DNA preview",
        "enzymeSites": "Enzyme sites",
        "imageType": "Image type",
        "linear": "Linear",
        "orfTable": "ORF table",
        "reset": "Reset",
        "showEnzymes": "Show enzymes",
        "showORFs": "Show ORFs",
        "tabDnaPreview": "DNA preview",
        "viewAsFasta": "View as FASTA"
      }
    }
  },
  "common": {
    "actions": {
      "add": "Add",
      "back": "Back",
      "cancel": "Cancel",
      "clear": "Clear",
      "close": "Close",
      "confirm": "Confirm",
      "create": "Create",
      "delete": "Delete",
      "dismiss": "Dismiss",
      "done": "Done",
      "edit": "Edit",
      "export": "Export",
      "invite": "Invite",
      "next": "Next",
      "ok": "OK",
      "retry": "Retry",
      "save": "Save",
      "search": "Search",
      "select": "Select",
      "share": "Share",
      "sign": "Sign",
      "submit": "Submit",
      "witness": "Witness"
    },
    "apiAuthentication": {
      "warningMessage": "Some functionality will not be available until an authenticated session can be established. Please try logging in again in another window. If the issue persists, please contact support.",
      "warningTitle": "Could not authenticate via API"
    },
    "appBar": {
      "brandingAlt": "branding",
      "maintenancePopup": "A scheduled maintenance window begins {{relativeTime}}.",
      "operatingAs": "Operating as:",
      "orcidAdd": "Add an ORCID iD to your <0>profile</0>."
    },
    "confirmationDialog": {
      "inputMismatch": "Input does not match confirmation text"
    },
    "errorBoundary": {
      "message": "Something went wrong! Please refresh the page. If this error persists, please contact <0>support@researchspace.com</0> with details of when the issue happens."
    },
    "folderSelection": {
      "selectedFolder": "Selected folder",
      "selectedFolderWithColon": "Selected folder:",
      "title": "Select Folder"
    },
    "folderTree": {
      "addSubfolder": "Add subfolder to {{folderName}}",
      "createFolder": {
        "folderName": "Folder Name",
        "title": "Create New Folder",
        "validation": "Folder name is required"
      },
      "failedFolders": "Failed to load folders",
      "failedSubfolders": "Failed to load subfolders",
      "loadMore": "Load More",
      "loading": "Loading..."
    },
    "groupDetails": {
      "members": "Members",
      "principalInvestigators": "Principal Investigators",
      "users": "Users",
      "viewGroup": "View Group"
    },
    "imageEditing": {
      "rotateClockwise": "rotate clockwise",
      "rotateCounterClockwise": "rotate counter clockwise",
      "title": "Edit Image"
    },
    "inputs": {
      "dateField": {
        "invalidDate": "Invalid date."
      },
      "optionField": {
        "deleteNewOption": "Delete New Option",
        "deleteOption": "Delete Option: {option}",
        "emptyOption": "Option value cannot be empty",
        "noOptionSelected": "No option selected"
      },
      "referenceField": {
        "notYetSupported": "Not yet supported."
      },
      "selectedFileInfo": {
        "invalidFile": "Invalid file."
      },
      "unitSelect": {
        "quantityUnits": "Quantity units"
      }
    },
    "integrationErrors": {
      "calira": {
        "invalidToken": "Invalid Calira user or client token. Please re-connect to Calira.",
        "notFound": "Please contact an Admin: Calira returned HTTP status 404. Is Calira endpoint set correctly?"
      },
      "omero": {
        "notFound": "The requested data was not found on this instance of Omero",
        "sessionExpired": "Your session with Omero has expired. Please re-connect to Omero on the Apps page."
      },
      "timeout": "Request timed out.",
      "title": "Error",
      "tryAgainLater": "There is a problem, please try again later",
      "unknownRelogin": "Unknown issue, please attempt to relogin to RSpace."
    },
    "ketcher": {
      "discardChanges": {
        "discard": "Discard",
        "keepEditing": "Keep Editing",
        "text": "You have unsaved changes. Are you sure you want to discard them?",
        "title": "Discard changes?"
      }
    },
    "profile": {
      "accountActivity": {
        "action": "Action",
        "show": "Show account activity",
        "time": "Time",
        "title": "User's account activity"
      },
      "groups": {
        "activity": {
          "action": "Action",
          "show": "Show group activity",
          "time": "Time",
          "title": "User's group activity"
        },
        "autosharing": {
          "additionalInfo": {
            "p1": "Enabling autosharing for a member will ensure that all their current and future documents and notebooks will be shared automatically with the \"read\" permission with this group.",
            "p2": "Edit permission can be granted or items can be unshared through the \"Manage Shared Documents\" section as usual.",
            "p3": "This setting is revertible and you can always manually change the autoshare status of any non-PI member in your lab group.",
            "title": "Additional Information",
            "toggle": "Toggle additional information"
          },
          "disable": "Disable autosharing",
          "disableGroup": {
            "button": "disable autosharing",
            "text": "Disabling group-wide autosharing will unshare all work shared by non-PI members in the <strong>{{groupDisplayName}}</strong> group. Once disabled, new non-PI members will no longer have autosharing automatically enabled on joining.",
            "title": "Disable group-wide autosharing"
          },
          "disableStarted": "Reverting autoshare for {group} started successfully. You will receive a notification once it is complete.",
          "disableSuccess": "Autoshare for {group} was disabled successfully.",
          "disableUserText": "Disabling autosharing will unshare all work for user <strong>{{username}}</strong> from group <strong>{{group}}</strong>.<br/><br/>Individual documents and notebooks can still be shared as usual.",
          "disabled": "Disabled",
          "enable": "Enable autosharing",
          "enableAsyncSuccess": "Autoshare for {group} was enabled successfully. You will receive a notification once it is complete.",
          "enableGroup": {
            "button": "enable autosharing",
            "text": "Enabling group-wide autosharing will enable autosharing for all non-PI members in the <strong>{{groupDisplayName}}</strong> group. Once enabled, new non-PI members will have autosharing automatically enabled on joining.",
            "title": "Enable group-wide autosharing"
          },
          "enableSuccess": "Autoshare for {group} was enabled successfully.",
          "enableUserText": "Autosharing work will ensure that all current and future documents and notebooks for user <strong>{{username}}</strong> will be shared with group<strong> {{group}}</strong> with the READ permission.<br/><br/>The EDIT permission can be granted or items can be unshared from the \"Manage Shared Documents\" section as usual.<br/><br/>Please enter a name for the folder that the work will be shared into.",
          "enabled": "Enabled",
          "folderName": "Folder name",
          "genericError": "Something went wrong. Please, contact support if the issue persists.",
          "inProgress": "Autosharing is in progress",
          "notApplicable": "n/a",
          "onlyLabGroups": "Autosharing is only possible for LabGroups",
          "settingInProgress": "Please allow some time for the setting to take into-effect. You will receive a notification when it is complete"
        },
        "bioOntologies": {
          "allow": {
            "button": "allow BioPortal Ontologies",
            "text": "Allowing BioPortal Ontologies for tags will query data from the <a href=\"https://bioportal.bioontology.org/ontologies\"> BioPortal Ontologies Portal</a> and use the values to generate tag suggestions",
            "title": "Allow BioPortal Ontologies to be used for tag suggestions"
          },
          "disabledButton": "disallow Ontologies",
          "disallow": {
            "button": "disallow BioPortal Ontologies",
            "text": "Disallowing use of BioPortal Ontologies will restrict tag suggestions: values from the <a href=\"https://bioportal.bioontology.org/ontologies\"> BioPortal Ontologies Portal</a> will no longer be suggested.",
            "title": "Disallow BioPortal Ontologies to be used for tag suggestions"
          },
          "onlyEnterprise": "Only available on Enterprise"
        },
        "dialog": {
          "addError": "Unable to add/invite the user(s). Please check browser console for error details, and contact support if the problem persists.",
          "availableUsers": "Available users",
          "membersTitle": "{action} members",
          "selectedUsers": "Selected users"
        },
        "editBar": {
          "cancel": "Cancel",
          "editTooltip": "Edit profile settings",
          "errorMessage": "Your request failed: {error}. Please contact support if this problem persists.",
          "hideGroup": "Hide the group from public listings",
          "noProfile": "There is no profile information for this group.",
          "piCanEdit": "PI can edit all work in this lab group.",
          "placeholder": "Please enter a short description of this group...",
          "profileDescription": "Profile description",
          "save": "Save",
          "subheader": "Profile"
        },
        "groupActivity": {
          "title": "Group Activity",
          "user": "User"
        },
        "manager": {
          "cancel": "Cancel",
          "confirm": "Confirm",
          "contactAdmin": "Please contact your system administrator to enable this feature",
          "notAvailableForCollaboration": "Not available for collaboration groups",
          "onlyEnterprise": "Only available on Enterprise"
        },
        "members": "Members",
        "ontologies": {
          "disabledButton": "disable Ontologies",
          "enforce": {
            "button": "enforce Ontologies",
            "text": "Enforcing ontologies for tags will result in all new tags coming from autopopulated values read from ontology files. These ontology files must be shared with a Group and any user creating new tags must be a member of that Group. Collaboration Groups can be used for this purpose. Tags can not be created from free text and will not autopopulate from existing tags.",
            "title": "Enforce ontologies for tags"
          },
          "onlyEnterprise": "Only available on Enterprise",
          "unenforce": {
            "button": "un-enforce Ontologies",
            "text": "Un-enforcing use of ontologies for tags will result in group members being able to enter free text when creating new tags. They may also use values autopopulated from ontology files. These ontology files may be their own, or may be files shared with them. They may also use values autopopulated from existing tags.",
            "title": "Un-enforce use of ontologies for tags"
          }
        },
        "publication": {
          "disable": {
            "button": "disable publication",
            "text": "Disabling group-wide publication will prevent non PI members of the <strong>{{groupDisplayName}}</strong> group publishing their own documents. They may still unpublish previously published documents.",
            "title": "Disable group-wide publication"
          },
          "disabledButton": "disable publication",
          "enable": {
            "button": "enable publication",
            "text": "Enabling group-wide publication will allow non-PI members in the <strong>{{groupDisplayName}}</strong> group to publish and unpublish their own documents. PIs can also unpublish these documents.",
            "title": "Enable group publication"
          },
          "notAvailableForCollaboration": "Not available for collaboration groups",
          "onlyEnterprise": "Only available on Enterprise"
        },
        "seo": {
          "disable": {
            "button": "disable published seo",
            "text": "Disabling group-wide SEO of public documents will prevent non PI members of the <strong>{{groupDisplayName}}</strong> group from allowing SEO bots to index their documents. Their published documents will not appear on the 'Published' page visible to the public.",
            "title": "Disable group-wide SEO of public documents"
          },
          "disabledButton": "disable published seo",
          "enable": {
            "button": "enable published seo",
            "text": "Enabling group-wide SEO for published documents will allow non-PI members in the <strong>{{groupDisplayName}}</strong> group to choose to have their documents indexed by SEO bots. These documents will also be shown on the 'Published' page visible to the public.",
            "title": "Enable group-wide SEO for published documents"
          },
          "notAvailableForCollaboration": "Not available for collaboration groups",
          "onlyEnterprise": "Only available on Enterprise"
        },
        "table": {
          "actions": "Actions",
          "ariaLabel": "enhanced table",
          "autosharing": "Autosharing",
          "group": "Group",
          "role": "Role"
        },
        "title": "Groups",
        "userList": {
          "search": "Search..."
        }
      },
      "oauth": {
        "connectedApps": {
          "confirmDisconnectTitle": "Confirm Disconnect",
          "disconnect": "Disconnect",
          "disconnectErrorMessage": "There was a problem disconnecting app with client ID {clientId}. Please contact support if the problem persists.",
          "disconnectErrorTitle": "Unable to disconnect app",
          "disconnectSuccessMessage": "App with client ID {clientId} was successfully disconnected.",
          "disconnectSuccessTitle": "App disconnected",
          "show": "Show Connected Apps",
          "title": "Connected Apps"
        },
        "createdApps": {
          "confirmDeleteTitle": "Confirm Deletion",
          "deleteErrorMessage": "There was a problem deleting app with client ID {clientId}.",
          "deleteErrorTitle": "Unable to delete app",
          "deleteExceptionMessage": "There was a problem deleting app with client ID {clientId}: {error}.",
          "deleteSuccessMessage": "App with client ID {clientId} was successfully deleted.",
          "deleteSuccessTitle": "App successfully deleted",
          "show": "Show Created OAuth Apps",
          "title": "OAuth Apps"
        },
        "dialog": {
          "addNewApp": "Add a new app",
          "appName": "App name",
          "clientSecret": "Client Secret",
          "confirmAppName": "Type OAuth app name to confirm",
          "copy": "Copy",
          "copyError": "Couldn't copy to clipboard. Try again manually.",
          "copySuccess": "Copied to clipboard",
          "createError": "There was a problem while creating your application. Please, try again later or contact support.",
          "createTitle": "Create an OAuth application",
          "createdTitle": "App Successfully Created",
          "secretWarning": "Please write down the client secret. <strong>It will not be available once you close this window.</strong>",
          "validation": {
            "alphanumeric": "The application name should only contain alphanumeric symbols.",
            "maxLength": "The application name should be less than 100 symbols."
          }
        },
        "fetchError": "There was a problem fetching your apps. Please, try again.",
        "table": {
          "actions": "Actions",
          "appName": "App Name",
          "ariaLabel": "enhanced table",
          "clientId": "Client ID",
          "scope": "Scope"
        }
      },
      "raidConnections": {
        "adding": "Adding...",
        "confirmDisassociateText": "Are you sure you want to disassociate the RAiD identifier <strong>{{raidTitle}}</strong> ({{raidIdentifier}}) from this project group?",
        "confirmDisassociateTitle": "Confirm Disassociation",
        "connectedTo": "connected to:",
        "currently": "Currently",
        "disabledForProjectType": "RAiD is disabled for this project - only project groups can have RAiD connections.",
        "disassociate": "Disassociate",
        "errorLoadingGroupInfo": "Error loading group info: {error}",
        "errorLoadingIntegrationInfo": "Error loading RAiD integration info: {error}",
        "errorPrefix": "Error: {error}",
        "groupNotFound": "Group not found, or you may not have permission to view this group.",
        "identifier": "RAiD Identifier",
        "loadOptionsError": "Error loading RAiD identifier options: {error}",
        "noConnectedServers": "RAiD has been enabled, but no RAiD servers have been connected yet. Please go to the <a href=\"/apps\">Apps page</a> and add a RAiD server.",
        "noOptions": "No valid available RAiD found, or the RAiD has been used by another project group.",
        "notAvailable": "RAiD is not available for this RSpace instance. Please contact your system administrator to enable RAiD.",
        "notConnected": "Not connected",
        "notEnabled": "RAiD is not enabled for your account. To add or change RAiD connections, go to the <a href=\"/apps\">Apps page</a> and enable RAiD.",
        "previously": "Previously",
        "title": "RAiD Connections",
        "validation": {
          "identifierMinLength": "RAiD identifier must be at least 3 characters",
          "identifierRequired": "RAiD identifier is required"
        }
      }
    },
    "pubchemImport": {
      "importSelected": "Import Selected",
      "importing": "Importing...",
      "title": "Import from PubChem"
    },
    "search": {
      "clearTooltip": "Clear search",
      "placeholder": "Search..."
    },
    "searchDialog": {
      "advancedSearch": "advanced search",
      "apachePage": "Apache page",
      "expandField": "Expand field",
      "luceneTip": "Tip: Create powerful Lucene queries by prefixing your query with <0>l:</0>",
      "moreInfo": "For more information, see <0>advanced search</0> and the related <1>Apache page</1>.",
      "query": "Search query"
    },
    "shareDialog": {
      "changeFolder": "Change Folder",
      "changeLocation": "Change",
      "snippetsSharedNote": "Shared snippets can be found in the <0>SNIPPETS_Shared</0> folder, inside the Snippets section of the Gallery."
    },
    "stoichiometry": {
      "addReagent": {
        "addChemical": "Add Chemical",
        "name": "Name",
        "smilesString": "SMILES String",
        "title": "Add New Chemical",
        "validation": {
          "nameRequired": "Name is required",
          "smilesRequired": "SMILES string is required"
        }
      },
      "inventoryUpdate": {
        "dialogTitle": "Update Inventory Stock",
        "inStock": "In Stock",
        "molecule": "Molecule",
        "permanentlyReduceWarning": "This will permanently reduce inventory quantities.",
        "remaining": "Remaining",
        "saving": "Saving...",
        "updateInventoryStock": "Update Inventory Stock",
        "willUse": "Will Use"
      },
      "tableToolbar": {
        "columns": "Columns",
        "exportToCsv": "Export to CSV"
      }
    },
    "tags": {
      "addTag": "Add Tag",
      "checkOntologyFiles": "Please check that the ontology files are correctly configured.",
      "errorFetchingTags": "Error fetching tags",
      "filterSuggestedTags": "Filter suggested tags",
      "loading": "Loading...",
      "metadata": {
        "controlledVocabularyName": "Controlled Vocabulary Name",
        "controlledVocabularyVersion": "Controlled Vocabulary Version",
        "term": "Term",
        "termUri": "Term's URI",
        "view": "View metadata"
      },
      "noMatchingSuggestions": "No matching tag suggestions.",
      "noMatchingSuggestionsFromOntologies": "No matching tag suggestions from ontologies.",
      "noName": "no name",
      "noTagsAvailable": "No tags available",
      "typeTagInstead": "Simply type in the tag and press enter instead.",
      "useNewTagHint": "To use a new tag, press Enter.",
      "validation": {
        "alreadySelected": "Tag is already selected.",
        "fromSource": "From version {version} of {filename}",
        "invalidChar": "Tag contains invalid character \"{char}\".",
        "notFromOntology": "Not from an ontology",
        "tooLong": "Tag cannot exceed {maxLength} characters.",
        "tooShort": "Tag must be at least {minLength} characters long.",
        "whitespaceConsecutive": "Tags cannot contain consecutive whitespace characters.",
        "whitespacePrefix": "Tags cannot start with whitespace characters.",
        "whitespaceSuffix": "Tags cannot end with whitespace characters."
      }
    },
    "toolbar": {
      "createDocument": "CREATE DOCUMENT",
      "createRecord": "Create a record",
      "displayingLockedVersion": "Displaying version {version} of the document - this is locked for editing.",
      "folder": "Folder",
      "folderIcon": "Folder icon",
      "fromEvernote": "From Evernote",
      "fromForm": "From Form",
      "fromProtocolsIo": "From Protocols.io",
      "fromTemplate": "From Template",
      "fromWord": "From Word",
      "hideTreeBrowser": "Hide tree browser",
      "microsoftTeams": "Microsoft Teams",
      "newEntry": "New entry",
      "newForm": "New Form",
      "notebook": "Notebook",
      "notebookIcon": "Notebook Icon",
      "notifications": "Notifications",
      "print": "Print",
      "protocolsIoIcon": "Protocols.io Icon",
      "receivedMessages": "Received messages",
      "saveAndClone": "Save & Clone",
      "saveAndClose": "Save & Close",
      "saveAndNew": "Save & New",
      "saveAndView": "Save & View",
      "saveAsTemplate": "SAVE AS TEMPLATE",
      "saveAsTemplateTitle": "Save as Template",
      "sendMessage": "Send a message",
      "sendMessageOnMicrosoftTeams": "Send message on MicrosoftTeams",
      "sendMessageOnSlack": "Send message on Slack",
      "slack": "Slack"
    },
    "userDetails": {
      "accountDisabled": "Disabled",
      "accountEnabled": "Enabled",
      "accountStatus": "Account Status",
      "email": "Email",
      "lastLogin": "Last login:",
      "openProfile": "Open profile",
      "sendMessage": "Send a message"
    },
    "values": {
      "none": "None"
    },
    "warningBar": {
      "unsavedChanges": "Unsaved changes"
    }
  },
  "dashboard": {

  },
  "gallery": {
    "filestoreLogin": {
      "couldNotAuthenticate": "Could not authenticate",
      "login": "Login",
      "password": "Password",
      "title": "Filestore Login",
      "username": "Username",
      "wrongCredentials": "Wrong credentials?"
    },
    "landingPage": {
      "filestoreEnabledError": "Error checking if filestores are enabled.",
      "invalidSection": "Not a valid Gallery section."
    },
    "loadMore": "Load More",
    "snippetPreview": {
      "error": "Error: {error}",
      "loadError": "Failed to load snippet content",
      "loading": "Loading snippet content...",
      "noContent": "No content available",
      "title": "Snippet Preview: {name}"
    }
  },
  "groups": {
    "createGroup": {
      "errors": {
        "requestFailed": "Your request failed due to: {message}. If this problem persists, please contact RSpace Support."
      },
      "nav": {
        "back": "Back",
        "create": "Create {groupType}",
        "next": "Next"
      },
      "openButton": "Create Group",
      "step1": {
        "heading": "Group Name",
        "hint": "Enter a name to identify the new group"
      },
      "step2": {
        "createOption": "Select {userInput}",
        "heading": "Select PI",
        "nominateHint": "Enter a single email address of a new or existing user to be asked to be group PI.",
        "nominateOtherPi": "Nominate a PI, make me Lab Admin, and supply users for pending invitations.",
        "piInvitationNote": "Note: group wont be created until PI accepts invitation",
        "roleAriaLabel": "Pi Role",
        "searchPlaceholder": "Start typing...",
        "selfPi": "Make me the group PI and invite users"
      },
      "step3": {
        "emailPlaceholder": "Enter email address",
        "inviteExistingHeading": "Invite RSpace users",
        "inviteNewHeading": "Invite new users",
        "typeHint": "type at least 3 characters"
      },
      "step4": {
        "groupNameLabel": "Group name:",
        "groupNameRequired": "You require a group name",
        "groupOwnerLabel": "Group Owner:",
        "heading": "Summary",
        "invitedMembersLabel": "Invited members:",
        "invitedNonMembersLabel": "Invited non-members:",
        "piLabel": "PI:",
        "piRequired": "You must select a PI"
      },
      "title": "Create group",
      "toast": {
        "created": "{groupName} group created successfully!",
        "requestSent": "Group creation request for {groupName} sent successfully"
      },
      "validation": {
        "invalidEmail": "Please enter a valid email address"
      }
    },
    "errors": {
      "selectGroupOwner": "Please select at least one group owner",
      "selectPi": "Please, select a PI"
    },
    "fields": {
      "groupName": "Group's identifying name",
      "optional": "(optional)",
      "selectGroupOwners": "Select group owners *",
      "selectGroupType": "Select a group type*",
      "selectMembers": "Select group members",
      "selectPi": "Select one LabGroup PI *"
    },
    "groupType": {
      "lab": "Lab Group",
      "project": "Project Group"
    },
    "raidHint": "If RAiD has been set up, you can associate a RAiD identifier with the project group after it has been created.",
    "userBox": {
      "availablePis": "Available PIs",
      "availableUsers": "Available users",
      "groupMembers": "Group members",
      "groupOwners": "Group owners",
      "groupPis": "Group PIs",
      "noUsersFound": "No users found",
      "one": "one",
      "pi": "PI",
      "search": "Search...",
      "selectOnlyPrefix": "Please, select only"
    }
  },
  "inventory": {
    "associatedRecords": {
      "button": "Inventory Items",
      "empty": "The document has no connected Inventory items.",
      "loading": "Loading"
    },
    "baseRecord": {
      "editSessionExpired": {
        "body": "Another user may be editing this {recordType}. Please copy any information you need and then press <strong>Cancel</strong>.",
        "title": "Your editing session has expired"
      }
    },
    "container": {
      "content": {
        "placeMarkers": {
          "actions": {
            "open": "Open",
            "remove": "Remove"
          },
          "columns": {
            "actions": "Actions",
            "content": "Content",
            "location": "Location"
          },
          "emptyLocation": "Empty Location",
          "emptyLocationHelper": "This location can be chosen as the destination in a move operation."
        }
      },
      "fields": {
        "canStore": {
          "containers": "Containers",
          "label": "Can Store",
          "selectAtLeastOne": "Select at least one.",
          "subsamples": "Subsamples"
        },
        "gridDimensions": {
          "chooseCommonSize": "Choose a common size",
          "columns": "Columns",
          "commonSizes": {
            "custom": "Custom",
            "freezerBox100": "100 place freezer box",
            "freezerBox169": "169 place freezer box",
            "freezerBox196": "196 place freezer box",
            "freezerBox64": "64 place freezer box",
            "freezerBox81": "81 place freezer box",
            "wellPlate12": "12 well plate",
            "wellPlate24": "24 well plate",
            "wellPlate6": "6 well plate",
            "wellPlate96": "96 well plate"
          },
          "error": "Must be at least {min}, and not more than {max}.",
          "label": "Grid Dimensions",
          "rows": "Rows",
          "specifyDimensions": "Or specify the dimensions"
        },
        "gridLabels": {
          "expandAria": "Expand grid dimension controls group",
          "title": "Configure Grid Labels"
        },
        "gridLayout": {
          "columnLabels": "Column Labels",
          "rowLabels": "Row Labels"
        },
        "organization": {
          "options": {
            "grid": {
              "explanation": "Two-dimensional container with rows and columns e.g. a well plate.",
              "label": "Grid"
            },
            "list": {
              "explanation": "Generic container for storing unordered content.",
              "label": "List"
            },
            "visual": {
              "explanation": "Container showing exact locations on an image background.",
              "label": "Visual"
            }
          },
          "type": "Type"
        }
      }
    },
    "contextMenu": {
      "actions": {
        "addToBasket": "Add to Basket",
        "create": "Create",
        "duplicate": "Duplicate",
        "export": "Export",
        "makeTopLevel": "Make Top-level",
        "more": "More actions",
        "move": "Move",
        "printBarcode": "Print Barcode",
        "removeFromThisBasket": "Remove from This Basket",
        "restore": "Restore",
        "trash": "Trash"
      },
      "createDialog": {
        "change": "Change",
        "columns": {
          "defaultValue": "Default Value",
          "field": "Field"
        },
        "fields": {
          "copies": "Copies",
          "count": "Count"
        },
        "helpTitle": "Info on creating new items.",
        "itemType": "Type of item to create",
        "loading": "Loading...",
        "noFields": "No fields.",
        "noOptions": "No options available."
      }
    },
    "createNew": {
      "button": "Create",
      "containers": "Containers",
      "csvImport": "CSV Import",
      "newContainer": "New Container",
      "newSample": "New Sample",
      "newTemplate": "New Template",
      "samples": "Samples",
      "subsamples": "Subsamples",
      "thirdPartyImport": "Third-Party Import"
    },
    "fields": {
      "attachments": {
        "actions": {
          "browseGallery": "Browse Gallery",
          "upload": "Upload"
        },
        "columns": {
          "actions": "Actions",
          "name": "Name"
        },
        "linkGalleryItems": "Link to existing items in the Gallery.",
        "noDescription": "No description",
        "noFileAttached": "No File Attached",
        "summary": "Attach files of any type, e.g. images, documents, or chemistry files.",
        "toggle": {
          "hide": "Hide attachment listing",
          "none": "No current attachments",
          "show": "Show attachment listing"
        },
        "uploadFromDevice": "Upload a file from your device.",
        "validation": {
          "missingGlobalId": "\"{name}\" does not have an RSpace Global Id",
          "noFolders": "Folders cannot be attached to Inventory records.",
          "noSnippets": "Snippets cannot be attached to Inventory records."
        }
      },
      "barcodes": {
        "actions": {
          "cannotDeleteGenerated": "Cannot delete generated barcodes",
          "deleteAfterClicked": "Barcode will be deleted once this item is saved.",
          "previewQrCode": "Preview as QR code",
          "previewUnsupported": "QR code preview is not supported.",
          "printAll": "Print All",
          "printAllBarcodes": "Print all barcodes",
          "printQrCode": "Print QR code",
          "printUnsupported": "Barcode print is not supported or you do not have permission.",
          "remove": "Remove",
          "removeNeedsEdit": "First press Edit to remove this barcode.",
          "save": "Save",
          "scan": "Scan a barcode to associate.",
          "scanNeedsEdit": "Press Edit to scan a barcode."
        },
        "alerts": {
          "dataTooLong": "Data is too long.",
          "unableToRetrieveBarcodeImage": "Unable to retrieve barcode image.",
          "unableToRetrieveBarcodeImages": "Unable to retrieve barcode images.",
          "unsupportedBarcode": "Unsupported barcode"
        },
        "columns": {
          "actions": "Actions",
          "description": "Description"
        },
        "noDescription": "No description",
        "scannedDescription": "Scanned {format}: {value}",
        "summary": "Scan an existing barcode and associate it with this item.",
        "toggle": {
          "hide": "Hide barcodes listing",
          "none": "No current barcodes",
          "show": "Show barcodes listing"
        }
      },
      "description": {
        "label": "Description",
        "maxLength": "Description must be no longer than {max} characters (including HTML tags)."
      },
      "extraFields": {
        "addCustomField": "Add custom field.",
        "addNewField": "Add new field",
        "addOneFieldAtATime": "You can only create one field at a time.",
        "deleteField": "Delete field",
        "fieldSettings": "Field settings",
        "fieldTypes": {
          "link": "Link",
          "number": "Number",
          "text": "Text"
        },
        "fields": {
          "fieldName": "Field name",
          "fieldType": "Field type",
          "relationType": "Relation type"
        },
        "groups": {
          "editing": "Editing extra field with name {name}",
          "new": "New extra field"
        },
        "link": {
          "relationHelper": "Pick a DataCite relation type",
          "targetHelper": "Paste a Global ID, or use the Browse buttons above.",
          "targetNotFound": "{globalId} does not exist, or you do not have permission to view it."
        },
        "maxCharacters": "Must be no more than {max} characters.",
        "noLinkSet": "No link set",
        "noMoreFields": "No more fields",
        "updateField": {
          "apply": "Apply",
          "ariaCancel": "Cancel update",
          "ariaUpdate": "Update field",
          "cancel": "Cancel",
          "discard": "Discard",
          "update": "Update"
        },
        "validNumber": "Must be a valid number.",
        "validation": {
          "duplicateName": "You either already have a field with that name or that name is not permitted.",
          "emptyName": "Name should not be empty.",
          "nameTooLong": "Name must be no longer than 255 characters."
        }
      },
      "link": {
        "editor": {
          "browseEln": "Browse ELN",
          "browseInventory": "Browse Inventory",
          "latest": "Latest",
          "pinVersion": "Pin version",
          "pinVersionFor": "Pin version for {globalId}",
          "pinnedVersion": "Pinned to v{version}",
          "targetGlobalId": "Target Global ID"
        },
        "elnPicker": {
          "ariaLabel": "Browse the ELN for a link target",
          "cancel": "Cancel",
          "choose": "Choose",
          "title": "Browse ELN"
        },
        "relatedInventoryItems": {
          "loading": "Loading...",
          "none": "No Inventory items link to this {recordTypeName}.",
          "title": "Related inventory items"
        },
        "targetBrowser": {
          "ariaLabel": "Browse Inventory for link target",
          "title": "Browse Inventory"
        }
      },
      "location": {
        "label": "Location"
      },
      "name": {
        "label": "Name",
        "maxLength": "Name must be no longer than {max} characters.",
        "minLength": "Name must be at least {min} characters.",
        "nonWhitespace": "Name must include at least one non-whitespace character.",
        "suffix": {
          "alphabeticalIndex": "Alphabetical Index: A, B, C...",
          "dateOfCreation": "Date of Creation",
          "label": "Suffix:",
          "none": "None",
          "numericalIndex": "Numerical Index: 1, 2, 3..."
        }
      },
      "notes": {
        "clear": "Clear",
        "createNote": "Create note",
        "immutableNote": "Please note that once created, notes can be neither edited nor deleted.",
        "label": "Notes",
        "newNote": "New note",
        "showFewer": "Show fewer",
        "showMore": "Show more",
        "validation": {
          "empty": "Note cannot be empty.",
          "notEditable": "Notes are not editable",
          "tooLong": "Note cannot exceed {max} characters."
        }
      },
      "owner": {
        "label": "Owner",
        "unknownOwner": "Unknown Owner"
      },
      "quantity": {
        "label": "Quantity",
        "validation": {
          "positiveOrZero": "Should be a positive number or zero."
        }
      },
      "tags": {
        "label": "Tags",
        "none": "None",
        "validation": {
          "maxLength": "Tags must be no longer than {max} characters.",
          "minLength": "Each tag cannot be less than {min} characters."
        }
      },
      "templateFields": {
        "addField": "Add field",
        "alias": {
          "custom": "Custom",
          "defaults": {
            "aliquot": "Aliquot",
            "component": "Component",
            "individual": "Individual",
            "piece": "Piece",
            "portion": "Portion",
            "section": "Section",
            "subsample": "Subsample",
            "unit": "Unit",
            "volume": "Volume"
          },
          "explanation": "The name for subsamples of the samples created from this template.",
          "helperText": "Please enter at least {min} characters, and no more than {max}",
          "label": "Subsample Alias",
          "minimumPlaceholder": "Minimum 2 char.",
          "plural": "Plural",
          "singular": "Singular"
        },
        "customField": {
          "defaultDescription": "Default Description",
          "defaultValue": "Default Value",
          "deleteField": "Delete field",
          "deleteNewField": "Delete new field",
          "deleteOptions": {
            "keep": "Keep field in existing samples",
            "remove": "Remove field from existing samples"
          },
          "mandatory": "Mandatory",
          "name": "Name",
          "noMoreFields": "No more fields",
          "type": "Type",
          "validation": {
            "duplicateName": "You either already have a field with that name or that name is not permitted",
            "emptyName": "Name cannot be empty",
            "nameTooLong": "Name cannot be longer than 50 characters",
            "optionsNotUnique": "All values must be unique.",
            "optionsRequired": "One or more values are required."
          },
          "values": "Values",
          "valuesExplanation": "The set of available options. Any selected values will be the default when creating samples."
        },
        "defaultValue": {
          "addValue": "Add Value",
          "allRelationshipTypes": "All relationship types",
          "allowedRelationshipTypes": "Allowed relationship types",
          "allowedRelationshipTypesExplanation": "The DataCite relationship types that links may use on samples created from this template. Leave empty to allow all relationship types.",
          "none": "None"
        },
        "move": {
          "down": "Down",
          "label": "Move",
          "toBottom": "To Bottom",
          "toTop": "To Top",
          "up": "Up"
        },
        "quantityUnits": {
          "defaultScale": "Default Scale",
          "label": "Quantity Units",
          "mass": "Mass",
          "unitType": "Unit Type",
          "unitless": "Unitless",
          "volume": "Volume"
        }
      }
    },
    "formSections": {
      "accessPermissions": "Access Permissions",
      "attachments": "Attachments",
      "barcodes": "Barcodes",
      "containersBeingEdited": "Containers being edited",
      "customFields": "Custom Fields",
      "details": "Details",
      "identifiers": "Identifiers",
      "information": "Information",
      "itemsBeingEdited": "Items being edited",
      "locationsAndContent": "Locations and Content",
      "notes": "Notes",
      "overview": "Overview",
      "parentSample": "Parent Sample",
      "sampleFields": "Sample Fields",
      "samples": "Samples",
      "samplesBeingEdited": "Samples being edited"
    },
    "identifierConfirm": {
      "cancelButton": "CANCEL",
      "create": {
        "body": "An IGSN ID in <strong>Draft</strong> state will be created. No metadata will be made public at this stage.",
        "title": "You are about to create an Identifier"
      },
      "publish": {
        "body": "The IGSN ID landing page, DataCite Commons, and the DataCite APIs will be updated with these changes.<br /><br /><strong>Please ensure the IGSN ID metadata you provided does not contain any information you do not want to make public before publishing, as this action cannot be fully undone.</strong><br /><br />Do you want to proceed?",
        "title": "You are about to publish this Identifier"
      },
      "retract": {
        "body": "The IGSN ID will be set to <strong>Registered</strong>. It will be removed from DataCite Commons and the Public API, and the landing page will not display any metadata.<br /><br /><strong>The metadata will remain visible to other DataCite Members via the Member API.</strong><br /><br />Do you want to proceed?",
        "title": "You are about to retract this Identifier"
      }
    },
    "igsnManagement": {
      "actions": {
        "ariaLabel": "Actions menu for selected IGSN IDs",
        "button": "Actions",
        "delete": {
          "subheader": "Does not delete any linked item.",
          "title": "Delete"
        },
        "print": {
          "subheader": "Print barcode labels for selected IGSN IDs.",
          "title": "Print"
        }
      },
      "browserTitle": "Manage IGSN IDs | RSpace Inventory",
      "bulkRegister": {
        "button": "Bulk Register",
        "createdMessage": "IGSN IDs in Draft state will be created.",
        "dialogTitle": "Bulk Register IGSN IDs",
        "numberLabel": "Number of new IGSN IDs",
        "register": "Register",
        "summary": "You can also bulk-register IGSN IDs to be used at a later date, such as a field collection trip:"
      },
      "cancel": "Cancel",
      "landmark": "IGSN management main content",
      "pageTitle": "IGSN Management Page",
      "sections": {
        "ids": "IGSN IDs",
        "manage": "Manage IGSN IDs",
        "register": "Register IGSN IDs"
      }
    },
    "igsnTable": {
      "columns": {
        "doi": "DOI",
        "linkedItem": "Linked Item",
        "state": "State"
      },
      "exportToCsv": "Export to CSV",
      "filters": {
        "all": "All",
        "hasLinkedItem": "Has Linked Item",
        "linkedItem": "Linked Item",
        "linkedItemStates": {
          "no": "No",
          "yes": "Yes"
        },
        "noLinkedItem": "No Linked Item",
        "state": "State",
        "stateOptions": {
          "all": {
            "subheader": "Show all IGSN IDs",
            "title": "All"
          },
          "draft": {
            "subheader": "A newly created IGSN ID without any public metadata.",
            "title": "Draft"
          },
          "findable": {
            "subheader": "A published, searchable IGSN ID with a public landing page.",
            "title": "Findable"
          },
          "registered": {
            "subheader": "An IGSN ID that has been retracted from public access.",
            "title": "Registered"
          }
        }
      },
      "noLinkedItem": "None",
      "noRows": "No IGSN IDs",
      "scan": "Scan",
      "searchButtonPrefix": "Search for IGSN",
      "searchPlaceholder": "Search IGSN IDs...",
      "selectIgsn": "Select IGSN"
    },
    "import": {
      "actions": {
        "import": "Import"
      },
      "columnMapping": {
        "columns": {
          "convertTo": "Convert To",
          "foundCsvColumns": "Found CSV Columns"
        },
        "nameRequiredError": "It is required that a column be mapped to 'Name', as all {recordType} must have a name.",
        "nameRequiredInfo": "You must select one column to convert to the Name of the {recordType}.",
        "noCsv": "Column conversion is only available once a CSV file has been selected.",
        "parentSampleRequired": "You must select one column that refers to a Sample.",
        "quantityConversion": "Quantity conversion is not set. All imported {recordType} will have a total quantity of 1 {unitLabel}.",
        "templateMismatch": "The columns of the CSV file do not match the selected template. Please edit the fields of the template or the supplied CSV file.",
        "unconverted": "You have one or more columns selected without conversion. The columns' data will not be used."
      },
      "customDetails": "Custom details",
      "customFieldName": "Custom Field Name",
      "file": {
        "clearFileAndMappings": "Clear File and Mappings",
        "errorDetails": "Error details:",
        "replaceCsvFile": "Replace {recordType} CSV File",
        "selectCsvFile": "Select {recordType} CSV File",
        "title": "Upload CSV File"
      },
      "helpTitle": "Info on importing.",
      "importDocumentation": "Import Documentation",
      "sections": {
        "columnConversion": "CSV Column Conversion Settings",
        "templateDetails": "Template Details"
      },
      "templateDetails": {
        "chooseExistingTemplate": "Choose existing template.",
        "createNewTemplate": "Create new template.",
        "selectTemplate": "Select a template from which these imported samples will be created."
      },
      "title": "IMPORT",
      "types": {
        "containers": "Containers",
        "samples": "Samples",
        "subsamples": "Subsamples"
      }
    },
    "layout": {
      "initialScreen": {
        "navigateTo": "Navigate to:"
      },
      "sidebar": {
        "containers": "Containers",
        "exportData": "Export Data",
        "igsnIds": "IGSN IDs",
        "itemsListAriaLabel": "List existing Inventory items",
        "myBench": "My Bench",
        "navigationAriaLabel": "Inventory Sidebar Navigation",
        "otherActionsAriaLabel": "Other places and action",
        "samples": "Samples",
        "settings": "Settings",
        "subsamples": "Subsamples",
        "templates": "Templates"
      }
    },
    "materialsListing": {
      "actions": {
        "addItems": "Add items",
        "closeQuantityEditor": "Close Quantity Editor",
        "deleteList": "Delete List",
        "editQuantities": "Edit Quantities",
        "editTip": "Tip: to edit an item click its Global ID, then the Edit button in the new browser tab.",
        "export": "Export",
        "move": {
          "alreadyOnBench": "All items are already on your bench.",
          "none": "Nothing to move.",
          "unsavedChanges": "Cannot move whilst there are unsaved changes."
        },
        "moveAllToBench": "Move all to my bench",
        "viewInNewTab": "View in new tab"
      },
      "dialog": {
        "creatingList": "Creating list...",
        "emptyList": "Use \"Add items\" to add materials to this list.",
        "exportOptions": "Export Options",
        "helpTitle": "Info on using Lists of Materials.",
        "newTitle": "New List of Materials (Inventory)",
        "pickInventoryItems": "Pick Inventory Items",
        "savingChanges": "Saving changes...",
        "title": "List of Materials (Inventory)",
        "updatingList": "Updating list..."
      },
      "launcher": {
        "newList": "New List of Materials",
        "showAssociatedLists": "Show list of materials associated with this field"
      },
      "metadata": {
        "description": "Description",
        "id": "ID",
        "name": "List Name"
      },
      "table": {
        "batchSelect": {
          "all": "All",
          "invert": "Invert",
          "none": "None"
        },
        "columns": {
          "additionalConsumedQuantity": "Additional Consumed Quantity",
          "batchEdit": "Batch Edit",
          "consumedQuantity": "Consumed Quantity",
          "globalId": "Global ID",
          "inventoryQuantity": "Inventory Quantity",
          "location": "Location",
          "name": "Name",
          "owner": "Owner",
          "updateInventoryQuantity": "Update Inventory Quantity"
        },
        "linkedQuantities": "Linked quantities",
        "removeFromList": "Remove from list",
        "subsamplesOnly": "For subsamples only"
      }
    },
    "moreInfo": {
      "closeSidebar": "Close more info sidebar",
      "created": "Created",
      "globalId": "Global ID",
      "lastModified": "Last Modified",
      "linkedDocuments": {
        "columns": {
          "linkedVersion": "Linked version",
          "name": "Name",
          "owner": "Owner",
          "relation": "Relation"
        },
        "documentsTable": "Documents containing this item",
        "inventoryLinksTable": "Inventory items linking to this item",
        "latest": "Latest",
        "noDocuments": "No documents",
        "noInventoryLinks": "No inventory links",
        "show": "Show Linked Documents",
        "title": "Linked Documents"
      },
      "updateSamples": "Update Samples",
      "versionHistory": {
        "columns": {
          "by": "By",
          "modified": "Modified",
          "version": "Version"
        },
        "current": " (current)",
        "none": "No version history is available for this item yet.",
        "title": "Version history",
        "view": "View version history",
        "viewing": " (viewing)"
      }
    },
    "permalinkNotFound": {
      "latestLink": "View the latest version",
      "typeLabels": {
        "container": "container",
        "sample": "sample",
        "sampleTemplate": "sample template",
        "subsample": "subsample"
      },
      "unversionedBody": "It may have been deleted, or you may not have permission to view it.",
      "unversionedTitle": "This {typeLabel} could not be found.",
      "versionedBody": "The version may never have existed.",
      "versionedTitle": "Version {version} of this {typeLabel} could not be found."
    },
    "print": {
      "dialog": {
        "loading": "Loading...",
        "nothingToPreview": "Nothing to preview",
        "previewLabelLayout": "Preview Barcode Label Layout",
        "printError": "Print error.",
        "printSelected": "Print selected ({count})",
        "resolveError": "Please resolve error.",
        "title": "Print Options",
        "unableToRetrieveBarcodeImages": "Unable to retrieve barcode images."
      },
      "options": {
        "basic": "Basic",
        "eachBarcodeOnce": "Each barcode once",
        "eachBarcodeTwice": "Each barcode twice (raffle book)",
        "full": "Full",
        "fullWidth": "Full width (4cm).",
        "globalId": "Global ID",
        "halfWidth": "Half width (2cm).",
        "horizontalLayout": "Applying a horizontal layout.",
        "identifierType": "Identifier Type",
        "igsnId": "IGSN ID",
        "igsnMissing": "Some of the selected records do not have an IGSN ID.",
        "labelPrinter": "Label Printer",
        "labelPrinterAutoSize": "For label printers size is set automatically (to match a range of label sizes).",
        "labelPrinterCopies": "For label printers, the number of copies is set to 1 per item.",
        "labelPrinterHint": "Print one label per sticker (Zebra printer).",
        "large": "Large",
        "printCopies": "Print Copies",
        "printLayout": "Print Layout",
        "printSize": "Print Size",
        "printerType": "Printer Type",
        "small": "Small",
        "standardPrinter": "Standard Printer",
        "standardPrinterHint": "Print multiple labels per sheet (e.g. A4 / A3 / Letter)."
      }
    },
    "recordTree": {
      "navigateToContainer": "Navigate to container"
    },
    "recordsTable": {
      "columns": {
        "globalId": "Global ID",
        "name": "Name"
      }
    },
    "sample": {
      "fields": {
        "expiryDate": {
          "expiredWarning": "This sample has expired.",
          "label": "Expiry Date"
        },
        "source": {
          "label": "Source",
          "options": {
            "labCreated": "Lab Created",
            "other": "Other",
            "vendorSupplied": "Vendor Supplied"
          }
        },
        "storageTemperature": {
          "belowAbsoluteZero": "One or more values are below absolute zero.",
          "between": "Between {min} and {max}.",
          "invalidValues": "Invalid values.",
          "label": "Storage Temperature",
          "max": "Max",
          "min": "Min",
          "none": "None",
          "notSpecified": "The storage temperature for this item is currently not specified.",
          "presets": {
            "ambient": "Ambient",
            "frozen": "Frozen",
            "liquidNitrogen": "Liquid Nitrogen",
            "refrigerated": "Refrigerated",
            "ultFrozen": "ULT Frozen"
          },
          "specify": "Specify",
          "unit": "Unit"
        }
      }
    },
    "search": {
      "controls": {
        "nameDialog": {
          "cancel": "Cancel",
          "duplicateName": "This name is already taken. Please modify it.",
          "helperText": "Please enter a unique name, no longer than 32 characters.",
          "invalidLength": "Please enter minimum 1 and maximum 32 characters.",
          "name": "Name",
          "save": "Save"
        },
        "saveSearch": {
          "defaultName": "New saved search",
          "saveSearch": "Save search"
        },
        "searchbar": {
          "clearSearch": "Clear search",
          "search": "Search"
        },
        "sort": {
          "ascending": "(A-Z)",
          "cannotSortView": "Cannot sort {view} view.",
          "descending": "(Z-A)",
          "sortBy": "Sort by"
        },
        "status": {
          "current": "Current",
          "currentAndInTrash": "Current & In Trash",
          "inTrash": "In Trash"
        },
        "type": {
          "all": "All",
          "container": "Container",
          "containers": "Containers",
          "enterQueryFirst": "Enter a search query first.",
          "sample": "Sample",
          "samples": "Samples",
          "samplesNotInContainers": "Samples cannot be found in containers.",
          "samplesNotOnBenches": "Samples cannot be found on benches.",
          "subsample": "Subsample",
          "subsamples": "Subsamples",
          "template": "Template",
          "templates": "Templates",
          "templatesNotInContainers": "Templates cannot be found in containers.",
          "templatesNotOnBenches": "Templates cannot be found on benches."
        },
        "view": {
          "card": "Card View",
          "changeView": "Change view",
          "grid": "Grid View",
          "image": "Image View",
          "list": "List View",
          "tree": "Tree View"
        }
      },
      "details": {
        "loadingBatchEditing": "Loading batch editing"
      },
      "emptyListing": {
        "alt": "Empty Listing",
        "body": "Nothing here yet.",
        "title": "Empty {recordType}"
      },
      "feedback": {
        "ariaLabel": "Search status",
        "containerContents": "{count} container contents found.",
        "errorGlobalId": "ERROR",
        "foundGlobalId": "Found {globalId}.",
        "itemsInBasket": "{count} items found in {basketName}.",
        "itemsOnBench": "{count} items found on this bench.",
        "loading": "Loading...",
        "results": "{count} search results found.",
        "samples": "{count} samples found.",
        "samplesOfTemplate": "{count} samples of the template found.",
        "subsamples": "{count} subsamples found.",
        "templates": "{count} templates found.",
        "thisBasket": "this basket",
        "topLevelContainers": "{count} top-level containers found.",
        "undetermined": "Results cannot be fully determined."
      },
      "helpTitle": "Info on searching Inventory.",
      "navigation": {
        "ariaLabel": "Search and Navigation"
      },
      "noActiveResult": {
        "body": "Let's get you started with the system.",
        "guideLink": "Get Started Guide",
        "title": "Welcome to RSpace Inventory!"
      },
      "noResults": {
        "title": "No results.",
        "tryDifferentSearch": "Try searching for a different term, or use the advanced search to change search filters."
      },
      "resultsTable": {
        "actionInProgress": "Action In Progress",
        "allRows": "{count} (All)",
        "ariaLabel": "Search results",
        "select": "Select",
        "selectAll": "Select all",
        "selection": {
          "all": "All",
          "current": "Current",
          "inTrash": "In Trash",
          "invert": "Invert",
          "mine": "Mine",
          "none": "None",
          "notMine": "Not Mine"
        }
      },
      "savedList": {
        "deleteAria": "delete saved item",
        "deleteBasket": "Delete Basket",
        "deleteSavedSearch": "Delete Saved Search",
        "editAria": "edit saved item",
        "editName": "Edit name",
        "noBaskets": "There are no Baskets yet. To create one: select some results and then 'Add to Basket'.",
        "noSavedSearches": "There are no Saved Searches yet."
      }
    },
    "subsample": {
      "batch": {
        "imageAlt": "What the {count} subsamples look like",
        "itemsTableLabel": "Subsamples being edited",
        "largeImageWarning": "Please note, on slower network connections uploading large images may trigger an error.",
        "quantityMixedUnitsWarning": "Quantity cannot be edited as the subsamples use a variety of different units.",
        "title": "Batch editing {count} subsamples"
      },
      "details": {
        "ariaLabel": "Subsample details",
        "imageAlt": "What the subsample, {name}, looks like",
        "none": "No subsamples"
      }
    },
    "template": {
      "summary": {
        "loading": "Loading",
        "noTemplate": "No Template"
      },
      "updateSamplesConfirm": {
        "body": "All of your samples created from this template will be updated to pick up the structural changes that have been made to the template since the sample was created or last updated, such as the addition, deletion and reordering of fields, and the change to available options in choice and radio fields. <strong>This action cannot be undone.</strong>",
        "confirmButton": "Update all",
        "helpTitle": "Info on updating samples to latest template version.",
        "title": "Update all samples to latest template version?"
      }
    },
    "tinyMceIdentifiers": {
      "dialogTitle": "Insert Barcodes Table",
      "insertBarcodeTable": "Insert Barcode Table",
      "instructions": "Select from newly registered IGSN IDs or those already with linked items, and insert a table into your document, each with a QR code.",
      "pageTitle": "Inventory Identifiers"
    }
  },
  "public": {
    "footer": {
      "contactInfo": "If you wish to obtain more information about this item, please contact the research data management department at {institution}.",
      "generatedBy": "This page was generated by {institution} using RSpace Public Pages."
    },
    "geolocation": {
      "boxHeading": "Box",
      "description": "Description",
      "eastboundLongitude": "Eastbound Longitude",
      "inPolygonPointHeading": "In Polygon Point",
      "latitude": "Latitude",
      "longitude": "Longitude",
      "northboundLatitude": "Northbound Latitude",
      "placeHeading": "Place",
      "pointHeading": "Point",
      "pointLatitude": "Point {index} Latitude",
      "pointLongitude": "Point {index} Longitude",
      "polygonHeading": "Polygon",
      "southboundLatitude": "Southbound Latitude",
      "westboundLongitude": "Westbound Longitude"
    },
    "headings": {
      "alternateIdentifiers": "Alternate Identifiers",
      "customFields": "Custom Fields",
      "dates": "Dates",
      "descriptions": "Descriptions",
      "extraFields": "Extra Fields",
      "general": "General",
      "geolocations": "Geolocations",
      "inventory": "Inventory",
      "optionalFields": "Optional Fields",
      "otherInformation": "Other Information",
      "rspacePublicPages": "RSpace Public Pages",
      "subjects": "Subjects"
    },
    "images": {
      "igsnLogoAlt": "IGSN Logo",
      "institutionLogoAlt": "Institution Logo"
    },
    "labels": {
      "creator": "Creator:",
      "creatorAffiliation": "Creator Affiliation:",
      "creatorAffiliationIdentifier": "Creator Affiliation Identifier:",
      "igsnId": "IGSN ID:",
      "name": "Name:",
      "organisation": "Organisation:",
      "publicationYear": "Publication Year:",
      "resourceType": "Resource Type:",
      "urlAvailableAfterPublishing": "URL available after publishing"
    },
    "links": {
      "doiAddressTitle": "DOI - address",
      "igsnHomepageTitle": "IGSN Homepage",
      "itemLandingPageTitle": "Item landing page"
    },
    "table": {
      "name": "Name",
      "value": "Value"
    },
    "values": {
      "none": "None"
    }
  },
  "system": {
    "errors": {
      "networkProblem": "There is a problem, please try again later"
    },
    "ror": {
      "curationRequestLink": "curation request form.",
      "heading": "Research Organization Registry (ROR) Integration",
      "institutionalIdHeading": "Institutional ROR ID",
      "introPrefix": "By associating a",
      "introSuffix": "with your RSpace instance, you ensure the research outputs produced in RSpace are connected with your research organisation. All research outputs with a DOI will automatically include the ROR ID in their affiliation metadata.",
      "invalidFormatHelp": "Please ensure the ROR ID is one of the following formats:",
      "linkButton": "Link",
      "linkHelpAction": "Link",
      "linkHelpPrefix": "ROR ID found. Click",
      "linkHelpSuffix": "to associate with this RSpace Instance.",
      "registryLink": "ROR registry",
      "rorIdLink": "ROR ID",
      "searchHelpMiddle": "to ensure you are adding the correct ROR ID. If your institution does not have a ROR ID, you can submit a",
      "searchHelpPrefix": "You can search the",
      "searchTooltip": "Search Registry",
      "statusLabel": "Status:",
      "unlinkButton": "UnLink",
      "unlinkHelpAction": "UNLINK",
      "unlinkHelpPrefix": "A ROR ID is linked to this RSpace Instance. Click on",
      "unlinkHelpSuffix": "to remove the association. Future published or updated DOIs will not include the ROR ID."
    }
  },
  "workspace": {
    "export": {
      "dialog": {
        "defaultExportName": {
          "exportData": "Export Data",
          "groupAllWork": "{groupName} - all work",
          "userAllWork": "{username} - all work"
        },
        "panes": {
          "export": "Export",
          "filestoreExportConfiguration": "Filestore Links Export Configuration",
          "raid": "RAiD",
          "setupRepository": "Setup Repository"
        }
      },
      "fileStore": {
        "filters": {
          "changeButton": "Change file filtering options",
          "dialogTitle": "Filtering options for filestore files",
          "excludeLabel": "File types to exclude (comma-separated list)",
          "heading": "File filters",
          "sizeLimitLabel": "Individual file size limit (MB)",
          "summary": "Filestore files larger than <strong>{sizeMB} MB</strong> will not be included in the export. All types of filestore files will be included.",
          "summaryWithExclusions": "Filestore files larger than <strong>{sizeMB} MB</strong> will not be included in the export. All types of filestore files will be included, apart from the following: <strong>{extensions}</strong>."
        },
        "foundLinks": {
          "columns": {
            "linkType": "Link type",
            "notes": "Notes",
            "path": "Full path on the File System"
          },
          "heading": "Filestore links found in exported content",
          "showButton": "Show found filestore links",
          "summary": "Exported content contains {filesCount} filestore link from {fileSystemsCount} File System."
        },
        "login": {
          "allLoggedIn": "You are logged into all File Systems referenced by filestore links.",
          "authProblem": "Authentication problem, check your username and password or contact your System Admin",
          "checkButton": "Check File Systems login details",
          "columns": {
            "loggedInAs": "Logged in as",
            "name": "File System Name"
          },
          "dialogTitle": "File Systems login status",
          "heading": "File Systems that require login",
          "loggedInToast": "Logged in as {userName}",
          "loginButton": "Login to remaining File Systems",
          "notAllLoggedIn": "You are not logged into all File Systems referenced by filestore links. Please login to remaining File Systems or some linked files may be omitted during the export.",
          "notLoggedIn": "Not logged in",
          "passwordBlank": "Password cannot be blank",
          "passwordLabel": "Password",
          "submitButton": "Login",
          "usernameBlank": "Username cannot be blank",
          "usernameLabel": "Username"
        },
        "noLinks": {
          "checkSelection": "If that's unexpected, you should check your export selection.",
          "heading": "No filestore links found in exported content.",
          "proceed": "Otherwise you can proceed with the export."
        },
        "scan": {
          "checkResults": "Please check the scan results for details.",
          "columns": {
            "path": "Full path on the File System",
            "reason": "Reason",
            "size": "Size",
            "type": "Type"
          },
          "dialogTitle": "Availability scan results",
          "filesIncluded": "Export will include <strong>{count} filestore file(s)</strong> of total size <strong>{size}</strong>.",
          "filesSkipped": "<strong>{count} file(s) or folder(s) will be skipped</strong>.",
          "heading": "Link availability scan",
          "includedHeading": "Included files from {name}",
          "noFilesIncluded": "Export <strong>will not include any filestore files</strong>.",
          "runHint": "Before continuing please run the filestore links availability scan, which will report on any unaccessible or filtered links.",
          "scanButton": "Scan filestore links",
          "showLastButton": "Show last scan results",
          "skippedHeading": "Skipped files from {name}"
        },
        "validation": {
          "exceedsDiskSpace": "The size of filestore files to be included in export ({size}) exceeds disk space currently available on RSpace server. Use file filters to exclude some files, or contact your System Admin.",
          "exceedsGlobalLimit": "The size of filestore files to be included in export ({size}) exceeds the global limit set for size of RSpace archive file. Use file filters to exclude some files, or ask your System Admin to raise the limit on archive size.",
          "loggedOut": "You are not logged into all required File Systems and some filestore links won't be exported. Do you want to proceed without logging in?",
          "proceedButton": "Yes, proceed",
          "scanNotPerformed": "You have not performed links availability scan. We strongly recommend running it, as it will report any potential problems with accessing filestore link. Do you want to proceed without running the scan?"
        }
      },
      "format": {
        "chooser": {
          "additionalDestinations": "Choose additional destinations",
          "exportToRepository": "Export to a repository",
          "filestoresSection": "Filestores",
          "formats": {
            "docAvailable": "MS Word version of your RSpace documents will be placed in the 'Exports' area of the Gallery.",
            "docHeading": ".DOC file",
            "elnExplanation": "An XML bundle with an RO-Crate metadata file, zipped into a .eln archive.",
            "elnHeading": "RO-Crate",
            "htmlExplanation": "Exported data, notebooks and attached files can be accessed offline with a browser.",
            "htmlHeading": ".ZIP bundle containing .HTML files",
            "pdfAvailable": "A read-only version of your RSpace documents will be placed in the 'Exports' area of the Gallery",
            "pdfHeading": "PDF file",
            "pdfUnavailable": "All selected items are attachments — there are no RSpace documents to export.",
            "xmlExplanation": "Exported data is machine readable. Good for archiving, or transferring data from one RSpace server or user to another.",
            "xmlHeading": ".ZIP bundle containing .XML files"
          },
          "heading": "Choose an appropriate format for your export",
          "includeAllVersions": "Check to include all previous versions of your documents, or leave unchecked for only current version",
          "includeFilestoreLinks": "Include filestore links",
          "loading": "Loading",
          "noRepoSetup": "You have not setup a repository, to do so please activate them within Apps",
          "repoFetchError": "Export to repository is not available because there was an error fetching repository configurations.",
          "revisionsSection": "Revisions",
          "selectAria": "Select Export",
          "wordErrors": {
            "allMedia": "All selected items are attachments — there are no RSpace documents to export.",
            "folder": "Word export is only available for a single document, and you've selected a folder.",
            "multiple": "Word export is only available for a single document, and you have selected more than one.",
            "notebook": "Word export is only available for a single document or notebook entry, and you've selected a Notebook."
          }
        },
        "htmlXml": {
          "depthInfinity": "Include linked documents to depth infinity",
          "depthLevel": "Include linked documents to depth {level}",
          "depthNone": "Don't include linked documents",
          "descriptionLabel": "Export Description (optional)",
          "foldersNote": "Linked folders and notebooks are never included",
          "includeLinksLabel": "Should linked RSpace documents be included in export?"
        },
        "pdf": {
          "checkboxes": {
            "annotations": "Include image annotations",
            "comments": "Include comments",
            "footerEndOnly": "Insert date footer at file end only",
            "lastModified": "Include last modified dates for fields",
            "provenance": "Include provenance information",
            "restartPageNumbers": "Restart page numbering for each document"
          },
          "dateFooterLabel": "Date on page footer",
          "dateType": {
            "created": "Created",
            "exported": "Exported",
            "lastModified": "Last modified date"
          },
          "nameHelper": "Name your file",
          "nameLabel": "File name *",
          "pageFormatLabel": "Page format: ",
          "pageSize": {
            "a4": "A4",
            "letter": "Letter"
          },
          "setDefault": "Set {pageSize} as default"
        },
        "word": {
          "nameLabel": "Name your file",
          "pageFormatLabel": "Page format: ",
          "pageSize": {
            "a4": "A4",
            "letter": "Letter"
          },
          "setDefault": "Set {pageSize} as default."
        }
      },
      "raid": {
        "eligible": {
          "instructions": "By enabling reporting to RAID below, the DOI of your repository export will be automatically added to your RAiD record. Otherwise, click Next to continue without reporting to RAiD.",
          "projectGroupLine": "The content you're about to export is part of the project group <strong>{name}</strong> which is associated with the following RAiD identifier:",
          "raidDetails": "<strong>{title}</strong> ({identifier}).",
          "reportLabel": "Report to RAiD",
          "title": "Report to RAiD"
        },
        "error": {
          "message": "An error occurred while determining RAiD export eligibility: {message}",
          "nextHint": "Please press Next to continue without reporting to RAiD.",
          "title": "Error"
        },
        "ineligible": {
          "missingGroups": "You do not have access to the following groups, therefore RSpace is unable to determine whether you have the rights to export the items to RAiD: {groupIds}. For more information, please contact the owner of the item, or press Next to continue without reporting to RAiD.",
          "multipleRaids": "Multiple project groups ({groups}) associated with the shared items have RAiD associations, which is not supported. Please narrow your selection, or press Next to continue without reporting to RAiD.",
          "noProjectGroups": "No project groups are associated with all shared items selected. Please press Next to continue without reporting to RAiD.",
          "noRaidAssociation": "None of the project groups ({groups}) associated with the shared items have a RAiD association. Please press Next to continue without reporting to RAiD.",
          "title": "Cannot report to RAiD",
          "unknown": "An unknown error occurred while determining RAiD export eligibility. Please press Next to continue without reporting to RAiD."
        }
      },
      "repositories": {
        "choiceAriaLabel": "Repository choice",
        "choiceLabel": "Please choose one of your configured repositories to submit your export to:",
        "common": {
          "descriptionLabel": "Description *",
          "titleLabel": "Title *"
        },
        "dataverse": {
          "descriptionHelper": "Please add a relevant description for your export",
          "licenseHelper": "Please select your license",
          "licenseLabel": "License *",
          "metadataLanguageHelper": "Please select your metadata language (only if target Dataverse supports it)",
          "metadataLanguageLabel": "Metadata language",
          "subjectHelper": "Please select your subject",
          "subjectLabel": "Subject *",
          "titleHelper": "Please choose a title, >3 symbols"
        },
        "dmp": {
          "associateLabel": "Associate export with a Data Management Plans (DMPs)",
          "zenodoLimit": "Only one DMP can be associated with an export to Zenodo."
        },
        "dryad": {
          "abstractHelper": "Please add a relevant abstract for your export",
          "abstractLabel": "Add an abstract *",
          "grantingOrgHelper": "Enter 3 of more characters to filter list",
          "grantingOrgLabel": "Granting Organization *",
          "licenseHelper": "Please select your license",
          "licenseLabel": "License *",
          "researchDomainHelper": "Please select your research domain",
          "researchDomainLabel": "Research Domain *",
          "titleHelper": "Please choose a title, >3 symbols"
        },
        "figshare": {
          "descriptionHelper": "Please add a relevant description for your export",
          "draft": "Draft",
          "licenseHelper": "Please select your license",
          "licenseLabel": "License *",
          "publish": "Publish",
          "publishingStatus": "Publishing status",
          "subjectHelper": "Please select your subject",
          "subjectLabel": "Subject *",
          "titleHelper": "Please choose a title, >3 symbols"
        },
        "tags": {
          "clearButton": "Clear Tags",
          "helperText": "Add tags from controlled vocabularies to this export. The term's value and URI will be included in the deposit's metadata. For more info see <a>Tagging Documents and using Controlled Vocabularies</a>.",
          "label": "Tags and Controlled Vocabulary Terms"
        },
        "user": {
          "addDialogTitle": "Add new person",
          "addTooltip": "Add author/contact",
          "author": "Author",
          "contact": "Contact",
          "emailLabel": "Email *",
          "nameLabel": "Name *",
          "peopleHelper": "Add author(s) AND contact(s) to your repository export.",
          "peopleLabel": "People",
          "typeLabel": "Type *"
        }
      }
    },
    "toolbar": {
      "advancedSearch": {
        "addCondition": "Add new condition",
        "cardSubheader": "Advanced search",
        "dateFrom": "From",
        "datePlaceholderFrom": "the beginning",
        "datePlaceholderTo": "now",
        "dateTo": "To",
        "recordsConditionInfo": "At least one of the 'Within records' conditions will always be satisfied.",
        "removeCondition": "Remove condition",
        "reset": "Reset",
        "satisfyAll": "Satisfy all conditions",
        "satisfyOne": "Satisfy at least one condition",
        "searchTypes": {
          "attachment": "Attachment",
          "created": "Creation date",
          "form": "Form",
          "fullText": "Text",
          "lastModified": "Last modified",
          "name": "Name",
          "owner": "Owner(s)",
          "records": "Within records",
          "tag": "Tag(s)",
          "template": "Template"
        },
        "validation": {
          "includeAtLeastOne": "Include at least one {filter}",
          "termTooShort": "The term should be at least 2 symbols"
        }
      },
      "chemicalSearch": {
        "back": "Back",
        "chemicalPreviewAlt": "Chemical Preview",
        "close": "Close",
        "columnHeaders": {
          "lastModified": "Last Modified",
          "name": "Name",
          "owner": "Owner",
          "preview": "Preview"
        },
        "dialogTitle": "Chemical Search",
        "drawInstruction": "Draw a single molecule below to search",
        "errorFetching": "Error fetching search results: {message}",
        "ketcherTitle": "Chemistry Search",
        "loading": "Loading...",
        "noResults": "No Search Results",
        "searchType": "Search Type",
        "searchTypeExact": "Exact",
        "searchTypeSubstructure": "Substructure",
        "validationMultipleMolecules": "Chemical search currently supports a single molecule. Please remove extra molecules from the canvas.",
        "validationNoMolecule": "Please draw, paste, or open a molecule to start your search"
      },
      "compareDialog": {
        "columnHeaders": {
          "createdDate": "Created Date",
          "globalId": "Global ID",
          "modifiedDate": "Modified Date",
          "name": "Name",
          "owner": "Owner",
          "signed": "Signed",
          "tags": "Tags",
          "unsigned": "Unsigned"
        },
        "description": "Select the documents you want to combine into a single CSV file. Documents with identical structures will be automatically aligned, including form data and content. If documents have different structures, additional columns will be created to accommodate all information.",
        "exportRows": "Export {selection, select, selected {selected} other {all}} rows to CSV",
        "loadingDocuments": "Reading documents…",
        "readError": "Could not read all of the documents",
        "title": "Export Documents to CSV",
        "unknownError": "Unknown reason"
      },
      "filePicker": {
        "clickToSelect": "Click on the folder icon to select records.",
        "dialogTitle": "{count, plural, one {# record selected} other {# records selected}}",
        "openPicker": "Pick files"
      },
      "newFolder": {
        "creating": "Creating a new folder...",
        "nameAria": "Folder name",
        "navigateAfterCreate": "Navigate to the created folder",
        "placeholder": "Enter a name, /or/a/path to create multiple folders",
        "title": "Create a folder",
        "validation": {
          "nameRequired": "Please enter a name"
        }
      },
      "newNotebook": {
        "name": "New notebook name",
        "title": "Create a notebook",
        "validation": {
          "nameRequired": "Please enter a name - excluding '/' characters."
        }
      },
      "rename": {
        "emptyName": "Empty name is not permitted.",
        "error": "An error occurred while renaming the document.",
        "name": "Name",
        "success": "Successfully renamed document.",
        "title": "Rename"
      },
      "searchbox": {
        "placeholder": "Search term"
      },
      "simpleSearch": {
        "advancedSearch": "Advanced search",
        "filterTypes": {
          "attachment": "Attachment",
          "chemical": "Chemical",
          "created": "Creation date",
          "form": "Form",
          "fullText": "Text",
          "global": "All",
          "lastModified": "Last modified",
          "name": "Name",
          "owner": "Owner(s)",
          "tag": "Tag(s)",
          "template": "Template"
        },
        "filters": "Filters",
        "scopeDialog": {
          "instructions": "Click \"Within selected\" if you wish to search within the specified records, or \"Search everywhere\" otherwise.",
          "searchEverywhere": "Search everywhere",
          "selectedRecords": "You have selected the records listed below.",
          "title": "Scope search within records",
          "withinSelected": "Within selected"
        },
        "searchPlaceholder": "Search"
      },
      "tagSelect": {
        "placeholder": "Select tag(s)"
      },
      "tags": {
        "description": "You can tag Documents, Notebooks, and Folders to categorise work and make it more searchable. If you've selected multiple items, only shared tags are shown. <a>Read more about creating, importing, and using Tags here.</a>",
        "getTagsError": "Could not get tags.",
        "invalidTags": "Some tags are invalid",
        "multipleErrors": "There are multiple errors.",
        "ontologyError": "Could not determine if ontologies are enforced or not.",
        "saveError": "Could not save tags.",
        "saveSuccess": "Successfully saved tags.",
        "title": "Tagging {count, plural, one {# item} other {# items}}",
        "unknownError": "An unknown error occurred."
      },
      "userSelect": {
        "placeholder": "Select owner(s)"
      },
      "workspaceToolbar": {
        "calendarEntry": "Create a calendar entry",
        "favorites": "Favorites",
        "folderView": "Folder view",
        "labgroupRecords": "Labgroup records",
        "listView": "List view",
        "ontologyFiles": "Ontology files",
        "sharedWithMe": "Shared with me",
        "templates": "Templates",
        "treeView": "Tree view",
        "viewAll": "View all",
        "viewMode": "View mode"
      }
    }
  }
}
