package com.researchspace.model.permissions;

import static org.apache.commons.lang3.RandomStringUtils.random;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

import org.apache.shiro.crypto.cipher.AesCipherService;
import org.apache.shiro.lang.codec.Base64;
import org.junit.jupiter.api.Test;

public class SymmetricTextEncryptorTest {

  // this is to ensure backwards compatibility with existing encrypted secrets, that we
  // encode/decode
  // in the same way over time.
  final String secretMessage_Shiro1_5_0 = "aaaaaaaaaaaaaaaabbbbb";

  // A fixed AES-128 key (the 16 bytes 0x00..0x0f) and the ciphertext produced for
  // secretMessage_Shiro1_5_0 under AES/ECB/PKCS5(PKCS7) padding. The ciphertext was generated by an
  // independent implementation (openssl: `openssl enc -aes-128-ecb -K
  // 000102030405060708090a0b0c0d0e0f`),
  // not by this class, so decrypting it here proves that our Shiro 2.1 crypto path still reads the
  // exact
  // wire format that Shiro 1.5.x persisted. This guards the OAuth/integration tokens stored
  // encrypted in
  // the DB (see UserConnectionDaoHibernate) against a silent mode/padding/default change on a Shiro
  // upgrade.
  final String fixedKey_Base64 = "AAECAwQFBgcICQoLDA0ODw==";
  final String fixedCiphertext_AesEcbPkcs5_Base64 = "uED7oMVTS3wTO+z7G2dN8zPRzfxg+Qi5lQ++GdyS5fM=";

  @Test
  public void encryptDecryptRoundTrip() {
    String keyString = createNewEncryptionKey();

    TextEncryptor encryptor = new SymmetricTextEncryptor(keyString);

    String encrypted = encryptor.encrypt(secretMessage_Shiro1_5_0);
    assertEquals(secretMessage_Shiro1_5_0, encryptor.decrypt(encrypted));

    String encrypted2 = encryptor.encrypt(secretMessage_Shiro1_5_0);
    encrypted = encryptor.encrypt(secretMessage_Shiro1_5_0);
    assertEquals(secretMessage_Shiro1_5_0, encryptor.decrypt(encrypted2));
  }

  // Backward-compatibility check that an AES/ECB/PKCS5 ciphertext produced outside this class, with
  // a fixed key, still decrypts. Replaces the previous self-comparing no-op assertion
  // (assertEquals(expected, expected)) that never exercised a fixed key.
  @Test
  public void decryptsFixedCiphertextFromEarlierShiroVersion() {
    TextEncryptor encryptor = new SymmetricTextEncryptor(fixedKey_Base64);
    assertEquals(secretMessage_Shiro1_5_0, encryptor.decrypt(fixedCiphertext_AesEcbPkcs5_Base64));
  }

  @Test
  public void createFromAnyString() {
    TextEncryptor encryptor = SymmetricTextEncryptor.createFromAnyString("abcde");
    String encrypted = encryptor.encrypt(secretMessage_Shiro1_5_0);
    assertEquals(secretMessage_Shiro1_5_0, encryptor.decrypt(encrypted));
  }

  @Test
  public void createFromAnyStringConstraints() {

    assertThrows(
        IllegalArgumentException.class, () -> SymmetricTextEncryptor.createFromAnyString(""));
    assertThrows(
        IllegalArgumentException.class, () -> SymmetricTextEncryptor.createFromAnyString(null));
    assertThrows(
        IllegalArgumentException.class,
        () -> SymmetricTextEncryptor.createFromAnyString(random(256)));
  }

  private String createNewEncryptionKey() {
    return Base64.encodeToString(new AesCipherService().generateNewKey().getEncoded());
  }
}
