package com.researchspace.dao.query;

import com.blazebit.persistence.CommonQueryBuilder;
import com.researchspace.model.collection.CollectionDescription;
import com.researchspace.model.collection.CollectionDescription.Operator;
import com.researchspace.model.collection.CollectionQueryException;
import com.researchspace.model.collection.FilterExpression;
import com.researchspace.model.collection.FilterSelector;
import com.researchspace.model.collection.FilterSelector.RelationshipComponent;
import com.researchspace.model.collection.ResourceReference;
import com.researchspace.model.collection.SplitReferenceBinding;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/** Compiles a typed collection filter into a parameterized Blaze-Persistence predicate. */
public final class RsqlCollectionQuery {

  /** Maximum number of SQL LIKE/NOT LIKE predicates generated by one collection filter. */
  public static final int MAX_LIKE_PREDICATES = 50;

  private final CollectionDescription<?> description;
  private final String alias;

  public RsqlCollectionQuery(CollectionDescription<?> description, String alias) {
    this.description = description;
    this.alias = alias;
  }

  public Predicate translate(FilterExpression filter) {
    if (filter == null) {
      return null;
    }
    State state = new State();
    return new Predicate(compile(filter, state), state.parameters);
  }

  public record Predicate(String expression, Map<String, Object> parameters) {

    public Predicate {
      parameters = Map.copyOf(parameters);
    }

    public void apply(CommonQueryBuilder<?> query) {
      parameters.forEach(query::setParameter);
    }
  }

  private String compile(FilterExpression filter, State state) {
    if (filter instanceof FilterExpression.Comparison comparison) {
      return compileComparison(comparison, state);
    }
    if (filter instanceof FilterExpression.And and) {
      return compileLogical(and.children(), " AND ", state);
    }
    if (filter instanceof FilterExpression.Or or) {
      return compileLogical(or.children(), " OR ", state);
    }
    throw new IllegalStateException("Unsupported filter expression " + filter.getClass());
  }

  private String compileLogical(List<FilterExpression> children, String separator, State state) {
    return children.stream()
        .map(child -> compile(child, state))
        .reduce((left, right) -> left + separator + right)
        .map(expression -> "(" + expression + ")")
        .orElseThrow(() -> new CollectionQueryException(CollectionQueryException.Reason.SYNTAX));
  }

  private String compileComparison(FilterExpression.Comparison comparison, State state) {
    FilterSelector<?> selector = description.requireFilterSelector(comparison.field());
    Operator operator = comparison.operator();
    if (!selector.operators().contains(operator)) {
      throw new CollectionQueryException(CollectionQueryException.Reason.OPERATOR);
    }
    if (selector instanceof FilterSelector.RelationshipPart<?> relationship) {
      return compileRelationship(comparison, relationship, state);
    }
    FilterSelector.Property<?> property = (FilterSelector.Property<?>) selector;
    String path = alias + "." + property.property();
    if (operator == Operator.EXISTS) {
      return path + (Boolean.TRUE.equals(comparison.values().get(0)) ? " IS NOT NULL" : " IS NULL");
    }
    if (operator == Operator.IN || operator == Operator.NOT_IN) {
      String parameter = state.add(comparison.values());
      return path + (operator == Operator.IN ? " IN :" : " NOT IN :") + parameter;
    }

    Object value = comparison.values().get(0);
    if (operator == Operator.CONTAINS) {
      state.recordLikePredicate();
      return like(path, state.add("%" + escapeLike(String.valueOf(value)) + "%"), false);
    }
    if (operator == Operator.LIKE) {
      return wordsLike(path, String.valueOf(value), state);
    }
    if (comparison.wildcard()) {
      state.recordLikePredicate();
      return like(
          path, state.add(wildcardPattern(String.valueOf(value))), operator == Operator.NOT_EQUAL);
    }
    return path + " " + symbol(operator) + " :" + state.add(value);
  }

  private String compileRelationship(
      FilterExpression.Comparison comparison,
      FilterSelector.RelationshipPart<?> selector,
      State state) {
    SplitReferenceBinding<?, ?, ?> binding = selector.relationship().binding();
    String kindPath = alias + "." + binding.kindProperty();
    String idPath = alias + "." + binding.idProperty();
    if (selector.part() == RelationshipComponent.ROOT) {
      return compileReference(comparison, kindPath, idPath, state);
    }
    String path = selector.part() == RelationshipComponent.KIND ? kindPath : idPath;
    Operator operator = comparison.operator();
    if (operator == Operator.EXISTS) {
      return path + (Boolean.TRUE.equals(comparison.values().get(0)) ? " IS NOT NULL" : " IS NULL");
    }
    if (operator == Operator.IN || operator == Operator.NOT_IN) {
      String parameter = state.add(comparison.values());
      return path + (operator == Operator.IN ? " IN :" : " NOT IN :") + parameter;
    }
    return path + " " + symbol(operator) + " :" + state.add(comparison.values().get(0));
  }

  private String compileReference(
      FilterExpression.Comparison comparison, String kindPath, String idPath, State state) {
    Operator operator = comparison.operator();
    if (operator == Operator.EXISTS) {
      boolean exists = Boolean.TRUE.equals(comparison.values().get(0));
      return exists
          ? "(" + kindPath + " IS NOT NULL AND " + idPath + " IS NOT NULL)"
          : "(" + kindPath + " IS NULL OR " + idPath + " IS NULL)";
    }
    String pairs =
        comparison.values().stream()
            .map(value -> referencePair(value, kindPath, idPath, state))
            .reduce((left, right) -> left + " OR " + right)
            .map(expression -> "(" + expression + ")")
            .orElseThrow(() -> new CollectionQueryException(CollectionQueryException.Reason.VALUE));
    return switch (operator) {
      case EQUAL, IN -> pairs;
      case NOT_EQUAL, NOT_IN -> "NOT " + pairs;
      default -> throw new CollectionQueryException(CollectionQueryException.Reason.OPERATOR);
    };
  }

  private static String referencePair(Object value, String kindPath, String idPath, State state) {
    if (!(value instanceof ResourceReference<?, ?> reference)) {
      throw new CollectionQueryException(CollectionQueryException.Reason.VALUE);
    }
    return "("
        + kindPath
        + " = :"
        + state.add(reference.kind())
        + " AND "
        + idPath
        + " = :"
        + state.add(reference.id())
        + ")";
  }

  private static String symbol(Operator operator) {
    return switch (operator) {
      case EQUAL -> "=";
      case NOT_EQUAL -> "<>";
      case GREATER_THAN -> ">";
      case GREATER_THAN_OR_EQUAL -> ">=";
      case LESS_THAN -> "<";
      case LESS_THAN_OR_EQUAL -> "<=";
      default -> throw new CollectionQueryException(CollectionQueryException.Reason.OPERATOR);
    };
  }

  private static String wordsLike(String path, String value, State state) {
    return Arrays.stream(value.trim().split("\\s+"))
        .map(
            word -> {
              state.recordLikePredicate();
              return like(path, state.add("%" + escapeLike(word) + "%"), false);
            })
        .reduce((left, right) -> left + " AND " + right)
        .map(expression -> "(" + expression + ")")
        .orElseThrow(() -> new CollectionQueryException(CollectionQueryException.Reason.VALUE));
  }

  private static String like(String path, String parameter, boolean negated) {
    return "LOWER("
        + path
        + ") "
        + (negated ? "NOT LIKE" : "LIKE")
        + " LOWER(:"
        + parameter
        + ") ESCAPE '!'";
  }

  // ponytail: '*' is always a wildcard here, so a value containing a literal '*' can never be
  // matched by EQUAL/NOT_EQUAL. Add a '\*' escape convention in RsqlFilterParser if that's needed.
  private static String wildcardPattern(String value) {
    return escapeLike(value).replace('*', '%');
  }

  private static String escapeLike(String value) {
    return value.replace("!", "!!").replace("%", "!%").replace("_", "!_");
  }

  private static final class State {

    private int sequence;
    private int likePredicates;
    private final Map<String, Object> parameters = new LinkedHashMap<>();

    private String add(Object value) {
      String name = "rsql" + sequence++;
      parameters.put(name, value);
      return name;
    }

    private void recordLikePredicate() {
      if (++likePredicates > MAX_LIKE_PREDICATES) {
        throw new CollectionQueryException(CollectionQueryException.Reason.COMPLEXITY);
      }
    }
  }
}
