package com.researchspace.dao.query;

import com.blazebit.persistence.CommonQueryBuilder;
import com.researchspace.model.collection.AccessResult;
import com.researchspace.model.collection.CollectionDescription;
import com.researchspace.model.collection.CollectionDescription.Operator;
import com.researchspace.model.collection.CollectionQueryException;
import com.researchspace.model.collection.FilterExpression;
import com.researchspace.model.collection.FilterSelector;
import com.researchspace.model.collection.FilterSelector.RelationshipComponent;
import com.researchspace.model.collection.RelationshipReadAccess;
import com.researchspace.model.collection.RelationshipTarget;
import com.researchspace.model.collection.ResourceReference;
import com.researchspace.model.collection.ResourceRegistry.RelationshipQueryPath;
import com.researchspace.model.collection.ResourceRegistry.TargetQueryField;
import com.researchspace.model.collection.SplitReferenceBinding;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/** Compiles a typed collection filter into a parameterized Blaze-Persistence predicate. */
public final class RsqlCollectionQuery {

  /** Maximum number of SQL LIKE/NOT LIKE predicates generated by one collection filter. */
  public static final int MAX_LIKE_PREDICATES = 50;

  private final CollectionDescription<?> description;
  private final String alias;
  private final String parameterPrefix;

  public RsqlCollectionQuery(CollectionDescription<?> description, String alias) {
    this(description, alias, "rsql");
  }

  /**
   * Names generated parameters with {@code parameterPrefix}.
   *
   * <p>Two predicates compiled separately are applied to the same query builder, so they must not
   * generate the same parameter names. A caller filter and a server-built access constraint are
   * exactly that pair: sharing a prefix makes the second silently overwrite the first, which
   * quietly changes which rows match.
   */
  public RsqlCollectionQuery(
      CollectionDescription<?> description, String alias, String parameterPrefix) {
    this.description = description;
    this.alias = alias;
    if (parameterPrefix == null || parameterPrefix.isBlank()) {
      throw new IllegalArgumentException("Parameter prefix must not be blank");
    }
    this.parameterPrefix = parameterPrefix;
  }

  public Predicate translate(FilterExpression filter) {
    return translate(filter, RelationshipReadAccess.none());
  }

  public Predicate translate(FilterExpression filter, RelationshipReadAccess targets) {
    return translate(filter, targets, true);
  }

  /** Compiles a server-built constraint without charging it to the caller complexity budget. */
  public Predicate translateTrusted(FilterExpression filter) {
    return translate(filter, RelationshipReadAccess.none(), false);
  }

  /** Compiles a relationship-aware server constraint without charging caller complexity limits. */
  public Predicate translateTrusted(FilterExpression filter, RelationshipReadAccess targets) {
    return translate(filter, targets, false);
  }

  private Predicate translate(
      FilterExpression filter, RelationshipReadAccess targets, boolean enforceComplexityLimit) {
    if (filter == null) {
      return null;
    }
    State state = new State(parameterPrefix, targets, enforceComplexityLimit);
    return new Predicate(compile(filter, state), state.parameters, state.subqueries);
  }

  /**
   * One correlated subquery, kept out of the expression text.
   *
   * <p>Blaze's expression parser accepts no subquery, so a subquery must be built through {@code
   * whereExpressionSubqueries} and referenced from the expression by name.
   */
  public record Subquery(Class<?> entityType, String alias, String whereExpression) {}

  public record Predicate(
      String expression, Map<String, Object> parameters, Map<String, Subquery> subqueries) {

    public Predicate {
      parameters = Map.copyOf(parameters);
      subqueries = Map.copyOf(subqueries);
    }

    public Predicate(String expression, Map<String, Object> parameters) {
      this(expression, parameters, Map.of());
    }

    public void apply(CommonQueryBuilder<?> query) {
      parameters.forEach(query::setParameter);
    }
  }

  private String compile(FilterExpression filter, State state) {
    if (filter instanceof FilterExpression.Comparison comparison) {
      return compileComparison(comparison, state);
    }
    if (filter instanceof FilterExpression.And and) {
      return compileLogical(and.children(), " AND ", state);
    }
    if (filter instanceof FilterExpression.Or or) {
      return compileLogical(or.children(), " OR ", state);
    }
    throw new IllegalStateException("Unsupported filter expression " + filter.getClass());
  }

  private String compileLogical(List<FilterExpression> children, String separator, State state) {
    return children.stream()
        .map(child -> compile(child, state))
        .reduce((left, right) -> left + separator + right)
        .map(expression -> "(" + expression + ")")
        .orElseThrow(() -> new CollectionQueryException(CollectionQueryException.Reason.SYNTAX));
  }

  private String compileComparison(FilterExpression.Comparison comparison, State state) {
    FilterSelector<?> selector = description.findFilterSelector(comparison.field()).orElse(null);
    if (selector == null) {
      return compileRelationshipField(comparison, state);
    }
    Operator operator = comparison.operator();
    if (!selector.operators().contains(operator)) {
      throw new CollectionQueryException(CollectionQueryException.Reason.OPERATOR);
    }
    // Covers every permitted FilterSelector. Java 17 has no pattern switch, so a new selector kind
    // fails here explicitly rather than through a cast that breaks only when a caller filters on
    // it.
    if (selector instanceof FilterSelector.RelationshipPart<?> relationship) {
      return compileRelationship(comparison, relationship, state);
    }
    if (selector instanceof FilterSelector.Property<?> property) {
      return compileProperty(comparison, property, state);
    }
    throw new IllegalStateException("Unsupported filter selector " + selector.getClass());
  }

  private String compileProperty(
      FilterExpression.Comparison comparison, FilterSelector.Property<?> property, State state) {
    Operator operator = comparison.operator();
    String path = alias + "." + property.property();
    if (operator == Operator.EXISTS) {
      return path + (Boolean.TRUE.equals(comparison.values().get(0)) ? " IS NOT NULL" : " IS NULL");
    }
    if (operator == Operator.IN || operator == Operator.NOT_IN) {
      String parameter = state.add(comparison.values());
      return path + (operator == Operator.IN ? " IN :" : " NOT IN :") + parameter;
    }

    Object value = comparison.values().get(0);
    if (operator == Operator.CONTAINS) {
      state.recordLikePredicate();
      return like(path, state.add("%" + escapeLike(String.valueOf(value)) + "%"), false);
    }
    if (operator == Operator.LIKE) {
      return wordsLike(path, String.valueOf(value), state);
    }
    if (comparison.wildcard()) {
      state.recordLikePredicate();
      return like(
          path, state.add(wildcardPattern(String.valueOf(value))), operator == Operator.NOT_EQUAL);
    }
    return path + " " + symbol(operator) + " :" + state.add(value);
  }

  /**
   * Compiles a filter on a field reached through a relationship, such as {@code primary.name}.
   *
   * <p>An {@code EXISTS} subquery rather than a second query in Java, so the page and its total
   * stay in step and no route reads a collection to filter it. One disjunct per target that
   * declares the field, because a polymorphic relationship can point at collections that do not all
   * have it.
   *
   * <p>The subquery repeats the target's own read rule. On the target's normal route the
   * registration and its DAO add that rule. A subquery receives neither. If the subquery omits the
   * rule, a caller can find unreadable records by observing which rows match.
   */
  private String compileRelationshipField(FilterExpression.Comparison comparison, State state) {
    RelationshipQueryPath path =
        state
            .targets
            .findPath(description.resourceName(), comparison.field())
            .orElseThrow(() -> new CollectionQueryException(CollectionQueryException.Reason.FIELD));
    if (!path.filterSelector().operators().contains(comparison.operator())) {
      throw new CollectionQueryException(CollectionQueryException.Reason.OPERATOR);
    }
    List<String> disjuncts = new ArrayList<>();
    for (TargetQueryField target : path.targets()) {
      String disjunct = targetExists(comparison, path, target, state);
      if (disjunct != null) {
        disjuncts.add(disjunct);
      }
    }
    if (disjuncts.isEmpty()) {
      throw new CollectionQueryException(CollectionQueryException.Reason.FIELD);
    }
    return "(" + String.join(" OR ", disjuncts) + ")";
  }

  private String targetExists(
      FilterExpression.Comparison comparison,
      RelationshipQueryPath path,
      TargetQueryField targetField,
      State state) {
    RelationshipTarget<?> target = targetField.target();
    CollectionDescription<?> targetDescription = state.targets.description(target.resourceName());
    if (targetDescription == null) {
      return null;
    }
    AccessResult access = state.targets.result(target.resourceName());
    if (access.isDenied()) {
      // The field exists, so this is a valid query, but no row of this destination is readable.
      return "1 = 0";
    }
    String targetAlias = state.nextTargetAlias();
    // Two prefixes, because the field predicate and the access rule are compiled separately and
    // then merged: one prefix would restart the sequence and overwrite the first set of values.
    RsqlCollectionQuery fieldQuery =
        new RsqlCollectionQuery(targetDescription, targetAlias, targetAlias + "f");
    RsqlCollectionQuery accessQuery =
        new RsqlCollectionQuery(targetDescription, targetAlias, targetAlias + "a");
    List<String> conjuncts =
        correlation(path.relationship(), target, targetDescription, targetAlias, state);
    conjuncts.add(
        state.merge(
            fieldQuery.translate(
                new FilterExpression.Comparison(
                    path.targetField(),
                    comparison.operator(),
                    comparison.values(),
                    comparison.wildcard()))));
    access
        .constraintOrEmpty()
        .ifPresent(
            constraint -> conjuncts.add(state.merge(accessQuery.translateTrusted(constraint))));
    return "EXISTS "
        + state.addSubquery(
            new Subquery(
                targetDescription.entityType(), targetAlias, String.join(" AND ", conjuncts)));
  }

  private List<String> correlation(
      CollectionDescription.Relationship<?> relationship,
      RelationshipTarget<?> target,
      CollectionDescription<?> targetDescription,
      String targetAlias,
      State state) {
    SplitReferenceBinding<?, ?, ?> binding = relationship.binding();
    List<String> conjuncts = new ArrayList<>();
    conjuncts.add(
        targetAlias
            + "."
            + targetDescription.requireField(targetDescription.idField()).property()
            + " = "
            + alias
            + "."
            + binding.idProperty());
    if (binding.hasKindProperty()) {
      conjuncts.add(alias + "." + binding.kindProperty() + " = :" + state.add(target.storedKind()));
    }
    return conjuncts;
  }

  private String compileRelationship(
      FilterExpression.Comparison comparison,
      FilterSelector.RelationshipPart<?> selector,
      State state) {
    String readable = compileReadableRelationship(selector.relationship(), state);
    SplitReferenceBinding<?, ?, ?> binding = selector.relationship().binding();
    String kindPath = alias + "." + binding.kindProperty();
    String idPath = alias + "." + binding.idProperty();
    if (comparison.operator() == Operator.EXISTS) {
      return Boolean.TRUE.equals(comparison.values().get(0)) ? readable : "NOT " + readable;
    }
    String stored;
    if (selector.part() == RelationshipComponent.ROOT) {
      stored = compileReference(comparison, kindPath, idPath, state);
    } else {
      String path = selector.part() == RelationshipComponent.KIND ? kindPath : idPath;
      Operator operator = comparison.operator();
      if (operator == Operator.IN || operator == Operator.NOT_IN) {
        String parameter = state.add(comparison.values());
        stored = path + (operator == Operator.IN ? " IN :" : " NOT IN :") + parameter;
      } else {
        stored = path + " " + symbol(operator) + " :" + state.add(comparison.values().get(0));
      }
    }
    return "(" + readable + " AND " + stored + ")";
  }

  private String compileReadableRelationship(
      CollectionDescription.Relationship<?> relationship, State state) {
    List<String> readableTargets = new ArrayList<>();
    for (RelationshipTarget<?> target : relationship.targets()) {
      CollectionDescription<?> targetDescription = state.targets.description(target.resourceName());
      if (targetDescription == null) {
        continue;
      }
      AccessResult access = state.targets.result(target.resourceName());
      if (access.isDenied()) {
        continue;
      }
      String targetAlias = state.nextTargetAlias();
      List<String> conjuncts =
          correlation(relationship, target, targetDescription, targetAlias, state);
      access
          .constraintOrEmpty()
          .ifPresent(
              constraint -> {
                RsqlCollectionQuery accessQuery =
                    new RsqlCollectionQuery(targetDescription, targetAlias, targetAlias + "a");
                conjuncts.add(state.merge(accessQuery.translateTrusted(constraint)));
              });
      readableTargets.add(
          "EXISTS "
              + state.addSubquery(
                  new Subquery(
                      targetDescription.entityType(),
                      targetAlias,
                      String.join(" AND ", conjuncts))));
    }
    return readableTargets.isEmpty() ? "(1 = 0)" : "(" + String.join(" OR ", readableTargets) + ")";
  }

  private String compileReference(
      FilterExpression.Comparison comparison, String kindPath, String idPath, State state) {
    Operator operator = comparison.operator();
    if (operator == Operator.EXISTS) {
      boolean exists = Boolean.TRUE.equals(comparison.values().get(0));
      return exists
          ? "(" + kindPath + " IS NOT NULL AND " + idPath + " IS NOT NULL)"
          : "(" + kindPath + " IS NULL OR " + idPath + " IS NULL)";
    }
    String pairs =
        comparison.values().stream()
            .map(value -> referencePair(value, kindPath, idPath, state))
            .reduce((left, right) -> left + " OR " + right)
            .map(expression -> "(" + expression + ")")
            .orElseThrow(() -> new CollectionQueryException(CollectionQueryException.Reason.VALUE));
    return switch (operator) {
      case EQUAL, IN -> pairs;
      case NOT_EQUAL, NOT_IN -> "NOT " + pairs;
      default -> throw new CollectionQueryException(CollectionQueryException.Reason.OPERATOR);
    };
  }

  private static String referencePair(Object value, String kindPath, String idPath, State state) {
    if (!(value instanceof ResourceReference<?, ?> reference)) {
      throw new CollectionQueryException(CollectionQueryException.Reason.VALUE);
    }
    return "("
        + kindPath
        + " = :"
        + state.add(reference.kind())
        + " AND "
        + idPath
        + " = :"
        + state.add(reference.id())
        + ")";
  }

  private static String symbol(Operator operator) {
    return switch (operator) {
      case EQUAL -> "=";
      case NOT_EQUAL -> "<>";
      case GREATER_THAN -> ">";
      case GREATER_THAN_OR_EQUAL -> ">=";
      case LESS_THAN -> "<";
      case LESS_THAN_OR_EQUAL -> "<=";
      default -> throw new CollectionQueryException(CollectionQueryException.Reason.OPERATOR);
    };
  }

  private static String wordsLike(String path, String value, State state) {
    return Arrays.stream(value.trim().split("\\s+"))
        .map(
            word -> {
              state.recordLikePredicate();
              return like(path, state.add("%" + escapeLike(word) + "%"), false);
            })
        .reduce((left, right) -> left + " AND " + right)
        .map(expression -> "(" + expression + ")")
        .orElseThrow(() -> new CollectionQueryException(CollectionQueryException.Reason.VALUE));
  }

  private static String like(String path, String parameter, boolean negated) {
    return "LOWER("
        + path
        + ") "
        + (negated ? "NOT LIKE" : "LIKE")
        + " LOWER(:"
        + parameter
        + ") ESCAPE '!'";
  }

  // ponytail: '*' is always a wildcard here, so a value containing a literal '*' can never be
  // matched by EQUAL/NOT_EQUAL. Add a '\*' escape convention in RsqlFilterParser if that's needed.
  private static String wildcardPattern(String value) {
    return escapeLike(value).replace('*', '%');
  }

  private static String escapeLike(String value) {
    return value.replace("!", "!!").replace("%", "!%").replace("_", "!_");
  }

  private static final class State {

    private final String prefix;
    private final RelationshipReadAccess targets;
    private final boolean enforceComplexityLimit;
    private int sequence;
    private int likePredicates;
    private int targetAliases;
    private final Map<String, Object> parameters = new LinkedHashMap<>();
    private final Map<String, Subquery> subqueries = new LinkedHashMap<>();

    private State(String prefix, RelationshipReadAccess targets, boolean enforceComplexityLimit) {
      this.prefix = prefix;
      this.targets = targets;
      this.enforceComplexityLimit = enforceComplexityLimit;
    }

    /** A distinct alias per subquery, so nested targets cannot shadow each other. */
    private String nextTargetAlias() {
      return prefix + "Target" + targetAliases++;
    }

    /** Folds a separately compiled predicate in, keeping its already-distinct parameter names. */
    private String merge(Predicate predicate) {
      parameters.putAll(predicate.parameters());
      subqueries.putAll(predicate.subqueries());
      return predicate.expression();
    }

    /** A placeholder distinct from the subquery's own entity alias, which Blaze also parses. */
    private String addSubquery(Subquery subquery) {
      String name = subquery.alias() + "Sub";
      subqueries.put(name, subquery);
      return name;
    }

    private String add(Object value) {
      String name = prefix + sequence++;
      parameters.put(name, value);
      return name;
    }

    private void recordLikePredicate() {
      if (enforceComplexityLimit && ++likePredicates > MAX_LIKE_PREDICATES) {
        throw new CollectionQueryException(CollectionQueryException.Reason.COMPLEXITY);
      }
    }
  }
}
