package com.researchspace.dao.query;

import com.blazebit.persistence.CommonQueryBuilder;
import com.researchspace.model.collection.CollectionDescription;
import com.researchspace.model.collection.FilterExpression;
import com.researchspace.model.collection.QueryConstraint;
import com.researchspace.model.collection.RelationshipReadAccess;
import com.researchspace.model.collection.RuntimeFieldSelection;
import java.util.Map;

/** Compiles a typed collection filter into a parameterized Blaze-Persistence predicate. */
public final class RsqlCollectionQuery {

  /** Maximum number of SQL LIKE/NOT LIKE predicates generated by one collection filter. */
  public static final int MAX_LIKE_PREDICATES = 50;

  private final CollectionDescription<?> description;
  private final String parameterPrefix;
  private final RsqlRelationshipCompiler relationships;
  private final RsqlExpressionCompiler expressions;

  public RsqlCollectionQuery(CollectionDescription<?> description, String alias) {
    this(description, alias, "rsql");
  }

  /**
   * Names generated parameters with {@code parameterPrefix}.
   *
   * <p>Two predicates compiled separately are applied to the same query builder, so they must not
   * generate the same parameter names. A caller filter and a server-built access constraint are
   * exactly that pair: sharing a prefix makes the second silently overwrite the first, which
   * quietly changes which rows match.
   */
  public RsqlCollectionQuery(
      CollectionDescription<?> description, String alias, String parameterPrefix) {
    this.description = description;
    if (parameterPrefix == null || parameterPrefix.isBlank()) {
      throw new IllegalArgumentException("Parameter prefix must not be blank");
    }
    this.parameterPrefix = parameterPrefix;
    this.relationships = new RsqlRelationshipCompiler(description, alias);
    this.expressions = new RsqlExpressionCompiler(description, alias, relationships);
  }

  public Predicate translate(FilterExpression filter) {
    return translate(filter, RelationshipReadAccess.none());
  }

  public Predicate translate(FilterExpression filter, RelationshipReadAccess targets) {
    return translate(filter, targets, RuntimeFieldSelection.empty(), true);
  }

  public Predicate translate(
      FilterExpression filter, RelationshipReadAccess targets, RuntimeFieldSelection runtime) {
    return translate(filter, targets, runtime, true);
  }

  /** Compiles a server-built constraint without charging it to the caller complexity budget. */
  public Predicate translateTrusted(QueryConstraint constraint) {
    return translateTrusted(constraint, RelationshipReadAccess.none());
  }

  /** Compiles a relationship-aware server constraint without charging caller complexity limits. */
  public Predicate translateTrusted(QueryConstraint constraint, RelationshipReadAccess targets) {
    if (constraint == null) {
      return null;
    }
    RsqlCompilationState state =
        new RsqlCompilationState(parameterPrefix, targets, RuntimeFieldSelection.empty(), false);
    return new Predicate(
        expressions.compileConstraint(constraint, state), state.parameters, state.subqueries);
  }

  /** Compiles the SQL-level read rule for one described relationship. */
  public Predicate compileReadableRelationship(
      String relationshipName, RelationshipReadAccess targets) {
    RsqlCompilationState state =
        new RsqlCompilationState(
            parameterPrefix,
            java.util.Objects.requireNonNull(targets, "Target access"),
            RuntimeFieldSelection.empty(),
            false);
    String expression =
        relationships.compileReadableRelationship(
            description.requireRelationship(relationshipName), state);
    return new Predicate(expression, state.parameters, state.subqueries);
  }

  private Predicate translate(
      FilterExpression filter,
      RelationshipReadAccess targets,
      RuntimeFieldSelection runtime,
      boolean enforceComplexityLimit) {
    if (filter == null) {
      return null;
    }
    RsqlCompilationState state =
        new RsqlCompilationState(parameterPrefix, targets, runtime, enforceComplexityLimit);
    return new Predicate(expressions.compile(filter, state), state.parameters, state.subqueries);
  }

  /**
   * One correlated subquery, kept out of the expression text.
   *
   * <p>Blaze's expression parser accepts no subquery, so a subquery must be built through {@code
   * whereExpressionSubqueries} and referenced from the expression by name.
   */
  public record Subquery(Class<?> entityType, String alias, String whereExpression) {}

  public record Predicate(
      String expression, Map<String, Object> parameters, Map<String, Subquery> subqueries) {

    public Predicate {
      parameters = Map.copyOf(parameters);
      subqueries = Map.copyOf(subqueries);
    }

    public Predicate(String expression, Map<String, Object> parameters) {
      this(expression, parameters, Map.of());
    }

    public void apply(CommonQueryBuilder<?> query) {
      parameters.forEach(query::setParameter);
    }
  }
}
