// flow-typed signature: faf49df55f6590a778d3fabf7f807dd1
// flow-typed version: <<STUB>>/immutability-helper_v=3.1.1/flow_v0.206.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'immutability-helper'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'immutability-helper' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'immutability-helper/smoke-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'immutability-helper/index' {
  declare module.exports: $Exports<'immutability-helper'>;
}
declare module 'immutability-helper/index.js' {
  declare module.exports: $Exports<'immutability-helper'>;
}
declare module 'immutability-helper/smoke-test.js' {
  declare module.exports: $Exports<'immutability-helper/smoke-test'>;
}
