// flow-typed signature: f85a72e606cee5bea5f8569bac0f4892
// flow-typed version: <<STUB>>/npm_v=7.23.0/flow_v0.206.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'npm'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'npm' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'npm/bin/npm-cli' {
  declare module.exports: any;
}

declare module 'npm/bin/npx-cli' {
  declare module.exports: any;
}

declare module 'npm/lib/access' {
  declare module.exports: any;
}

declare module 'npm/lib/adduser' {
  declare module.exports: any;
}

declare module 'npm/lib/audit' {
  declare module.exports: any;
}

declare module 'npm/lib/auth/legacy' {
  declare module.exports: any;
}

declare module 'npm/lib/auth/oauth' {
  declare module.exports: any;
}

declare module 'npm/lib/auth/saml' {
  declare module.exports: any;
}

declare module 'npm/lib/auth/sso' {
  declare module.exports: any;
}

declare module 'npm/lib/base-command' {
  declare module.exports: any;
}

declare module 'npm/lib/bin' {
  declare module.exports: any;
}

declare module 'npm/lib/birthday' {
  declare module.exports: any;
}

declare module 'npm/lib/bugs' {
  declare module.exports: any;
}

declare module 'npm/lib/cache' {
  declare module.exports: any;
}

declare module 'npm/lib/ci' {
  declare module.exports: any;
}

declare module 'npm/lib/cli' {
  declare module.exports: any;
}

declare module 'npm/lib/completion' {
  declare module.exports: any;
}

declare module 'npm/lib/config' {
  declare module.exports: any;
}

declare module 'npm/lib/dedupe' {
  declare module.exports: any;
}

declare module 'npm/lib/deprecate' {
  declare module.exports: any;
}

declare module 'npm/lib/diff' {
  declare module.exports: any;
}

declare module 'npm/lib/dist-tag' {
  declare module.exports: any;
}

declare module 'npm/lib/docs' {
  declare module.exports: any;
}

declare module 'npm/lib/doctor' {
  declare module.exports: any;
}

declare module 'npm/lib/edit' {
  declare module.exports: any;
}

declare module 'npm/lib/exec' {
  declare module.exports: any;
}

declare module 'npm/lib/exec/get-workspace-location-msg' {
  declare module.exports: any;
}

declare module 'npm/lib/explain' {
  declare module.exports: any;
}

declare module 'npm/lib/explore' {
  declare module.exports: any;
}

declare module 'npm/lib/find-dupes' {
  declare module.exports: any;
}

declare module 'npm/lib/fund' {
  declare module.exports: any;
}

declare module 'npm/lib/get' {
  declare module.exports: any;
}

declare module 'npm/lib/help-search' {
  declare module.exports: any;
}

declare module 'npm/lib/help' {
  declare module.exports: any;
}

declare module 'npm/lib/hook' {
  declare module.exports: any;
}

declare module 'npm/lib/init' {
  declare module.exports: any;
}

declare module 'npm/lib/install-ci-test' {
  declare module.exports: any;
}

declare module 'npm/lib/install-test' {
  declare module.exports: any;
}

declare module 'npm/lib/install' {
  declare module.exports: any;
}

declare module 'npm/lib/link' {
  declare module.exports: any;
}

declare module 'npm/lib/ll' {
  declare module.exports: any;
}

declare module 'npm/lib/logout' {
  declare module.exports: any;
}

declare module 'npm/lib/ls' {
  declare module.exports: any;
}

declare module 'npm/lib/npm' {
  declare module.exports: any;
}

declare module 'npm/lib/org' {
  declare module.exports: any;
}

declare module 'npm/lib/outdated' {
  declare module.exports: any;
}

declare module 'npm/lib/owner' {
  declare module.exports: any;
}

declare module 'npm/lib/pack' {
  declare module.exports: any;
}

declare module 'npm/lib/ping' {
  declare module.exports: any;
}

declare module 'npm/lib/pkg' {
  declare module.exports: any;
}

declare module 'npm/lib/prefix' {
  declare module.exports: any;
}

declare module 'npm/lib/profile' {
  declare module.exports: any;
}

declare module 'npm/lib/prune' {
  declare module.exports: any;
}

declare module 'npm/lib/publish' {
  declare module.exports: any;
}

declare module 'npm/lib/rebuild' {
  declare module.exports: any;
}

declare module 'npm/lib/repo' {
  declare module.exports: any;
}

declare module 'npm/lib/restart' {
  declare module.exports: any;
}

declare module 'npm/lib/root' {
  declare module.exports: any;
}

declare module 'npm/lib/run-script' {
  declare module.exports: any;
}

declare module 'npm/lib/search' {
  declare module.exports: any;
}

declare module 'npm/lib/search/format-package-stream' {
  declare module.exports: any;
}

declare module 'npm/lib/search/package-filter' {
  declare module.exports: any;
}

declare module 'npm/lib/set-script' {
  declare module.exports: any;
}

declare module 'npm/lib/set' {
  declare module.exports: any;
}

declare module 'npm/lib/shrinkwrap' {
  declare module.exports: any;
}

declare module 'npm/lib/star' {
  declare module.exports: any;
}

declare module 'npm/lib/stars' {
  declare module.exports: any;
}

declare module 'npm/lib/start' {
  declare module.exports: any;
}

declare module 'npm/lib/stop' {
  declare module.exports: any;
}

declare module 'npm/lib/team' {
  declare module.exports: any;
}

declare module 'npm/lib/test' {
  declare module.exports: any;
}

declare module 'npm/lib/token' {
  declare module.exports: any;
}

declare module 'npm/lib/uninstall' {
  declare module.exports: any;
}

declare module 'npm/lib/unpublish' {
  declare module.exports: any;
}

declare module 'npm/lib/unstar' {
  declare module.exports: any;
}

declare module 'npm/lib/update' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/ansi-trim' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/audit-error' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/cleanup-log-files' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/cmd-list' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/completion/installed-deep' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/completion/installed-shallow' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/config/definition' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/config/definitions' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/config/describe-all' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/config/flatten' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/config' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/deref-command' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/did-you-mean' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/error-message' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/exit-handler' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/explain-dep' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/explain-eresolve' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/file-exists' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/format-bytes' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/get-identity' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/get-project-scope' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/hosted-git-info-from-manifest' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/is-windows-bash' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/is-windows-shell' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/is-windows' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/lifecycle-cmd' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/npm-usage' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/open-url' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/otplease' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/path' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/ping' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/proc-log-listener' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/pulse-till-done' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/queryable' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/read-package-name' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/read-user-info' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/reify-finish' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/reify-output' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/replace-info' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/setup-log' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/split-package-names' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/tar' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/unsupported' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/update-notifier' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/usage' {
  declare module.exports: any;
}

declare module 'npm/lib/version' {
  declare module.exports: any;
}

declare module 'npm/lib/view' {
  declare module.exports: any;
}

declare module 'npm/lib/whoami' {
  declare module.exports: any;
}

declare module 'npm/lib/workspaces/arborist-cmd' {
  declare module.exports: any;
}

declare module 'npm/lib/workspaces/get-workspaces' {
  declare module.exports: any;
}

// Filename aliases
declare module 'npm/bin/npm-cli.js' {
  declare module.exports: $Exports<'npm/bin/npm-cli'>;
}
declare module 'npm/bin/npx-cli.js' {
  declare module.exports: $Exports<'npm/bin/npx-cli'>;
}
declare module 'npm/lib/access.js' {
  declare module.exports: $Exports<'npm/lib/access'>;
}
declare module 'npm/lib/adduser.js' {
  declare module.exports: $Exports<'npm/lib/adduser'>;
}
declare module 'npm/lib/audit.js' {
  declare module.exports: $Exports<'npm/lib/audit'>;
}
declare module 'npm/lib/auth/legacy.js' {
  declare module.exports: $Exports<'npm/lib/auth/legacy'>;
}
declare module 'npm/lib/auth/oauth.js' {
  declare module.exports: $Exports<'npm/lib/auth/oauth'>;
}
declare module 'npm/lib/auth/saml.js' {
  declare module.exports: $Exports<'npm/lib/auth/saml'>;
}
declare module 'npm/lib/auth/sso.js' {
  declare module.exports: $Exports<'npm/lib/auth/sso'>;
}
declare module 'npm/lib/base-command.js' {
  declare module.exports: $Exports<'npm/lib/base-command'>;
}
declare module 'npm/lib/bin.js' {
  declare module.exports: $Exports<'npm/lib/bin'>;
}
declare module 'npm/lib/birthday.js' {
  declare module.exports: $Exports<'npm/lib/birthday'>;
}
declare module 'npm/lib/bugs.js' {
  declare module.exports: $Exports<'npm/lib/bugs'>;
}
declare module 'npm/lib/cache.js' {
  declare module.exports: $Exports<'npm/lib/cache'>;
}
declare module 'npm/lib/ci.js' {
  declare module.exports: $Exports<'npm/lib/ci'>;
}
declare module 'npm/lib/cli.js' {
  declare module.exports: $Exports<'npm/lib/cli'>;
}
declare module 'npm/lib/completion.js' {
  declare module.exports: $Exports<'npm/lib/completion'>;
}
declare module 'npm/lib/config.js' {
  declare module.exports: $Exports<'npm/lib/config'>;
}
declare module 'npm/lib/dedupe.js' {
  declare module.exports: $Exports<'npm/lib/dedupe'>;
}
declare module 'npm/lib/deprecate.js' {
  declare module.exports: $Exports<'npm/lib/deprecate'>;
}
declare module 'npm/lib/diff.js' {
  declare module.exports: $Exports<'npm/lib/diff'>;
}
declare module 'npm/lib/dist-tag.js' {
  declare module.exports: $Exports<'npm/lib/dist-tag'>;
}
declare module 'npm/lib/docs.js' {
  declare module.exports: $Exports<'npm/lib/docs'>;
}
declare module 'npm/lib/doctor.js' {
  declare module.exports: $Exports<'npm/lib/doctor'>;
}
declare module 'npm/lib/edit.js' {
  declare module.exports: $Exports<'npm/lib/edit'>;
}
declare module 'npm/lib/exec.js' {
  declare module.exports: $Exports<'npm/lib/exec'>;
}
declare module 'npm/lib/exec/get-workspace-location-msg.js' {
  declare module.exports: $Exports<'npm/lib/exec/get-workspace-location-msg'>;
}
declare module 'npm/lib/explain.js' {
  declare module.exports: $Exports<'npm/lib/explain'>;
}
declare module 'npm/lib/explore.js' {
  declare module.exports: $Exports<'npm/lib/explore'>;
}
declare module 'npm/lib/find-dupes.js' {
  declare module.exports: $Exports<'npm/lib/find-dupes'>;
}
declare module 'npm/lib/fund.js' {
  declare module.exports: $Exports<'npm/lib/fund'>;
}
declare module 'npm/lib/get.js' {
  declare module.exports: $Exports<'npm/lib/get'>;
}
declare module 'npm/lib/help-search.js' {
  declare module.exports: $Exports<'npm/lib/help-search'>;
}
declare module 'npm/lib/help.js' {
  declare module.exports: $Exports<'npm/lib/help'>;
}
declare module 'npm/lib/hook.js' {
  declare module.exports: $Exports<'npm/lib/hook'>;
}
declare module 'npm/lib/init.js' {
  declare module.exports: $Exports<'npm/lib/init'>;
}
declare module 'npm/lib/install-ci-test.js' {
  declare module.exports: $Exports<'npm/lib/install-ci-test'>;
}
declare module 'npm/lib/install-test.js' {
  declare module.exports: $Exports<'npm/lib/install-test'>;
}
declare module 'npm/lib/install.js' {
  declare module.exports: $Exports<'npm/lib/install'>;
}
declare module 'npm/lib/link.js' {
  declare module.exports: $Exports<'npm/lib/link'>;
}
declare module 'npm/lib/ll.js' {
  declare module.exports: $Exports<'npm/lib/ll'>;
}
declare module 'npm/lib/logout.js' {
  declare module.exports: $Exports<'npm/lib/logout'>;
}
declare module 'npm/lib/ls.js' {
  declare module.exports: $Exports<'npm/lib/ls'>;
}
declare module 'npm/lib/npm.js' {
  declare module.exports: $Exports<'npm/lib/npm'>;
}
declare module 'npm/lib/org.js' {
  declare module.exports: $Exports<'npm/lib/org'>;
}
declare module 'npm/lib/outdated.js' {
  declare module.exports: $Exports<'npm/lib/outdated'>;
}
declare module 'npm/lib/owner.js' {
  declare module.exports: $Exports<'npm/lib/owner'>;
}
declare module 'npm/lib/pack.js' {
  declare module.exports: $Exports<'npm/lib/pack'>;
}
declare module 'npm/lib/ping.js' {
  declare module.exports: $Exports<'npm/lib/ping'>;
}
declare module 'npm/lib/pkg.js' {
  declare module.exports: $Exports<'npm/lib/pkg'>;
}
declare module 'npm/lib/prefix.js' {
  declare module.exports: $Exports<'npm/lib/prefix'>;
}
declare module 'npm/lib/profile.js' {
  declare module.exports: $Exports<'npm/lib/profile'>;
}
declare module 'npm/lib/prune.js' {
  declare module.exports: $Exports<'npm/lib/prune'>;
}
declare module 'npm/lib/publish.js' {
  declare module.exports: $Exports<'npm/lib/publish'>;
}
declare module 'npm/lib/rebuild.js' {
  declare module.exports: $Exports<'npm/lib/rebuild'>;
}
declare module 'npm/lib/repo.js' {
  declare module.exports: $Exports<'npm/lib/repo'>;
}
declare module 'npm/lib/restart.js' {
  declare module.exports: $Exports<'npm/lib/restart'>;
}
declare module 'npm/lib/root.js' {
  declare module.exports: $Exports<'npm/lib/root'>;
}
declare module 'npm/lib/run-script.js' {
  declare module.exports: $Exports<'npm/lib/run-script'>;
}
declare module 'npm/lib/search.js' {
  declare module.exports: $Exports<'npm/lib/search'>;
}
declare module 'npm/lib/search/format-package-stream.js' {
  declare module.exports: $Exports<'npm/lib/search/format-package-stream'>;
}
declare module 'npm/lib/search/package-filter.js' {
  declare module.exports: $Exports<'npm/lib/search/package-filter'>;
}
declare module 'npm/lib/set-script.js' {
  declare module.exports: $Exports<'npm/lib/set-script'>;
}
declare module 'npm/lib/set.js' {
  declare module.exports: $Exports<'npm/lib/set'>;
}
declare module 'npm/lib/shrinkwrap.js' {
  declare module.exports: $Exports<'npm/lib/shrinkwrap'>;
}
declare module 'npm/lib/star.js' {
  declare module.exports: $Exports<'npm/lib/star'>;
}
declare module 'npm/lib/stars.js' {
  declare module.exports: $Exports<'npm/lib/stars'>;
}
declare module 'npm/lib/start.js' {
  declare module.exports: $Exports<'npm/lib/start'>;
}
declare module 'npm/lib/stop.js' {
  declare module.exports: $Exports<'npm/lib/stop'>;
}
declare module 'npm/lib/team.js' {
  declare module.exports: $Exports<'npm/lib/team'>;
}
declare module 'npm/lib/test.js' {
  declare module.exports: $Exports<'npm/lib/test'>;
}
declare module 'npm/lib/token.js' {
  declare module.exports: $Exports<'npm/lib/token'>;
}
declare module 'npm/lib/uninstall.js' {
  declare module.exports: $Exports<'npm/lib/uninstall'>;
}
declare module 'npm/lib/unpublish.js' {
  declare module.exports: $Exports<'npm/lib/unpublish'>;
}
declare module 'npm/lib/unstar.js' {
  declare module.exports: $Exports<'npm/lib/unstar'>;
}
declare module 'npm/lib/update.js' {
  declare module.exports: $Exports<'npm/lib/update'>;
}
declare module 'npm/lib/utils/ansi-trim.js' {
  declare module.exports: $Exports<'npm/lib/utils/ansi-trim'>;
}
declare module 'npm/lib/utils/audit-error.js' {
  declare module.exports: $Exports<'npm/lib/utils/audit-error'>;
}
declare module 'npm/lib/utils/cleanup-log-files.js' {
  declare module.exports: $Exports<'npm/lib/utils/cleanup-log-files'>;
}
declare module 'npm/lib/utils/cmd-list.js' {
  declare module.exports: $Exports<'npm/lib/utils/cmd-list'>;
}
declare module 'npm/lib/utils/completion/installed-deep.js' {
  declare module.exports: $Exports<'npm/lib/utils/completion/installed-deep'>;
}
declare module 'npm/lib/utils/completion/installed-shallow.js' {
  declare module.exports: $Exports<'npm/lib/utils/completion/installed-shallow'>;
}
declare module 'npm/lib/utils/config/definition.js' {
  declare module.exports: $Exports<'npm/lib/utils/config/definition'>;
}
declare module 'npm/lib/utils/config/definitions.js' {
  declare module.exports: $Exports<'npm/lib/utils/config/definitions'>;
}
declare module 'npm/lib/utils/config/describe-all.js' {
  declare module.exports: $Exports<'npm/lib/utils/config/describe-all'>;
}
declare module 'npm/lib/utils/config/flatten.js' {
  declare module.exports: $Exports<'npm/lib/utils/config/flatten'>;
}
declare module 'npm/lib/utils/config/index' {
  declare module.exports: $Exports<'npm/lib/utils/config'>;
}
declare module 'npm/lib/utils/config/index.js' {
  declare module.exports: $Exports<'npm/lib/utils/config'>;
}
declare module 'npm/lib/utils/deref-command.js' {
  declare module.exports: $Exports<'npm/lib/utils/deref-command'>;
}
declare module 'npm/lib/utils/did-you-mean.js' {
  declare module.exports: $Exports<'npm/lib/utils/did-you-mean'>;
}
declare module 'npm/lib/utils/error-message.js' {
  declare module.exports: $Exports<'npm/lib/utils/error-message'>;
}
declare module 'npm/lib/utils/exit-handler.js' {
  declare module.exports: $Exports<'npm/lib/utils/exit-handler'>;
}
declare module 'npm/lib/utils/explain-dep.js' {
  declare module.exports: $Exports<'npm/lib/utils/explain-dep'>;
}
declare module 'npm/lib/utils/explain-eresolve.js' {
  declare module.exports: $Exports<'npm/lib/utils/explain-eresolve'>;
}
declare module 'npm/lib/utils/file-exists.js' {
  declare module.exports: $Exports<'npm/lib/utils/file-exists'>;
}
declare module 'npm/lib/utils/format-bytes.js' {
  declare module.exports: $Exports<'npm/lib/utils/format-bytes'>;
}
declare module 'npm/lib/utils/get-identity.js' {
  declare module.exports: $Exports<'npm/lib/utils/get-identity'>;
}
declare module 'npm/lib/utils/get-project-scope.js' {
  declare module.exports: $Exports<'npm/lib/utils/get-project-scope'>;
}
declare module 'npm/lib/utils/hosted-git-info-from-manifest.js' {
  declare module.exports: $Exports<'npm/lib/utils/hosted-git-info-from-manifest'>;
}
declare module 'npm/lib/utils/is-windows-bash.js' {
  declare module.exports: $Exports<'npm/lib/utils/is-windows-bash'>;
}
declare module 'npm/lib/utils/is-windows-shell.js' {
  declare module.exports: $Exports<'npm/lib/utils/is-windows-shell'>;
}
declare module 'npm/lib/utils/is-windows.js' {
  declare module.exports: $Exports<'npm/lib/utils/is-windows'>;
}
declare module 'npm/lib/utils/lifecycle-cmd.js' {
  declare module.exports: $Exports<'npm/lib/utils/lifecycle-cmd'>;
}
declare module 'npm/lib/utils/npm-usage.js' {
  declare module.exports: $Exports<'npm/lib/utils/npm-usage'>;
}
declare module 'npm/lib/utils/open-url.js' {
  declare module.exports: $Exports<'npm/lib/utils/open-url'>;
}
declare module 'npm/lib/utils/otplease.js' {
  declare module.exports: $Exports<'npm/lib/utils/otplease'>;
}
declare module 'npm/lib/utils/path.js' {
  declare module.exports: $Exports<'npm/lib/utils/path'>;
}
declare module 'npm/lib/utils/ping.js' {
  declare module.exports: $Exports<'npm/lib/utils/ping'>;
}
declare module 'npm/lib/utils/proc-log-listener.js' {
  declare module.exports: $Exports<'npm/lib/utils/proc-log-listener'>;
}
declare module 'npm/lib/utils/pulse-till-done.js' {
  declare module.exports: $Exports<'npm/lib/utils/pulse-till-done'>;
}
declare module 'npm/lib/utils/queryable.js' {
  declare module.exports: $Exports<'npm/lib/utils/queryable'>;
}
declare module 'npm/lib/utils/read-package-name.js' {
  declare module.exports: $Exports<'npm/lib/utils/read-package-name'>;
}
declare module 'npm/lib/utils/read-user-info.js' {
  declare module.exports: $Exports<'npm/lib/utils/read-user-info'>;
}
declare module 'npm/lib/utils/reify-finish.js' {
  declare module.exports: $Exports<'npm/lib/utils/reify-finish'>;
}
declare module 'npm/lib/utils/reify-output.js' {
  declare module.exports: $Exports<'npm/lib/utils/reify-output'>;
}
declare module 'npm/lib/utils/replace-info.js' {
  declare module.exports: $Exports<'npm/lib/utils/replace-info'>;
}
declare module 'npm/lib/utils/setup-log.js' {
  declare module.exports: $Exports<'npm/lib/utils/setup-log'>;
}
declare module 'npm/lib/utils/split-package-names.js' {
  declare module.exports: $Exports<'npm/lib/utils/split-package-names'>;
}
declare module 'npm/lib/utils/tar.js' {
  declare module.exports: $Exports<'npm/lib/utils/tar'>;
}
declare module 'npm/lib/utils/unsupported.js' {
  declare module.exports: $Exports<'npm/lib/utils/unsupported'>;
}
declare module 'npm/lib/utils/update-notifier.js' {
  declare module.exports: $Exports<'npm/lib/utils/update-notifier'>;
}
declare module 'npm/lib/utils/usage.js' {
  declare module.exports: $Exports<'npm/lib/utils/usage'>;
}
declare module 'npm/lib/version.js' {
  declare module.exports: $Exports<'npm/lib/version'>;
}
declare module 'npm/lib/view.js' {
  declare module.exports: $Exports<'npm/lib/view'>;
}
declare module 'npm/lib/whoami.js' {
  declare module.exports: $Exports<'npm/lib/whoami'>;
}
declare module 'npm/lib/workspaces/arborist-cmd.js' {
  declare module.exports: $Exports<'npm/lib/workspaces/arborist-cmd'>;
}
declare module 'npm/lib/workspaces/get-workspaces.js' {
  declare module.exports: $Exports<'npm/lib/workspaces/get-workspaces'>;
}
