// flow-typed signature: 8e783bc35a2f905501afdba80945c37d
// flow-typed version: <<STUB>>/photoswipe_v=5.3.8/flow_v0.206.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'photoswipe'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'photoswipe' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'photoswipe/dist/photoswipe-lightbox.esm' {
  declare module.exports: any;
}

declare module 'photoswipe/dist/photoswipe-lightbox.esm.min' {
  declare module.exports: any;
}

declare module 'photoswipe/dist/photoswipe.esm' {
  declare module.exports: any;
}

declare module 'photoswipe/dist/photoswipe.esm.min' {
  declare module.exports: any;
}

declare module 'photoswipe/dist/umd/photoswipe-lightbox.umd.min' {
  declare module.exports: any;
}

declare module 'photoswipe/dist/umd/photoswipe.umd.min' {
  declare module.exports: any;
}

declare module 'photoswipe/src/js/core/base' {
  declare module.exports: any;
}

declare module 'photoswipe/src/js/core/eventable' {
  declare module.exports: any;
}

declare module 'photoswipe/src/js/gestures/drag-handler' {
  declare module.exports: any;
}

declare module 'photoswipe/src/js/gestures/gestures' {
  declare module.exports: any;
}

declare module 'photoswipe/src/js/gestures/tap-handler' {
  declare module.exports: any;
}

declare module 'photoswipe/src/js/gestures/zoom-handler' {
  declare module.exports: any;
}

declare module 'photoswipe/src/js/keyboard' {
  declare module.exports: any;
}

declare module 'photoswipe/src/js/lightbox/lightbox' {
  declare module.exports: any;
}

declare module 'photoswipe/src/js/main-scroll' {
  declare module.exports: any;
}

declare module 'photoswipe/src/js/opener' {
  declare module.exports: any;
}

declare module 'photoswipe/src/js/photoswipe' {
  declare module.exports: any;
}

declare module 'photoswipe/src/js/scroll-wheel' {
  declare module.exports: any;
}

declare module 'photoswipe/src/js/slide/content' {
  declare module.exports: any;
}

declare module 'photoswipe/src/js/slide/get-thumb-bounds' {
  declare module.exports: any;
}

declare module 'photoswipe/src/js/slide/loader' {
  declare module.exports: any;
}

declare module 'photoswipe/src/js/slide/pan-bounds' {
  declare module.exports: any;
}

declare module 'photoswipe/src/js/slide/placeholder' {
  declare module.exports: any;
}

declare module 'photoswipe/src/js/slide/slide' {
  declare module.exports: any;
}

declare module 'photoswipe/src/js/slide/zoom-level' {
  declare module.exports: any;
}

declare module 'photoswipe/src/js/ui/button-arrow' {
  declare module.exports: any;
}

declare module 'photoswipe/src/js/ui/button-close' {
  declare module.exports: any;
}

declare module 'photoswipe/src/js/ui/button-zoom' {
  declare module.exports: any;
}

declare module 'photoswipe/src/js/ui/counter-indicator' {
  declare module.exports: any;
}

declare module 'photoswipe/src/js/ui/loading-indicator' {
  declare module.exports: any;
}

declare module 'photoswipe/src/js/ui/ui-element' {
  declare module.exports: any;
}

declare module 'photoswipe/src/js/ui/ui' {
  declare module.exports: any;
}

declare module 'photoswipe/src/js/util/animations' {
  declare module.exports: any;
}

declare module 'photoswipe/src/js/util/css-animation' {
  declare module.exports: any;
}

declare module 'photoswipe/src/js/util/dom-events' {
  declare module.exports: any;
}

declare module 'photoswipe/src/js/util/spring-animation' {
  declare module.exports: any;
}

declare module 'photoswipe/src/js/util/spring-easer' {
  declare module.exports: any;
}

declare module 'photoswipe/src/js/util/util' {
  declare module.exports: any;
}

declare module 'photoswipe/src/js/util/viewport-size' {
  declare module.exports: any;
}

// Filename aliases
declare module 'photoswipe/dist/photoswipe-lightbox.esm.js' {
  declare module.exports: $Exports<'photoswipe/dist/photoswipe-lightbox.esm'>;
}
declare module 'photoswipe/dist/photoswipe-lightbox.esm.min.js' {
  declare module.exports: $Exports<'photoswipe/dist/photoswipe-lightbox.esm.min'>;
}
declare module 'photoswipe/dist/photoswipe.esm.js' {
  declare module.exports: $Exports<'photoswipe/dist/photoswipe.esm'>;
}
declare module 'photoswipe/dist/photoswipe.esm.min.js' {
  declare module.exports: $Exports<'photoswipe/dist/photoswipe.esm.min'>;
}
declare module 'photoswipe/dist/umd/photoswipe-lightbox.umd.min.js' {
  declare module.exports: $Exports<'photoswipe/dist/umd/photoswipe-lightbox.umd.min'>;
}
declare module 'photoswipe/dist/umd/photoswipe.umd.min.js' {
  declare module.exports: $Exports<'photoswipe/dist/umd/photoswipe.umd.min'>;
}
declare module 'photoswipe/src/js/core/base.js' {
  declare module.exports: $Exports<'photoswipe/src/js/core/base'>;
}
declare module 'photoswipe/src/js/core/eventable.js' {
  declare module.exports: $Exports<'photoswipe/src/js/core/eventable'>;
}
declare module 'photoswipe/src/js/gestures/drag-handler.js' {
  declare module.exports: $Exports<'photoswipe/src/js/gestures/drag-handler'>;
}
declare module 'photoswipe/src/js/gestures/gestures.js' {
  declare module.exports: $Exports<'photoswipe/src/js/gestures/gestures'>;
}
declare module 'photoswipe/src/js/gestures/tap-handler.js' {
  declare module.exports: $Exports<'photoswipe/src/js/gestures/tap-handler'>;
}
declare module 'photoswipe/src/js/gestures/zoom-handler.js' {
  declare module.exports: $Exports<'photoswipe/src/js/gestures/zoom-handler'>;
}
declare module 'photoswipe/src/js/keyboard.js' {
  declare module.exports: $Exports<'photoswipe/src/js/keyboard'>;
}
declare module 'photoswipe/src/js/lightbox/lightbox.js' {
  declare module.exports: $Exports<'photoswipe/src/js/lightbox/lightbox'>;
}
declare module 'photoswipe/src/js/main-scroll.js' {
  declare module.exports: $Exports<'photoswipe/src/js/main-scroll'>;
}
declare module 'photoswipe/src/js/opener.js' {
  declare module.exports: $Exports<'photoswipe/src/js/opener'>;
}
declare module 'photoswipe/src/js/photoswipe.js' {
  declare module.exports: $Exports<'photoswipe/src/js/photoswipe'>;
}
declare module 'photoswipe/src/js/scroll-wheel.js' {
  declare module.exports: $Exports<'photoswipe/src/js/scroll-wheel'>;
}
declare module 'photoswipe/src/js/slide/content.js' {
  declare module.exports: $Exports<'photoswipe/src/js/slide/content'>;
}
declare module 'photoswipe/src/js/slide/get-thumb-bounds.js' {
  declare module.exports: $Exports<'photoswipe/src/js/slide/get-thumb-bounds'>;
}
declare module 'photoswipe/src/js/slide/loader.js' {
  declare module.exports: $Exports<'photoswipe/src/js/slide/loader'>;
}
declare module 'photoswipe/src/js/slide/pan-bounds.js' {
  declare module.exports: $Exports<'photoswipe/src/js/slide/pan-bounds'>;
}
declare module 'photoswipe/src/js/slide/placeholder.js' {
  declare module.exports: $Exports<'photoswipe/src/js/slide/placeholder'>;
}
declare module 'photoswipe/src/js/slide/slide.js' {
  declare module.exports: $Exports<'photoswipe/src/js/slide/slide'>;
}
declare module 'photoswipe/src/js/slide/zoom-level.js' {
  declare module.exports: $Exports<'photoswipe/src/js/slide/zoom-level'>;
}
declare module 'photoswipe/src/js/ui/button-arrow.js' {
  declare module.exports: $Exports<'photoswipe/src/js/ui/button-arrow'>;
}
declare module 'photoswipe/src/js/ui/button-close.js' {
  declare module.exports: $Exports<'photoswipe/src/js/ui/button-close'>;
}
declare module 'photoswipe/src/js/ui/button-zoom.js' {
  declare module.exports: $Exports<'photoswipe/src/js/ui/button-zoom'>;
}
declare module 'photoswipe/src/js/ui/counter-indicator.js' {
  declare module.exports: $Exports<'photoswipe/src/js/ui/counter-indicator'>;
}
declare module 'photoswipe/src/js/ui/loading-indicator.js' {
  declare module.exports: $Exports<'photoswipe/src/js/ui/loading-indicator'>;
}
declare module 'photoswipe/src/js/ui/ui-element.js' {
  declare module.exports: $Exports<'photoswipe/src/js/ui/ui-element'>;
}
declare module 'photoswipe/src/js/ui/ui.js' {
  declare module.exports: $Exports<'photoswipe/src/js/ui/ui'>;
}
declare module 'photoswipe/src/js/util/animations.js' {
  declare module.exports: $Exports<'photoswipe/src/js/util/animations'>;
}
declare module 'photoswipe/src/js/util/css-animation.js' {
  declare module.exports: $Exports<'photoswipe/src/js/util/css-animation'>;
}
declare module 'photoswipe/src/js/util/dom-events.js' {
  declare module.exports: $Exports<'photoswipe/src/js/util/dom-events'>;
}
declare module 'photoswipe/src/js/util/spring-animation.js' {
  declare module.exports: $Exports<'photoswipe/src/js/util/spring-animation'>;
}
declare module 'photoswipe/src/js/util/spring-easer.js' {
  declare module.exports: $Exports<'photoswipe/src/js/util/spring-easer'>;
}
declare module 'photoswipe/src/js/util/util.js' {
  declare module.exports: $Exports<'photoswipe/src/js/util/util'>;
}
declare module 'photoswipe/src/js/util/viewport-size.js' {
  declare module.exports: $Exports<'photoswipe/src/js/util/viewport-size'>;
}
