// flow-typed signature: db6244856e1ce88c7064a7b48241c4ae
// flow-typed version: <<STUB>>/qr-scanner_v^1.4.1/flow_v0.206.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'qr-scanner'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'qr-scanner' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'qr-scanner/qr-scanner-worker.min' {
  declare module.exports: any;
}

declare module 'qr-scanner/qr-scanner.legacy.min' {
  declare module.exports: any;
}

declare module 'qr-scanner/qr-scanner.min' {
  declare module.exports: any;
}

declare module 'qr-scanner/qr-scanner.umd.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'qr-scanner/qr-scanner-worker.min.js' {
  declare module.exports: $Exports<'qr-scanner/qr-scanner-worker.min'>;
}
declare module 'qr-scanner/qr-scanner.legacy.min.js' {
  declare module.exports: $Exports<'qr-scanner/qr-scanner.legacy.min'>;
}
declare module 'qr-scanner/qr-scanner.min.js' {
  declare module.exports: $Exports<'qr-scanner/qr-scanner.min'>;
}
declare module 'qr-scanner/qr-scanner.umd.min.js' {
  declare module.exports: $Exports<'qr-scanner/qr-scanner.umd.min'>;
}
