// flow-typed signature: f002fa94c738ec2925ecd7f96418700a
// flow-typed version: <<STUB>>/raw-loader_v^4.0.2/flow_v0.206.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'raw-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'raw-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'raw-loader/dist/cjs' {
  declare module.exports: any;
}

declare module 'raw-loader/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module 'raw-loader/dist/cjs.js' {
  declare module.exports: $Exports<'raw-loader/dist/cjs'>;
}
declare module 'raw-loader/dist/index' {
  declare module.exports: $Exports<'raw-loader/dist'>;
}
declare module 'raw-loader/dist/index.js' {
  declare module.exports: $Exports<'raw-loader/dist'>;
}
