// flow-typed signature: 4d3c3d964d26e60abaca0c0cfdccc987
// flow-typed version: <<STUB>>/react-zoom-pan-pinch_v=2.1.3/flow_v0.206.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-zoom-pan-pinch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-zoom-pan-pinch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-zoom-pan-pinch/dist/index.cjs' {
  declare module.exports: any;
}

declare module 'react-zoom-pan-pinch/dist/index.esm' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-zoom-pan-pinch/dist/index.cjs.js' {
  declare module.exports: $Exports<'react-zoom-pan-pinch/dist/index.cjs'>;
}
declare module 'react-zoom-pan-pinch/dist/index.esm.js' {
  declare module.exports: $Exports<'react-zoom-pan-pinch/dist/index.esm'>;
}
