// flow-typed signature: 5afcba27f5bc2546c6781afc5f802a66
// flow-typed version: <<STUB>>/tinymce_v^6.3.2/flow_v0.206.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tinymce'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tinymce' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tinymce/icons/default/icons' {
  declare module.exports: any;
}

declare module 'tinymce/icons/default/icons.min' {
  declare module.exports: any;
}

declare module 'tinymce/icons/default' {
  declare module.exports: any;
}

declare module 'tinymce/models/dom' {
  declare module.exports: any;
}

declare module 'tinymce/models/dom/model' {
  declare module.exports: any;
}

declare module 'tinymce/models/dom/model.min' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/advlist' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/advlist/plugin' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/advlist/plugin.min' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/anchor' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/anchor/plugin' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/anchor/plugin.min' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/autolink' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/autolink/plugin' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/autolink/plugin.min' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/autoresize' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/autoresize/plugin' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/autoresize/plugin.min' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/autosave' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/autosave/plugin' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/autosave/plugin.min' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/charmap' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/charmap/plugin' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/charmap/plugin.min' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/code' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/code/plugin' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/code/plugin.min' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/codesample' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/codesample/plugin' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/codesample/plugin.min' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/directionality' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/directionality/plugin' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/directionality/plugin.min' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/emoticons' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/emoticons/js/emojiimages' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/emoticons/js/emojiimages.min' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/emoticons/js/emojis' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/emoticons/js/emojis.min' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/emoticons/plugin' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/emoticons/plugin.min' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/fullscreen' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/fullscreen/plugin' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/fullscreen/plugin.min' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/help' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/help/plugin' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/help/plugin.min' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/image' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/image/plugin' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/image/plugin.min' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/importcss' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/importcss/plugin' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/importcss/plugin.min' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/insertdatetime' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/insertdatetime/plugin' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/insertdatetime/plugin.min' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/link' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/link/plugin' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/link/plugin.min' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/lists' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/lists/plugin' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/lists/plugin.min' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/media' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/media/plugin' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/media/plugin.min' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/nonbreaking' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/nonbreaking/plugin' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/nonbreaking/plugin.min' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/pagebreak' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/pagebreak/plugin' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/pagebreak/plugin.min' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/preview' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/preview/plugin' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/preview/plugin.min' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/quickbars' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/quickbars/plugin' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/quickbars/plugin.min' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/save' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/save/plugin' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/save/plugin.min' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/searchreplace' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/searchreplace/plugin' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/searchreplace/plugin.min' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/table' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/table/plugin' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/table/plugin.min' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/template' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/template/plugin' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/template/plugin.min' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/visualblocks' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/visualblocks/plugin' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/visualblocks/plugin.min' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/visualchars' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/visualchars/plugin' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/visualchars/plugin.min' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/wordcount' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/wordcount/plugin' {
  declare module.exports: any;
}

declare module 'tinymce/plugins/wordcount/plugin.min' {
  declare module.exports: any;
}

declare module 'tinymce/themes/silver' {
  declare module.exports: any;
}

declare module 'tinymce/themes/silver/theme' {
  declare module.exports: any;
}

declare module 'tinymce/themes/silver/theme.min' {
  declare module.exports: any;
}

declare module 'tinymce/tinymce' {
  declare module.exports: any;
}

declare module 'tinymce/tinymce.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tinymce/icons/default/icons.js' {
  declare module.exports: $Exports<'tinymce/icons/default/icons'>;
}
declare module 'tinymce/icons/default/icons.min.js' {
  declare module.exports: $Exports<'tinymce/icons/default/icons.min'>;
}
declare module 'tinymce/icons/default/index' {
  declare module.exports: $Exports<'tinymce/icons/default'>;
}
declare module 'tinymce/icons/default/index.js' {
  declare module.exports: $Exports<'tinymce/icons/default'>;
}
declare module 'tinymce/models/dom/index' {
  declare module.exports: $Exports<'tinymce/models/dom'>;
}
declare module 'tinymce/models/dom/index.js' {
  declare module.exports: $Exports<'tinymce/models/dom'>;
}
declare module 'tinymce/models/dom/model.js' {
  declare module.exports: $Exports<'tinymce/models/dom/model'>;
}
declare module 'tinymce/models/dom/model.min.js' {
  declare module.exports: $Exports<'tinymce/models/dom/model.min'>;
}
declare module 'tinymce/plugins/advlist/index' {
  declare module.exports: $Exports<'tinymce/plugins/advlist'>;
}
declare module 'tinymce/plugins/advlist/index.js' {
  declare module.exports: $Exports<'tinymce/plugins/advlist'>;
}
declare module 'tinymce/plugins/advlist/plugin.js' {
  declare module.exports: $Exports<'tinymce/plugins/advlist/plugin'>;
}
declare module 'tinymce/plugins/advlist/plugin.min.js' {
  declare module.exports: $Exports<'tinymce/plugins/advlist/plugin.min'>;
}
declare module 'tinymce/plugins/anchor/index' {
  declare module.exports: $Exports<'tinymce/plugins/anchor'>;
}
declare module 'tinymce/plugins/anchor/index.js' {
  declare module.exports: $Exports<'tinymce/plugins/anchor'>;
}
declare module 'tinymce/plugins/anchor/plugin.js' {
  declare module.exports: $Exports<'tinymce/plugins/anchor/plugin'>;
}
declare module 'tinymce/plugins/anchor/plugin.min.js' {
  declare module.exports: $Exports<'tinymce/plugins/anchor/plugin.min'>;
}
declare module 'tinymce/plugins/autolink/index' {
  declare module.exports: $Exports<'tinymce/plugins/autolink'>;
}
declare module 'tinymce/plugins/autolink/index.js' {
  declare module.exports: $Exports<'tinymce/plugins/autolink'>;
}
declare module 'tinymce/plugins/autolink/plugin.js' {
  declare module.exports: $Exports<'tinymce/plugins/autolink/plugin'>;
}
declare module 'tinymce/plugins/autolink/plugin.min.js' {
  declare module.exports: $Exports<'tinymce/plugins/autolink/plugin.min'>;
}
declare module 'tinymce/plugins/autoresize/index' {
  declare module.exports: $Exports<'tinymce/plugins/autoresize'>;
}
declare module 'tinymce/plugins/autoresize/index.js' {
  declare module.exports: $Exports<'tinymce/plugins/autoresize'>;
}
declare module 'tinymce/plugins/autoresize/plugin.js' {
  declare module.exports: $Exports<'tinymce/plugins/autoresize/plugin'>;
}
declare module 'tinymce/plugins/autoresize/plugin.min.js' {
  declare module.exports: $Exports<'tinymce/plugins/autoresize/plugin.min'>;
}
declare module 'tinymce/plugins/autosave/index' {
  declare module.exports: $Exports<'tinymce/plugins/autosave'>;
}
declare module 'tinymce/plugins/autosave/index.js' {
  declare module.exports: $Exports<'tinymce/plugins/autosave'>;
}
declare module 'tinymce/plugins/autosave/plugin.js' {
  declare module.exports: $Exports<'tinymce/plugins/autosave/plugin'>;
}
declare module 'tinymce/plugins/autosave/plugin.min.js' {
  declare module.exports: $Exports<'tinymce/plugins/autosave/plugin.min'>;
}
declare module 'tinymce/plugins/charmap/index' {
  declare module.exports: $Exports<'tinymce/plugins/charmap'>;
}
declare module 'tinymce/plugins/charmap/index.js' {
  declare module.exports: $Exports<'tinymce/plugins/charmap'>;
}
declare module 'tinymce/plugins/charmap/plugin.js' {
  declare module.exports: $Exports<'tinymce/plugins/charmap/plugin'>;
}
declare module 'tinymce/plugins/charmap/plugin.min.js' {
  declare module.exports: $Exports<'tinymce/plugins/charmap/plugin.min'>;
}
declare module 'tinymce/plugins/code/index' {
  declare module.exports: $Exports<'tinymce/plugins/code'>;
}
declare module 'tinymce/plugins/code/index.js' {
  declare module.exports: $Exports<'tinymce/plugins/code'>;
}
declare module 'tinymce/plugins/code/plugin.js' {
  declare module.exports: $Exports<'tinymce/plugins/code/plugin'>;
}
declare module 'tinymce/plugins/code/plugin.min.js' {
  declare module.exports: $Exports<'tinymce/plugins/code/plugin.min'>;
}
declare module 'tinymce/plugins/codesample/index' {
  declare module.exports: $Exports<'tinymce/plugins/codesample'>;
}
declare module 'tinymce/plugins/codesample/index.js' {
  declare module.exports: $Exports<'tinymce/plugins/codesample'>;
}
declare module 'tinymce/plugins/codesample/plugin.js' {
  declare module.exports: $Exports<'tinymce/plugins/codesample/plugin'>;
}
declare module 'tinymce/plugins/codesample/plugin.min.js' {
  declare module.exports: $Exports<'tinymce/plugins/codesample/plugin.min'>;
}
declare module 'tinymce/plugins/directionality/index' {
  declare module.exports: $Exports<'tinymce/plugins/directionality'>;
}
declare module 'tinymce/plugins/directionality/index.js' {
  declare module.exports: $Exports<'tinymce/plugins/directionality'>;
}
declare module 'tinymce/plugins/directionality/plugin.js' {
  declare module.exports: $Exports<'tinymce/plugins/directionality/plugin'>;
}
declare module 'tinymce/plugins/directionality/plugin.min.js' {
  declare module.exports: $Exports<'tinymce/plugins/directionality/plugin.min'>;
}
declare module 'tinymce/plugins/emoticons/index' {
  declare module.exports: $Exports<'tinymce/plugins/emoticons'>;
}
declare module 'tinymce/plugins/emoticons/index.js' {
  declare module.exports: $Exports<'tinymce/plugins/emoticons'>;
}
declare module 'tinymce/plugins/emoticons/js/emojiimages.js' {
  declare module.exports: $Exports<'tinymce/plugins/emoticons/js/emojiimages'>;
}
declare module 'tinymce/plugins/emoticons/js/emojiimages.min.js' {
  declare module.exports: $Exports<'tinymce/plugins/emoticons/js/emojiimages.min'>;
}
declare module 'tinymce/plugins/emoticons/js/emojis.js' {
  declare module.exports: $Exports<'tinymce/plugins/emoticons/js/emojis'>;
}
declare module 'tinymce/plugins/emoticons/js/emojis.min.js' {
  declare module.exports: $Exports<'tinymce/plugins/emoticons/js/emojis.min'>;
}
declare module 'tinymce/plugins/emoticons/plugin.js' {
  declare module.exports: $Exports<'tinymce/plugins/emoticons/plugin'>;
}
declare module 'tinymce/plugins/emoticons/plugin.min.js' {
  declare module.exports: $Exports<'tinymce/plugins/emoticons/plugin.min'>;
}
declare module 'tinymce/plugins/fullscreen/index' {
  declare module.exports: $Exports<'tinymce/plugins/fullscreen'>;
}
declare module 'tinymce/plugins/fullscreen/index.js' {
  declare module.exports: $Exports<'tinymce/plugins/fullscreen'>;
}
declare module 'tinymce/plugins/fullscreen/plugin.js' {
  declare module.exports: $Exports<'tinymce/plugins/fullscreen/plugin'>;
}
declare module 'tinymce/plugins/fullscreen/plugin.min.js' {
  declare module.exports: $Exports<'tinymce/plugins/fullscreen/plugin.min'>;
}
declare module 'tinymce/plugins/help/index' {
  declare module.exports: $Exports<'tinymce/plugins/help'>;
}
declare module 'tinymce/plugins/help/index.js' {
  declare module.exports: $Exports<'tinymce/plugins/help'>;
}
declare module 'tinymce/plugins/help/plugin.js' {
  declare module.exports: $Exports<'tinymce/plugins/help/plugin'>;
}
declare module 'tinymce/plugins/help/plugin.min.js' {
  declare module.exports: $Exports<'tinymce/plugins/help/plugin.min'>;
}
declare module 'tinymce/plugins/image/index' {
  declare module.exports: $Exports<'tinymce/plugins/image'>;
}
declare module 'tinymce/plugins/image/index.js' {
  declare module.exports: $Exports<'tinymce/plugins/image'>;
}
declare module 'tinymce/plugins/image/plugin.js' {
  declare module.exports: $Exports<'tinymce/plugins/image/plugin'>;
}
declare module 'tinymce/plugins/image/plugin.min.js' {
  declare module.exports: $Exports<'tinymce/plugins/image/plugin.min'>;
}
declare module 'tinymce/plugins/importcss/index' {
  declare module.exports: $Exports<'tinymce/plugins/importcss'>;
}
declare module 'tinymce/plugins/importcss/index.js' {
  declare module.exports: $Exports<'tinymce/plugins/importcss'>;
}
declare module 'tinymce/plugins/importcss/plugin.js' {
  declare module.exports: $Exports<'tinymce/plugins/importcss/plugin'>;
}
declare module 'tinymce/plugins/importcss/plugin.min.js' {
  declare module.exports: $Exports<'tinymce/plugins/importcss/plugin.min'>;
}
declare module 'tinymce/plugins/insertdatetime/index' {
  declare module.exports: $Exports<'tinymce/plugins/insertdatetime'>;
}
declare module 'tinymce/plugins/insertdatetime/index.js' {
  declare module.exports: $Exports<'tinymce/plugins/insertdatetime'>;
}
declare module 'tinymce/plugins/insertdatetime/plugin.js' {
  declare module.exports: $Exports<'tinymce/plugins/insertdatetime/plugin'>;
}
declare module 'tinymce/plugins/insertdatetime/plugin.min.js' {
  declare module.exports: $Exports<'tinymce/plugins/insertdatetime/plugin.min'>;
}
declare module 'tinymce/plugins/link/index' {
  declare module.exports: $Exports<'tinymce/plugins/link'>;
}
declare module 'tinymce/plugins/link/index.js' {
  declare module.exports: $Exports<'tinymce/plugins/link'>;
}
declare module 'tinymce/plugins/link/plugin.js' {
  declare module.exports: $Exports<'tinymce/plugins/link/plugin'>;
}
declare module 'tinymce/plugins/link/plugin.min.js' {
  declare module.exports: $Exports<'tinymce/plugins/link/plugin.min'>;
}
declare module 'tinymce/plugins/lists/index' {
  declare module.exports: $Exports<'tinymce/plugins/lists'>;
}
declare module 'tinymce/plugins/lists/index.js' {
  declare module.exports: $Exports<'tinymce/plugins/lists'>;
}
declare module 'tinymce/plugins/lists/plugin.js' {
  declare module.exports: $Exports<'tinymce/plugins/lists/plugin'>;
}
declare module 'tinymce/plugins/lists/plugin.min.js' {
  declare module.exports: $Exports<'tinymce/plugins/lists/plugin.min'>;
}
declare module 'tinymce/plugins/media/index' {
  declare module.exports: $Exports<'tinymce/plugins/media'>;
}
declare module 'tinymce/plugins/media/index.js' {
  declare module.exports: $Exports<'tinymce/plugins/media'>;
}
declare module 'tinymce/plugins/media/plugin.js' {
  declare module.exports: $Exports<'tinymce/plugins/media/plugin'>;
}
declare module 'tinymce/plugins/media/plugin.min.js' {
  declare module.exports: $Exports<'tinymce/plugins/media/plugin.min'>;
}
declare module 'tinymce/plugins/nonbreaking/index' {
  declare module.exports: $Exports<'tinymce/plugins/nonbreaking'>;
}
declare module 'tinymce/plugins/nonbreaking/index.js' {
  declare module.exports: $Exports<'tinymce/plugins/nonbreaking'>;
}
declare module 'tinymce/plugins/nonbreaking/plugin.js' {
  declare module.exports: $Exports<'tinymce/plugins/nonbreaking/plugin'>;
}
declare module 'tinymce/plugins/nonbreaking/plugin.min.js' {
  declare module.exports: $Exports<'tinymce/plugins/nonbreaking/plugin.min'>;
}
declare module 'tinymce/plugins/pagebreak/index' {
  declare module.exports: $Exports<'tinymce/plugins/pagebreak'>;
}
declare module 'tinymce/plugins/pagebreak/index.js' {
  declare module.exports: $Exports<'tinymce/plugins/pagebreak'>;
}
declare module 'tinymce/plugins/pagebreak/plugin.js' {
  declare module.exports: $Exports<'tinymce/plugins/pagebreak/plugin'>;
}
declare module 'tinymce/plugins/pagebreak/plugin.min.js' {
  declare module.exports: $Exports<'tinymce/plugins/pagebreak/plugin.min'>;
}
declare module 'tinymce/plugins/preview/index' {
  declare module.exports: $Exports<'tinymce/plugins/preview'>;
}
declare module 'tinymce/plugins/preview/index.js' {
  declare module.exports: $Exports<'tinymce/plugins/preview'>;
}
declare module 'tinymce/plugins/preview/plugin.js' {
  declare module.exports: $Exports<'tinymce/plugins/preview/plugin'>;
}
declare module 'tinymce/plugins/preview/plugin.min.js' {
  declare module.exports: $Exports<'tinymce/plugins/preview/plugin.min'>;
}
declare module 'tinymce/plugins/quickbars/index' {
  declare module.exports: $Exports<'tinymce/plugins/quickbars'>;
}
declare module 'tinymce/plugins/quickbars/index.js' {
  declare module.exports: $Exports<'tinymce/plugins/quickbars'>;
}
declare module 'tinymce/plugins/quickbars/plugin.js' {
  declare module.exports: $Exports<'tinymce/plugins/quickbars/plugin'>;
}
declare module 'tinymce/plugins/quickbars/plugin.min.js' {
  declare module.exports: $Exports<'tinymce/plugins/quickbars/plugin.min'>;
}
declare module 'tinymce/plugins/save/index' {
  declare module.exports: $Exports<'tinymce/plugins/save'>;
}
declare module 'tinymce/plugins/save/index.js' {
  declare module.exports: $Exports<'tinymce/plugins/save'>;
}
declare module 'tinymce/plugins/save/plugin.js' {
  declare module.exports: $Exports<'tinymce/plugins/save/plugin'>;
}
declare module 'tinymce/plugins/save/plugin.min.js' {
  declare module.exports: $Exports<'tinymce/plugins/save/plugin.min'>;
}
declare module 'tinymce/plugins/searchreplace/index' {
  declare module.exports: $Exports<'tinymce/plugins/searchreplace'>;
}
declare module 'tinymce/plugins/searchreplace/index.js' {
  declare module.exports: $Exports<'tinymce/plugins/searchreplace'>;
}
declare module 'tinymce/plugins/searchreplace/plugin.js' {
  declare module.exports: $Exports<'tinymce/plugins/searchreplace/plugin'>;
}
declare module 'tinymce/plugins/searchreplace/plugin.min.js' {
  declare module.exports: $Exports<'tinymce/plugins/searchreplace/plugin.min'>;
}
declare module 'tinymce/plugins/table/index' {
  declare module.exports: $Exports<'tinymce/plugins/table'>;
}
declare module 'tinymce/plugins/table/index.js' {
  declare module.exports: $Exports<'tinymce/plugins/table'>;
}
declare module 'tinymce/plugins/table/plugin.js' {
  declare module.exports: $Exports<'tinymce/plugins/table/plugin'>;
}
declare module 'tinymce/plugins/table/plugin.min.js' {
  declare module.exports: $Exports<'tinymce/plugins/table/plugin.min'>;
}
declare module 'tinymce/plugins/template/index' {
  declare module.exports: $Exports<'tinymce/plugins/template'>;
}
declare module 'tinymce/plugins/template/index.js' {
  declare module.exports: $Exports<'tinymce/plugins/template'>;
}
declare module 'tinymce/plugins/template/plugin.js' {
  declare module.exports: $Exports<'tinymce/plugins/template/plugin'>;
}
declare module 'tinymce/plugins/template/plugin.min.js' {
  declare module.exports: $Exports<'tinymce/plugins/template/plugin.min'>;
}
declare module 'tinymce/plugins/visualblocks/index' {
  declare module.exports: $Exports<'tinymce/plugins/visualblocks'>;
}
declare module 'tinymce/plugins/visualblocks/index.js' {
  declare module.exports: $Exports<'tinymce/plugins/visualblocks'>;
}
declare module 'tinymce/plugins/visualblocks/plugin.js' {
  declare module.exports: $Exports<'tinymce/plugins/visualblocks/plugin'>;
}
declare module 'tinymce/plugins/visualblocks/plugin.min.js' {
  declare module.exports: $Exports<'tinymce/plugins/visualblocks/plugin.min'>;
}
declare module 'tinymce/plugins/visualchars/index' {
  declare module.exports: $Exports<'tinymce/plugins/visualchars'>;
}
declare module 'tinymce/plugins/visualchars/index.js' {
  declare module.exports: $Exports<'tinymce/plugins/visualchars'>;
}
declare module 'tinymce/plugins/visualchars/plugin.js' {
  declare module.exports: $Exports<'tinymce/plugins/visualchars/plugin'>;
}
declare module 'tinymce/plugins/visualchars/plugin.min.js' {
  declare module.exports: $Exports<'tinymce/plugins/visualchars/plugin.min'>;
}
declare module 'tinymce/plugins/wordcount/index' {
  declare module.exports: $Exports<'tinymce/plugins/wordcount'>;
}
declare module 'tinymce/plugins/wordcount/index.js' {
  declare module.exports: $Exports<'tinymce/plugins/wordcount'>;
}
declare module 'tinymce/plugins/wordcount/plugin.js' {
  declare module.exports: $Exports<'tinymce/plugins/wordcount/plugin'>;
}
declare module 'tinymce/plugins/wordcount/plugin.min.js' {
  declare module.exports: $Exports<'tinymce/plugins/wordcount/plugin.min'>;
}
declare module 'tinymce/themes/silver/index' {
  declare module.exports: $Exports<'tinymce/themes/silver'>;
}
declare module 'tinymce/themes/silver/index.js' {
  declare module.exports: $Exports<'tinymce/themes/silver'>;
}
declare module 'tinymce/themes/silver/theme.js' {
  declare module.exports: $Exports<'tinymce/themes/silver/theme'>;
}
declare module 'tinymce/themes/silver/theme.min.js' {
  declare module.exports: $Exports<'tinymce/themes/silver/theme.min'>;
}
declare module 'tinymce/tinymce.js' {
  declare module.exports: $Exports<'tinymce/tinymce'>;
}
declare module 'tinymce/tinymce.min.js' {
  declare module.exports: $Exports<'tinymce/tinymce.min'>;
}
