// flow-typed signature: cc102dc406c551d694c5894477ae3063
// flow-typed version: <<STUB>>/tss-react_v=4.6.0/flow_v0.206.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tss-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tss-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tss-react/compat' {
  declare module.exports: any;
}

declare module 'tss-react/cssAndCx' {
  declare module.exports: any;
}

declare module 'tss-react/dsfr' {
  declare module.exports: any;
}

declare module 'tss-react/esm/compat' {
  declare module.exports: any;
}

declare module 'tss-react/esm/cssAndCx' {
  declare module.exports: any;
}

declare module 'tss-react/esm/dsfr' {
  declare module.exports: any;
}

declare module 'tss-react/esm/GlobalStyles' {
  declare module.exports: any;
}

declare module 'tss-react/esm' {
  declare module.exports: any;
}

declare module 'tss-react/esm/makeStyles' {
  declare module.exports: any;
}

declare module 'tss-react/esm/mergeClasses' {
  declare module.exports: any;
}

declare module 'tss-react/esm/mui-compat' {
  declare module.exports: any;
}

declare module 'tss-react/esm/mui' {
  declare module.exports: any;
}

declare module 'tss-react/esm/next/appDir' {
  declare module.exports: any;
}

declare module 'tss-react/esm/next' {
  declare module.exports: any;
}

declare module 'tss-react/esm/next/pagesDir' {
  declare module.exports: any;
}

declare module 'tss-react/esm/nextJs' {
  declare module.exports: any;
}

declare module 'tss-react/esm/tools/assert' {
  declare module.exports: any;
}

declare module 'tss-react/esm/tools/capitalize' {
  declare module.exports: any;
}

declare module 'tss-react/esm/tools/classnames' {
  declare module.exports: any;
}

declare module 'tss-react/esm/tools/getDependencyArrayRef' {
  declare module.exports: any;
}

declare module 'tss-react/esm/tools/objectKeys' {
  declare module.exports: any;
}

declare module 'tss-react/esm/tools/polyfills/Object.fromEntries' {
  declare module.exports: any;
}

declare module 'tss-react/esm/tools/ReactComponent' {
  declare module.exports: any;
}

declare module 'tss-react/esm/tools/typeGuard' {
  declare module.exports: any;
}

declare module 'tss-react/esm/tools/useGuaranteedMemo' {
  declare module.exports: any;
}

declare module 'tss-react/esm/types' {
  declare module.exports: any;
}

declare module 'tss-react/esm/withStyles_compat' {
  declare module.exports: any;
}

declare module 'tss-react/esm/withStyles' {
  declare module.exports: any;
}

declare module 'tss-react/GlobalStyles' {
  declare module.exports: any;
}

declare module 'tss-react/makeStyles' {
  declare module.exports: any;
}

declare module 'tss-react/mergeClasses' {
  declare module.exports: any;
}

declare module 'tss-react/mui-compat' {
  declare module.exports: any;
}

declare module 'tss-react/mui' {
  declare module.exports: any;
}

declare module 'tss-react/next/appDir' {
  declare module.exports: any;
}

declare module 'tss-react/next' {
  declare module.exports: any;
}

declare module 'tss-react/next/pagesDir' {
  declare module.exports: any;
}

declare module 'tss-react/nextJs' {
  declare module.exports: any;
}

declare module 'tss-react/tools/assert' {
  declare module.exports: any;
}

declare module 'tss-react/tools/capitalize' {
  declare module.exports: any;
}

declare module 'tss-react/tools/classnames' {
  declare module.exports: any;
}

declare module 'tss-react/tools/getDependencyArrayRef' {
  declare module.exports: any;
}

declare module 'tss-react/tools/objectKeys' {
  declare module.exports: any;
}

declare module 'tss-react/tools/polyfills/Object.fromEntries' {
  declare module.exports: any;
}

declare module 'tss-react/tools/ReactComponent' {
  declare module.exports: any;
}

declare module 'tss-react/tools/typeGuard' {
  declare module.exports: any;
}

declare module 'tss-react/tools/useGuaranteedMemo' {
  declare module.exports: any;
}

declare module 'tss-react/types' {
  declare module.exports: any;
}

declare module 'tss-react/withStyles_compat' {
  declare module.exports: any;
}

declare module 'tss-react/withStyles' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tss-react/compat.js' {
  declare module.exports: $Exports<'tss-react/compat'>;
}
declare module 'tss-react/cssAndCx.js' {
  declare module.exports: $Exports<'tss-react/cssAndCx'>;
}
declare module 'tss-react/dsfr.js' {
  declare module.exports: $Exports<'tss-react/dsfr'>;
}
declare module 'tss-react/esm/compat.js' {
  declare module.exports: $Exports<'tss-react/esm/compat'>;
}
declare module 'tss-react/esm/cssAndCx.js' {
  declare module.exports: $Exports<'tss-react/esm/cssAndCx'>;
}
declare module 'tss-react/esm/dsfr.js' {
  declare module.exports: $Exports<'tss-react/esm/dsfr'>;
}
declare module 'tss-react/esm/GlobalStyles.js' {
  declare module.exports: $Exports<'tss-react/esm/GlobalStyles'>;
}
declare module 'tss-react/esm/index' {
  declare module.exports: $Exports<'tss-react/esm'>;
}
declare module 'tss-react/esm/index.js' {
  declare module.exports: $Exports<'tss-react/esm'>;
}
declare module 'tss-react/esm/makeStyles.js' {
  declare module.exports: $Exports<'tss-react/esm/makeStyles'>;
}
declare module 'tss-react/esm/mergeClasses.js' {
  declare module.exports: $Exports<'tss-react/esm/mergeClasses'>;
}
declare module 'tss-react/esm/mui-compat.js' {
  declare module.exports: $Exports<'tss-react/esm/mui-compat'>;
}
declare module 'tss-react/esm/mui.js' {
  declare module.exports: $Exports<'tss-react/esm/mui'>;
}
declare module 'tss-react/esm/next/appDir.js' {
  declare module.exports: $Exports<'tss-react/esm/next/appDir'>;
}
declare module 'tss-react/esm/next/index' {
  declare module.exports: $Exports<'tss-react/esm/next'>;
}
declare module 'tss-react/esm/next/index.js' {
  declare module.exports: $Exports<'tss-react/esm/next'>;
}
declare module 'tss-react/esm/next/pagesDir.js' {
  declare module.exports: $Exports<'tss-react/esm/next/pagesDir'>;
}
declare module 'tss-react/esm/nextJs.js' {
  declare module.exports: $Exports<'tss-react/esm/nextJs'>;
}
declare module 'tss-react/esm/tools/assert.js' {
  declare module.exports: $Exports<'tss-react/esm/tools/assert'>;
}
declare module 'tss-react/esm/tools/capitalize.js' {
  declare module.exports: $Exports<'tss-react/esm/tools/capitalize'>;
}
declare module 'tss-react/esm/tools/classnames.js' {
  declare module.exports: $Exports<'tss-react/esm/tools/classnames'>;
}
declare module 'tss-react/esm/tools/getDependencyArrayRef.js' {
  declare module.exports: $Exports<'tss-react/esm/tools/getDependencyArrayRef'>;
}
declare module 'tss-react/esm/tools/objectKeys.js' {
  declare module.exports: $Exports<'tss-react/esm/tools/objectKeys'>;
}
declare module 'tss-react/esm/tools/polyfills/Object.fromEntries.js' {
  declare module.exports: $Exports<'tss-react/esm/tools/polyfills/Object.fromEntries'>;
}
declare module 'tss-react/esm/tools/ReactComponent.js' {
  declare module.exports: $Exports<'tss-react/esm/tools/ReactComponent'>;
}
declare module 'tss-react/esm/tools/typeGuard.js' {
  declare module.exports: $Exports<'tss-react/esm/tools/typeGuard'>;
}
declare module 'tss-react/esm/tools/useGuaranteedMemo.js' {
  declare module.exports: $Exports<'tss-react/esm/tools/useGuaranteedMemo'>;
}
declare module 'tss-react/esm/types.js' {
  declare module.exports: $Exports<'tss-react/esm/types'>;
}
declare module 'tss-react/esm/withStyles_compat.js' {
  declare module.exports: $Exports<'tss-react/esm/withStyles_compat'>;
}
declare module 'tss-react/esm/withStyles.js' {
  declare module.exports: $Exports<'tss-react/esm/withStyles'>;
}
declare module 'tss-react/GlobalStyles.js' {
  declare module.exports: $Exports<'tss-react/GlobalStyles'>;
}
declare module 'tss-react/index' {
  declare module.exports: $Exports<'tss-react'>;
}
declare module 'tss-react/index.js' {
  declare module.exports: $Exports<'tss-react'>;
}
declare module 'tss-react/makeStyles.js' {
  declare module.exports: $Exports<'tss-react/makeStyles'>;
}
declare module 'tss-react/mergeClasses.js' {
  declare module.exports: $Exports<'tss-react/mergeClasses'>;
}
declare module 'tss-react/mui-compat.js' {
  declare module.exports: $Exports<'tss-react/mui-compat'>;
}
declare module 'tss-react/mui.js' {
  declare module.exports: $Exports<'tss-react/mui'>;
}
declare module 'tss-react/next/appDir.js' {
  declare module.exports: $Exports<'tss-react/next/appDir'>;
}
declare module 'tss-react/next/index' {
  declare module.exports: $Exports<'tss-react/next'>;
}
declare module 'tss-react/next/index.js' {
  declare module.exports: $Exports<'tss-react/next'>;
}
declare module 'tss-react/next/pagesDir.js' {
  declare module.exports: $Exports<'tss-react/next/pagesDir'>;
}
declare module 'tss-react/nextJs.js' {
  declare module.exports: $Exports<'tss-react/nextJs'>;
}
declare module 'tss-react/tools/assert.js' {
  declare module.exports: $Exports<'tss-react/tools/assert'>;
}
declare module 'tss-react/tools/capitalize.js' {
  declare module.exports: $Exports<'tss-react/tools/capitalize'>;
}
declare module 'tss-react/tools/classnames.js' {
  declare module.exports: $Exports<'tss-react/tools/classnames'>;
}
declare module 'tss-react/tools/getDependencyArrayRef.js' {
  declare module.exports: $Exports<'tss-react/tools/getDependencyArrayRef'>;
}
declare module 'tss-react/tools/objectKeys.js' {
  declare module.exports: $Exports<'tss-react/tools/objectKeys'>;
}
declare module 'tss-react/tools/polyfills/Object.fromEntries.js' {
  declare module.exports: $Exports<'tss-react/tools/polyfills/Object.fromEntries'>;
}
declare module 'tss-react/tools/ReactComponent.js' {
  declare module.exports: $Exports<'tss-react/tools/ReactComponent'>;
}
declare module 'tss-react/tools/typeGuard.js' {
  declare module.exports: $Exports<'tss-react/tools/typeGuard'>;
}
declare module 'tss-react/tools/useGuaranteedMemo.js' {
  declare module.exports: $Exports<'tss-react/tools/useGuaranteedMemo'>;
}
declare module 'tss-react/types.js' {
  declare module.exports: $Exports<'tss-react/types'>;
}
declare module 'tss-react/withStyles_compat.js' {
  declare module.exports: $Exports<'tss-react/withStyles_compat'>;
}
declare module 'tss-react/withStyles.js' {
  declare module.exports: $Exports<'tss-react/withStyles'>;
}
