server.port=8080
server.tomcat.max-part-count=2
server.tomcat.max-http-form-post-size=201MB
server.tomcat.max-swallow-size=201MB
spring.servlet.multipart.file-size-threshold=0
spring.servlet.multipart.location=/work
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=201MB
spring.mvc.async.request-timeout=185s
server.error.include-message=never
server.error.include-stacktrace=never
management.endpoints.web.exposure.include=health
management.endpoint.health.probes.enabled=true

converter.office-home=/usr/lib/libreoffice
converter.working-directory=/work/rspace-conversion
converter.conversion-timeout=180s
converter.connection-request-timeout=2s
converter.connect-timeout=5s
converter.response-timeout=185s
converter.max-concurrent-office-conversions=2
converter.max-output-bytes=314572800
converter.sandbox-executable=/usr/bin/bwrap
