import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { expect } from "@playwright/test";
import { createDynamicUser } from "@/__tests__/e2e/createDynamicUser";
import { dynamicUserTest as test } from "@/__tests__/e2e/fixtures/dynamicUser";
import { test as sessionTest } from "@/__tests__/e2e/fixtures/flows";
import { alphaNumericUnique, uniqueName } from "@/__tests__/e2e/testData";

const currentDir = dirname(fileURLToPath(import.meta.url));
const ONTOLOGY_CSV_FIXTURE = resolve(currentDir, "fixtures/ontology_import.csv");

const ONTOLOGY_FILE_NAME = "YOUR_AUTOGENERATED_TAGS.ontology";
const ONTOLOGY_FIELD_NAME = "Ontologies for tag creation";
const ENFORCED_MESSAGE = "Ontologies are enforced, tag values must come from ontology files shared with a group";

test.describe("Tagging and Ontology", () => {
  test("As a user, tags I add to a document appear in my account's auto-generated ontology file, are shown on the document, and can be removed", async ({
    pageWorkspace,
    pageDocument,
  }) => {
    const docName = uniqueName("e2e-ont-doc");
    const tag1 = uniqueName("e2e-ont-tag1");
    const tag2 = uniqueName("e2e-ont-tag2");
    const tag3 = uniqueName("e2e-ont-tag3");
    const tag4 = "myTagWithAnApostrophe's";
    const tags = [tag1, tag2, tag3, tag4];

    await test.step("Given I create a basic document and tag it, including a tag with an apostrophe", async () => {
      await pageWorkspace.open();
      const editor = await pageWorkspace.createBasicDocument();
      await editor.header.rename(docName);
      for (const tag of tags) {
        await editor.header.addTag(tag);
      }
      await editor.editToolbar.saveAndClose();
    });

    await test.step("Then the account's auto-generated ontology file contains all the tags", async () => {
      await expect
        .poll(async () => {
          await pageWorkspace.open();
          await pageWorkspace.searchBar.search(ONTOLOGY_FILE_NAME);
          await pageWorkspace.table.openRecord(ONTOLOGY_FILE_NAME);
          await pageDocument.isLoaded();
          return pageDocument.getOntologyTags();
        })
        .toEqual(expect.arrayContaining(tags));
    });

    await test.step("And the document itself shows all the tags", async () => {
      await pageWorkspace.open();
      await pageWorkspace.searchBar.search(docName);
      await pageWorkspace.table.openRecord(docName);
      await pageDocument.isLoaded();
      const docTags = await pageDocument.header.getTags();
      for (const tag of tags) {
        expect(docTags).toContain(tag);
      }
    });

    await test.step("When I remove all the tags", async () => {
      for (const tag of tags) {
        await pageDocument.header.removeTag(tag);
      }
    });

    await test.step("Then no tags remain, even after reloading", async () => {
      await pageDocument.reload();
      expect(await pageDocument.header.getTags()).toEqual([]);
    });

    await test.step("When I try to add tags containing forbidden characters", async () => {
      for (const forbidden of ["<tag1>", "tag/2", "tag\\3"]) {
        await pageDocument.header.addForbiddenTag(forbidden);
        await pageDocument.reload();
      }
    });

    await test.step("Then none of the forbidden-character tags were added", async () => {
      expect(await pageDocument.header.getTags()).toEqual([]);
    });
  });

  test("As a user, tags I define in an ontology document appear as tag suggestions when tagging another document", async ({
    pageWorkspace,
    pageDocument,
  }) => {
    const tagLines = ["a,b,c", "key=d,e,f", "key2=a"];
    const expectedSuggestions = ["a", "b", "c", "key2=a", "key=d", "key=e", "key=f"];

    await test.step("Given I create an ontology document defining several tags, including a key= group", async () => {
      await pageWorkspace.open();
      await pageWorkspace.toolbar.createMenu.createFromCustomForm("RSpace Tags from Ontologies");
      await pageDocument.isLoaded();
      const field = await pageDocument.editField(ONTOLOGY_FIELD_NAME);
      await field.typeLines(tagLines);
      await field.save();
    });

    const editor =
      await test.step("Then those tags, with key= groups expanded, appear as suggestions when tagging another document", async () => {
        await pageWorkspace.open();
        const created = await pageWorkspace.createBasicDocument();
        await expect
          .poll(() => created.header.getSuggestedTags(), { timeout: 30_000, intervals: [3_000] })
          .toEqual(expect.arrayContaining(expectedSuggestions));
        return created;
      });

    await test.step("When I select one of the suggestions instead of typing it, it's applied as a real tag", async () => {
      await editor.header.selectSuggestedTag("key=d");
      await editor.saveAndView();
      await pageWorkspace.openDocument(editor.getId());
      expect(await pageDocument.header.getTags()).toContain("key=d");
    });
  });

  test("As a user, I can import an ontology CSV file, and the resulting document is signed", async ({
    pageMyRSpace,
    pageWorkspace,
    pageDocument,
  }) => {
    const ontologyName = uniqueName("e2e-ont-csv");
    const ontologyVersion = "v1";
    const importedFileName = `${ontologyName}_version_${ontologyVersion}.ontology`;

    await test.step("When I import an ontology CSV file, setting the data and URI columns", async () => {
      await pageMyRSpace.open();
      const exportImport = await pageMyRSpace.openExportImport();
      await exportImport.importOntologyCsv(ONTOLOGY_CSV_FIXTURE, {
        dataColumn: "2",
        uriColumn: "1",
        name: ontologyName,
        version: ontologyVersion,
      });
    });

    await test.step("Then a new ontology document is created, named with the ontology name and version, and it is signed", async () => {
      await pageWorkspace.open();
      await pageWorkspace.searchBar.search(importedFileName);
      await pageWorkspace.table.openRecord(importedFileName);
      await pageDocument.isLoaded();
      await expect(pageDocument.signedStatus.first()).toBeVisible();
    });

    await test.step("And it preserves every term's URI and ontology metadata, excluding the CSV header", async () => {
      expect(await pageDocument.getImportedOntology()).toEqual({
        name: ontologyName,
        version: ontologyVersion,
        terms: [
          { label: "e2eCsvTagAlpha", uri: "http://example.org/ont/0001" },
          { label: "e2eCsvTagBeta", uri: "http://example.org/ont/0002" },
          { label: "e2eCsvTagGamma", uri: "http://example.org/ont/0003" },
        ],
      });
    });
  });

  sessionTest(
    "As a user, an ontology document I share individually is read-only for the recipient, but editable when shared with a group at Edit permission, and its tags are suggested to both",
    async ({ flowDocumentSession, clientSysadmin }) => {
      // Three authenticated actors and both suggestion/edit journeys take about a minute.
      sessionTest.setTimeout(90_000);
      const groupName = uniqueName("e2e-ont-share-group");
      const visibilityGroupName = uniqueName("e2e-ont-visibility-group");
      const ontologyDocName = uniqueName("e2e-ont-share-doc");
      const tag1 = uniqueName("e2e-ont-share-tag1");
      const tag2 = uniqueName("e2e-ont-share-tag2");
      const editedTag = uniqueName("e2e-ont-share-edited-tag");

      const { ownerUser, readUser, editUser } =
        await test.step("Given an owner, a read-only recipient, and a grouped edit recipient exist", async () => {
          const ownerUser = await createDynamicUser(clientSysadmin, "ROLE_PI", "e2eOntOwner", "OntOwner");
          const readUser = await createDynamicUser(clientSysadmin, "ROLE_USER", "e2eOntRead", "OntRead");
          const editUser = await createDynamicUser(clientSysadmin, "ROLE_USER", "e2eOntEdit", "OntEdit");
          await clientSysadmin.createGroup({
            displayName: groupName,
            type: "LAB_GROUP",
            users: [
              { username: ownerUser.username, roleInGroup: "PI" },
              { username: editUser.username, roleInGroup: "DEFAULT" },
            ],
          });

          await clientSysadmin.createGroup({
            displayName: visibilityGroupName,
            type: "LAB_GROUP",
            users: [
              { username: ownerUser.username, roleInGroup: "PI" },
              { username: readUser.username, roleInGroup: "DEFAULT" },
            ],
          });
          return { ownerUser, readUser, editUser };
        });

      const owner = await flowDocumentSession(ownerUser);

      const ontologyId = await test.step("When the owner creates an ontology document with two tags", async () => {
        await owner.workspace.toolbar.createMenu.createFromCustomForm("RSpace Tags from Ontologies");
        await owner.document.isLoaded();
        await owner.document.header.rename(ontologyDocName);
        const field = await owner.document.editField(ONTOLOGY_FIELD_NAME);
        await field.typeLines([tag1, tag2]);
        await field.saveAndFinishEditing();
        return owner.document.getId();
      });

      await test.step("And shares it individually at Read, and with the group at Edit", async () => {
        await owner.workspace.searchFor(ontologyDocName);
        await owner.workspace.table.selectRecord(ontologyDocName);
        const shareDialog = await owner.workspace.selectionBar.share();
        await shareDialog.addRecipient(readUser.username);
        await shareDialog.setPermission(readUser.username, "READ");
        await shareDialog.addRecipient(groupName);
        await shareDialog.setPermission(groupName, "EDIT");
        await shareDialog.save();
      });

      const read = await flowDocumentSession(readUser);

      await test.step("Then the read-only recipient sees the shared tags suggested on their own documents", async () => {
        const editor = await read.workspace.createBasicDocument();
        await expect.poll(() => editor.header.getSuggestedTags()).toEqual(expect.arrayContaining([tag1, tag2]));
      });

      await test.step("And they open it from Shared > IndividualShareItems, where it's read-only for them", async () => {
        await read.workspace.browseToIndividualShareFolder(ownerUser.username, readUser.username);
        await read.workspace.table.openRecord(ontologyDocName);
        await read.document.isLoaded();
        expect(read.document.getId()).toBe(ontologyId);
        expect(await read.document.isReadOnly()).toBe(true);
      });

      const edit = await flowDocumentSession(editUser);

      await test.step("Then the grouped edit recipient also sees the shared tags suggested", async () => {
        const editor = await edit.workspace.createBasicDocument();
        await expect
          .poll(() => editor.header.getSuggestedTags(), { timeout: 30_000, intervals: [3_000] })
          .toEqual(expect.arrayContaining([tag1, tag2]));
      });

      await test.step("When the grouped edit recipient opens it from Shared > LabGroups, changes a tag, and saves it", async () => {
        await edit.workspace.browseToLabGroupSharedFolder(groupName);
        await edit.workspace.table.openRecord(ontologyDocName);
        await edit.document.isLoaded();
        expect(edit.document.getId()).toBe(ontologyId);
        const field = await edit.document.editField(ONTOLOGY_FIELD_NAME);
        await field.fill("");
        await field.typeLines([tag1, editedTag]);
        await field.saveAndFinishEditing();
      });

      await test.step("Then the owner sees the saved change when reopening the ontology", async () => {
        const document = await owner.workspace.openDocument(ontologyId);
        expect(await document.getOntologyTags()).toEqual([tag1, editedTag]);
      });
    },
  );

  test("As a user, I can tag a notebook, folder, and document individually and via bulk multi-select, and search by tag", async ({
    pageWorkspace,
    clientFolders,
    clientDocuments,
  }) => {
    const notebookName = uniqueName("e2e-tag-nb");
    const folderName = uniqueName("e2e-tag-folder");
    const docName = uniqueName("e2e-tag-doc");
    const tagShared = uniqueName("e2e-tag-shared");
    const tagPicture = uniqueName("e2e-tag-picture");
    // ContentInitializerForDevRunManager (run/dev profiles only) tags each new user's example
    // "Full Notebook" with these, so RSpace suggests them.
    const existingTags = ["defaultFullNotebook", "defaultContent"];
    const sorted = (tags: string[]) => [...tags].sort();
    const expectTags = async (name: string, expected: string[]) => {
      await pageWorkspace.open();
      const info = await pageWorkspace.table.openInfoFor(name);
      expect(sorted(await info.getTags()), `Tags on ${name}`).toEqual(sorted(expected));
      await info.close();
    };

    await test.step("Given a notebook, a folder, and a document exist", async () => {
      await clientFolders.create({ name: notebookName, notebook: true });
      const folder = await clientFolders.create({ name: folderName });
      await clientDocuments.create({ name: docName, parentFolderId: folder.parentFolderId });
    });

    await test.step("When I tag the notebook by picking two existing tags from the suggestions", async () => {
      await pageWorkspace.open();
      await pageWorkspace.table.selectRecord(notebookName);
      const dialog = await pageWorkspace.selectionBar.addRemoveTags();
      for (const tag of existingTags) {
        await dialog.selectSuggestedTag(tag);
      }
      await dialog.save();
    });

    await test.step("Then Record Info shows exactly those two tags on the notebook", async () => {
      await expectTags(notebookName, existingTags);
    });

    await test.step("And Add/Remove Tags is available as an action for the notebook", async () => {
      await pageWorkspace.open();
      await pageWorkspace.table.selectRecord(notebookName);
      expect(await pageWorkspace.selectionBar.isActionVisible("Add/Remove Tags")).toBe(true);
    });

    await test.step("When I add a new free-text tag and remove one of the original tags", async () => {
      const dialog = await pageWorkspace.selectionBar.addRemoveTags();
      await dialog.addTag(tagPicture);
      await dialog.removeTag(existingTags[1]);
      await dialog.save();
    });

    await test.step("Then Record Info shows exactly the remaining and the new tag", async () => {
      await expectTags(notebookName, [existingTags[0], tagPicture]);
    });

    await test.step("When I select the notebook, folder, and document together", async () => {
      await pageWorkspace.open();
      await pageWorkspace.pagination.setItemsPerPage(50);
      await pageWorkspace.table.selectRecords(notebookName, folderName, docName);
    });

    await test.step("Then Add/Remove Tags shows no common tags across the selection, and adding one applies it to all three", async () => {
      const dialog = await pageWorkspace.selectionBar.addRemoveTags();
      await dialog.addTag(tagShared);
      // Common tags render as soon as getTagsForRecords returns, long before the added chip appears.
      await expect.poll(() => dialog.getTags()).toEqual([tagShared]);
      await dialog.save();
    });

    await test.step("Then each item shows exactly its own tags plus the shared one", async () => {
      await expectTags(notebookName, [existingTags[0], tagPicture, tagShared]);
      await expectTags(folderName, [tagShared]);
      await expectTags(docName, [tagShared]);
    });

    await test.step("And searching by that tag finds all three items", async () => {
      await pageWorkspace.open();
      await pageWorkspace.searchBar.openAdvanced();
      await pageWorkspace.searchBar.addRow();
      await pageWorkspace.searchBar.setRowType(0, "Tag(s)");
      await pageWorkspace.searchBar.setRowTag(0, tagShared);
      await pageWorkspace.searchBar.submitAdvanced();
      for (const name of [notebookName, folderName, docName]) {
        await expect(pageWorkspace.table.row(name)).toBeVisible();
      }
    });
  });

  test("As a PI, enforcing ontologies blocks free-text tags for group members, and sharing an ontology file with the group allows its tags through", async ({
    flowDocumentSession,
    appUser,
    pageWorkspace,
    pageDocument,
    pageGroupView,
    clientSysadmin,
  }) => {
    test.setTimeout(120_000);
    const groupName = uniqueName("e2e-enforce-group");
    const ontologyDocName = uniqueName("e2e-enforce-ont-doc");
    const ontologyTag = alphaNumericUnique("e2eEnforceTag");

    const { groupId, memberUser } = await test.step("Given a PI and a grouped member exist", async () => {
      const memberUser = await createDynamicUser(clientSysadmin, "ROLE_USER", "e2eEnfMember", "EnfMember");
      const group = await clientSysadmin.createGroup({
        displayName: groupName,
        type: "LAB_GROUP",
        users: [
          { username: appUser.username, roleInGroup: "PI" },
          { username: memberUser.username, roleInGroup: "DEFAULT" },
        ],
      });
      return { groupId: group.id, memberUser };
    });

    await test.step("When the PI enables Enforce Ontologies for the group", async () => {
      await pageGroupView.open(groupId);
      await pageGroupView.toggleEnforceOntologies();
      expect(await pageGroupView.isOntologiesEnforced()).toBe(true);
    });

    const piDocName = uniqueName("e2e-enforce-pi-doc");
    await test.step("Then the PI is also blocked from free-text tags by their own policy", async () => {
      await pageWorkspace.open();
      const editor = await pageWorkspace.createBasicDocument();
      await editor.header.rename(piDocName);
      await editor.header.addForbiddenTag(ontologyTag);
      expect(await editor.header.tagInfoDialogText.innerText()).toBe(ENFORCED_MESSAGE);
      expect(await editor.header.getTags()).toEqual([]);
      await editor.editToolbar.saveAndClose();
    });

    const member = await flowDocumentSession(memberUser);

    const memberDoc = await test.step("Then the grouped member cannot add a free-text tag", async () => {
      await member.workspace.open();
      const editor = await member.workspace.createBasicDocument();
      await editor.header.addForbiddenTag(ontologyTag);
      expect(await editor.header.tagInfoDialogText.innerText()).toBe(ENFORCED_MESSAGE);
      expect(await editor.header.getTags()).toEqual([]);
      return editor;
    });

    await test.step("When the PI creates an ontology document defining that tag, and shares it with the group", async () => {
      await pageWorkspace.open();
      await pageWorkspace.toolbar.createMenu.createFromCustomForm("RSpace Tags from Ontologies");
      await pageDocument.isLoaded();
      await pageDocument.header.rename(ontologyDocName);
      const field = await pageDocument.editField(ONTOLOGY_FIELD_NAME);
      await field.typeLines([ontologyTag]);
      await field.save();

      await pageWorkspace.open();
      await pageWorkspace.searchBar.search(ontologyDocName);
      await pageWorkspace.table.selectRecord(ontologyDocName);
      const shareDialog = await pageWorkspace.selectionBar.share();
      await shareDialog.addRecipient(groupName);
      await shareDialog.setPermission(groupName, "EDIT");
      await shareDialog.save();
    });

    await test.step("Then the member can now add that ontology-derived tag", async () => {
      await member.document.reload();

      await expect
        .poll(() => memberDoc.header.getSuggestedTags(), { timeout: 30_000, intervals: [3_000] })
        .toContain(ontologyTag);
      await memberDoc.header.addTag(ontologyTag);
      await member.document.reload();
      expect(await memberDoc.header.getTags()).toContain(ontologyTag);
    });

    await test.step("And still cannot add an unrelated free-text tag", async () => {
      const otherTag = alphaNumericUnique("e2eEnforceOther");
      await memberDoc.header.addForbiddenTag(otherTag);
      expect(await memberDoc.header.tagInfoDialogText.innerText()).toBe(ENFORCED_MESSAGE);
    });

    await test.step("Then the PI can also add the ontology-derived tag, but still not an unrelated one", async () => {
      await pageWorkspace.open();
      await pageWorkspace.searchBar.search(piDocName);
      await pageWorkspace.table.openRecord(piDocName);
      await pageDocument.isLoaded();

      await expect
        .poll(() => pageDocument.header.getSuggestedTags(), { timeout: 30_000, intervals: [3_000] })
        .toContain(ontologyTag);
      await pageDocument.header.addTag(ontologyTag);
      await pageDocument.reload();
      expect(await pageDocument.header.getTags()).toContain(ontologyTag);

      const otherTag = alphaNumericUnique("e2eEnforceOtherPi");
      await pageDocument.header.addForbiddenTag(otherTag);
      expect(await pageDocument.header.tagInfoDialogText.innerText()).toBe(ENFORCED_MESSAGE);
    });
  });

  test("As a member of two groups, enforcement from either group applies, and only a group-level share (not an individual one) unblocks its tags", async ({
    flowDocumentSession,
    appUser,
    pageWorkspace,
    pageDocument,
    pageGroupView,
    clientSysadmin,
  }) => {
    test.setTimeout(150_000);
    const enforcingGroupName = uniqueName("e2e-multi-enforce-group");
    const otherGroupName = uniqueName("e2e-multi-other-group");
    const ontologyDocName = uniqueName("e2e-multi-enforce-doc");
    const ontologyTag = alphaNumericUnique("e2eMultiEnforceTag");

    const { enforcingGroupId, memberUser } =
      await test.step("Given a PI and a member who belong to two of the PI's groups, neither enforcing ontologies yet", async () => {
        const memberUser = await createDynamicUser(clientSysadmin, "ROLE_USER", "e2eMultiMember", "MultiMember");
        const enforcingGroup = await clientSysadmin.createGroup({
          displayName: enforcingGroupName,
          type: "LAB_GROUP",
          users: [
            { username: appUser.username, roleInGroup: "PI" },
            { username: memberUser.username, roleInGroup: "DEFAULT" },
          ],
        });
        await clientSysadmin.createGroup({
          displayName: otherGroupName,
          type: "LAB_GROUP",
          users: [
            { username: appUser.username, roleInGroup: "PI" },
            { username: memberUser.username, roleInGroup: "DEFAULT" },
          ],
        });
        return { enforcingGroupId: enforcingGroup.id, memberUser };
      });

    await test.step("When the PI enables Enforce Ontologies on only one of the two shared groups", async () => {
      await pageGroupView.open(enforcingGroupId);
      await pageGroupView.toggleEnforceOntologies();
      expect(await pageGroupView.isOntologiesEnforced()).toBe(true);
    });

    const member = await flowDocumentSession(memberUser);

    await test.step("Then the member is blocked from free-text tags, even via their other, non-enforcing group", async () => {
      await member.workspace.open();
      const editor = await member.workspace.createBasicDocument();
      await editor.header.addForbiddenTag(ontologyTag);
      expect(await editor.header.tagInfoDialogText.innerText()).toBe(ENFORCED_MESSAGE);
    });

    const editor = await test.step("Given the member has a document open to check suggestions on", async () => {
      await member.workspace.open();
      return member.workspace.createBasicDocument();
    });

    await test.step("When the PI creates an ontology document defining that tag and shares it with the member individually, at Edit", async () => {
      await pageWorkspace.open();
      await pageWorkspace.toolbar.createMenu.createFromCustomForm("RSpace Tags from Ontologies");
      await pageDocument.isLoaded();
      await pageDocument.header.rename(ontologyDocName);
      const field = await pageDocument.editField(ONTOLOGY_FIELD_NAME);
      await field.typeLines([ontologyTag]);
      await field.save();

      await pageWorkspace.open();
      await pageWorkspace.searchBar.search(ontologyDocName);
      await pageWorkspace.table.selectRecord(ontologyDocName);
      const shareDialog = await pageWorkspace.selectionBar.share();
      await shareDialog.addRecipient(memberUser.username);
      await shareDialog.setPermission(memberUser.username, "EDIT");
      await shareDialog.save();
    });

    await test.step("Then the individually shared tag is neither suggested nor accepted for the member", async () => {
      expect(await editor.header.getSuggestedTags()).not.toContain(ontologyTag);
      await editor.header.addForbiddenTag(ontologyTag);
      await expect(editor.header.tagInfoDialogText).toHaveText(ENFORCED_MESSAGE);
      await editor.saveAndView();
      const document = await member.workspace.openDocument(editor.getId());
      expect(await document.header.getTags()).not.toContain(ontologyTag);
    });

    await test.step("When the PI instead shares the ontology document with the enforcing group, at Edit", async () => {
      await pageWorkspace.open();
      await pageWorkspace.searchBar.search(ontologyDocName);
      await pageWorkspace.table.selectRecord(ontologyDocName);
      const shareDialog = await pageWorkspace.selectionBar.share();
      await shareDialog.addRecipient(enforcingGroupName);
      await shareDialog.setPermission(enforcingGroupName, "EDIT");
      await shareDialog.save();
    });

    await test.step("Then the member now sees and can use the group-shared tag", async () => {
      await expect
        .poll(() => editor.header.getSuggestedTags(), { timeout: 30_000, intervals: [3_000] })
        .toContain(ontologyTag);
      await editor.header.addTag(ontologyTag);
      const reopened = await member.workspace.openDocument(editor.getId());
      expect(await reopened.header.getTags()).toContain(ontologyTag);
    });
  });

  test("As a user, tags added to a notebook entry persist and display correctly after reopening the notebook", async ({
    pageWorkspace,
    pageNotebook,
    clientFolders,
    clientDocuments,
  }) => {
    const notebookName = uniqueName("e2e-ont-nb-tags");
    const tag1 = uniqueName("e2e-ont-nb-tag1");
    const tag2 = uniqueName("e2e-ont-nb-tag2");

    await test.step("Given a notebook with one entry exists", async () => {
      const notebook = await clientFolders.create({ name: notebookName, notebook: true });
      await clientDocuments.create({ name: "Entry 1", parentFolderId: notebook.id });
    });

    await test.step("When I open the entry and tag it", async () => {
      await pageWorkspace.open();
      await pageWorkspace.table.openNotebook(notebookName);
      await pageNotebook.isLoaded();
      await pageNotebook.showAllEntries();
      await pageNotebook.selectEntry("Entry 1");
      await pageNotebook.header.addTag(tag1);
      await pageNotebook.header.addTag(tag2);
    });

    await test.step("Then the tags are shown, and survive a fresh navigation back into the entry — proving they're read from the DB, not stale in-page state", async () => {
      await pageWorkspace.open();
      await pageWorkspace.table.openNotebook(notebookName);
      await pageNotebook.isLoaded();
      await pageNotebook.showAllEntries();
      await pageNotebook.selectEntry("Entry 1");
      expect(await pageNotebook.header.getTags()).toEqual(expect.arrayContaining([tag1, tag2]));
    });
  });
});
