import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { expect } from "@playwright/test";
import { createDynamicUser } from "@/__tests__/e2e/createDynamicUser";
import { dynamicUserTest as test } from "@/__tests__/e2e/fixtures/dynamicUser";
import { loginAsWorkspaceUser } from "@/__tests__/e2e/fixtures/flows/userSessions";
import { DocumentPage } from "@/__tests__/e2e/pageObjects/document/DocumentPage";
import { alphaNumericUnique, uniqueName } from "@/__tests__/e2e/testData";

const currentDir = dirname(fileURLToPath(import.meta.url));
const ONTOLOGY_CSV_FIXTURE = resolve(currentDir, "fixtures/ontology_import.csv");

const ONTOLOGY_FILE_NAME = "YOUR_AUTOGENERATED_TAGS.ontology";
const ONTOLOGY_FIELD_NAME = "Ontologies for tag creation";
const ENFORCED_MESSAGE = "Ontologies are enforced, tag values must come from ontology files shared with a group";

test.describe("Tagging and Ontology", () => {
  test("As a user, tags I add to a document appear in my account's auto-generated ontology file, are shown on the document, and can be removed", async ({
    page,
    pageWorkspace,
    pageDocument,
  }) => {
    const docName = uniqueName("e2e-ont-doc");
    const tag1 = uniqueName("e2e-ont-tag1");
    const tag2 = uniqueName("e2e-ont-tag2");
    const tag3 = uniqueName("e2e-ont-tag3");
    const tag4 = "myTagWithAnApostrophe's";
    const tags = [tag1, tag2, tag3, tag4];

    await test.step("Given I create a basic document and tag it, including a tag with an apostrophe", async () => {
      await pageWorkspace.open();
      const editor = await pageWorkspace.createBasicDocument();
      await editor.header.rename(docName);
      for (const tag of tags) {
        await editor.header.addTag(tag);
      }
      await editor.editToolbar.saveAndClose();
    });

    await test.step("Then the account's auto-generated ontology file contains all the tags", async () => {
      await expect
        .poll(async () => {
          await pageWorkspace.open();
          await pageWorkspace.searchBar.search(ONTOLOGY_FILE_NAME);
          await pageWorkspace.table.openRecord(ONTOLOGY_FILE_NAME);
          await pageDocument.isLoaded();
          return pageDocument.getOntologyTags();
        })
        .toEqual(expect.arrayContaining(tags));
    });

    await test.step("And the document itself shows all the tags", async () => {
      await pageWorkspace.open();
      await pageWorkspace.searchBar.search(docName);
      await pageWorkspace.table.openRecord(docName);
      await pageDocument.isLoaded();
      const docTags = await pageDocument.header.getTags();
      for (const tag of tags) {
        expect(docTags).toContain(tag);
      }
    });

    await test.step("When I remove all the tags", async () => {
      for (const tag of tags) {
        await pageDocument.header.removeTag(tag);
      }
    });

    await test.step("Then no tags remain, even after reloading", async () => {
      await page.reload();
      await pageDocument.isLoaded();
      expect(await pageDocument.header.getTags()).toEqual([]);
    });

    await test.step("When I try to add tags containing forbidden characters", async () => {
      for (const forbidden of ["<tag1>", "tag/2", "tag\\3"]) {
        await pageDocument.header.addForbiddenTag(forbidden);
        await page.reload();
        await pageDocument.isLoaded();
      }
    });

    await test.step("Then none of the forbidden-character tags were added", async () => {
      expect(await pageDocument.header.getTags()).toEqual([]);
    });
  });

  test("As a user, tags I define in an ontology document appear as tag suggestions when tagging another document", async ({
    pageWorkspace,
    pageDocument,
  }) => {
    const tagLines = ["a,b,c", "key=d,e,f", "key2=a"];
    const expectedSuggestions = ["a", "b", "c", "key2=a", "key=d", "key=e", "key=f"];

    await test.step("Given I create an ontology document defining several tags, including a key= group", async () => {
      await pageWorkspace.open();
      await pageWorkspace.toolbar.createMenu.createFromCustomForm("RSpace Tags from Ontologies");
      await pageDocument.isLoaded();
      const field = await pageDocument.editField(ONTOLOGY_FIELD_NAME);
      await field.typeLines(tagLines);
      await field.save();
    });

    await test.step("Then those tags, with key= groups expanded, appear as suggestions when tagging another document", async () => {
      await pageWorkspace.open();
      const editor = await pageWorkspace.createBasicDocument();
      await expect
        .poll(() => editor.header.getSuggestedTags(), { timeout: 30_000, intervals: [3_000] })
        .toEqual(expect.arrayContaining(expectedSuggestions));
    });
  });

  test("As a user, I can import an ontology CSV file, and the resulting document is signed", async ({
    pageMyRSpace,
    pageWorkspace,
    pageDocument,
  }) => {
    const ontologyName = uniqueName("e2e-ont-csv");
    const ontologyVersion = "v1";
    const importedFileName = `${ontologyName}_version_${ontologyVersion}.ontology`;

    await test.step("When I import an ontology CSV file, setting the data and URI columns", async () => {
      await pageMyRSpace.open();
      const exportImport = await pageMyRSpace.openExportImport();
      await exportImport.importOntologyCsv(ONTOLOGY_CSV_FIXTURE, {
        dataColumn: "2",
        uriColumn: "1",
        name: ontologyName,
        version: ontologyVersion,
      });
    });

    await test.step("Then a new ontology document is created, named with the ontology name and version, and it is signed", async () => {
      await pageWorkspace.open();
      await pageWorkspace.searchBar.search(importedFileName);
      await pageWorkspace.table.openRecord(importedFileName);
      await pageDocument.isLoaded();
      expect(await pageDocument.isSigned()).toBe(true);
    });

    await test.step("And it contains the tags from the CSV's data column, not its URI column", async () => {
      const field = await pageDocument.getFieldViewContent("Ontologies");
      const fieldText = await field.innerText();
      for (const tag of ["e2eCsvTagAlpha", "e2eCsvTagBeta", "e2eCsvTagGamma"]) {
        expect(fieldText).toContain(tag);
      }
    });
  });

  test("As a user, an ontology document I share individually is read-only for the recipient, but editable when shared with a group at Edit permission, and its tags are suggested to both", async ({
    browser,
    browserContextOptions,
    clientSysadmin,
  }) => {
    const groupName = uniqueName("e2e-ont-share-group");
    const visibilityGroupName = uniqueName("e2e-ont-visibility-group");
    const ontologyDocName = uniqueName("e2e-ont-share-doc");
    const tag1 = uniqueName("e2e-ont-share-tag1");
    const tag2 = uniqueName("e2e-ont-share-tag2");

    const { ownerUsername, readUsername, editUsername } =
      await test.step("Given an owner, a read-only recipient, and a grouped edit recipient exist", async () => {
        const { username: ownerUsername } = await createDynamicUser(
          clientSysadmin,
          "ROLE_PI",
          "e2eOntOwner",
          "OntOwner",
        );
        const { username: readUsername } = await createDynamicUser(
          clientSysadmin,
          "ROLE_USER",
          "e2eOntRead",
          "OntRead",
        );
        const { username: editUsername } = await createDynamicUser(
          clientSysadmin,
          "ROLE_USER",
          "e2eOntEdit",
          "OntEdit",
        );
        await clientSysadmin.createGroup({
          displayName: groupName,
          type: "LAB_GROUP",
          users: [
            { username: ownerUsername, roleInGroup: "PI" },
            { username: editUsername, roleInGroup: "DEFAULT" },
          ],
        });

        await clientSysadmin.createGroup({
          displayName: visibilityGroupName,
          type: "LAB_GROUP",
          users: [
            { username: ownerUsername, roleInGroup: "PI" },
            { username: readUsername, roleInGroup: "DEFAULT" },
          ],
        });
        return { ownerUsername, readUsername, editUsername };
      });

    const owner = await loginAsWorkspaceUser(browser, browserContextOptions, ownerUsername);
    try {
      const ownerWorkspace = owner.workspace;
      const ownerDocument = new DocumentPage(owner.page);

      await test.step("When the owner creates an ontology document with two tags", async () => {
        await ownerWorkspace.open();
        await ownerWorkspace.toolbar.createMenu.createFromCustomForm("RSpace Tags from Ontologies");
        await ownerDocument.isLoaded();
        await ownerDocument.header.rename(ontologyDocName);
        const field = await ownerDocument.editField(ONTOLOGY_FIELD_NAME);
        await field.typeLines([tag1, tag2]);
        await field.save();
      });

      await test.step("And shares it individually at Read, and with the group at Edit", async () => {
        await expect
          .poll(async () => {
            await ownerWorkspace.open();
            await ownerWorkspace.searchBar.search(ontologyDocName);
            return ownerWorkspace.table.rowCount();
          })
          .toBeGreaterThan(0);

        await ownerWorkspace.table.selectRecord(ontologyDocName);
        const shareDialog = await ownerWorkspace.selectionBar.share();
        await shareDialog.addRecipient(readUsername);
        await shareDialog.setPermission(readUsername, "READ");
        await shareDialog.addRecipient(groupName);
        await shareDialog.setPermission(groupName, "EDIT");
        await shareDialog.save();
      });
    } finally {
      await owner.close();
    }

    const read = await loginAsWorkspaceUser(browser, browserContextOptions, readUsername);
    try {
      const readWorkspace = read.workspace;
      const readDocument = new DocumentPage(read.page);

      await test.step("Then the read-only recipient sees the shared tags suggested on their own documents", async () => {
        await readWorkspace.open();
        const editor = await readWorkspace.createBasicDocument();
        await expect.poll(() => editor.header.getSuggestedTags()).toEqual(expect.arrayContaining([tag1, tag2]));
      });

      await test.step("And the shared ontology document itself is read-only for them", async () => {
        await readWorkspace.open();
        await readWorkspace.searchBar.search(ontologyDocName);
        await readWorkspace.table.openRecord(ontologyDocName);
        await readDocument.isLoaded();
        expect(await readDocument.isReadOnly()).toBe(true);
      });
    } finally {
      await read.close();
    }

    const edit = await loginAsWorkspaceUser(browser, browserContextOptions, editUsername);
    try {
      const editWorkspace = edit.workspace;
      const editDocument = new DocumentPage(edit.page);

      await test.step("Then the grouped edit recipient also sees the shared tags suggested", async () => {
        await editWorkspace.open();
        const editor = await editWorkspace.createBasicDocument();
        await expect
          .poll(() => editor.header.getSuggestedTags(), { timeout: 30_000, intervals: [3_000] })
          .toEqual(expect.arrayContaining([tag1, tag2]));
      });

      await test.step("And the shared ontology document is not read-only for them", async () => {
        await editWorkspace.open();
        await editWorkspace.searchBar.search(ontologyDocName);
        await editWorkspace.table.openRecord(ontologyDocName);
        await editDocument.isLoaded();
        expect(await editDocument.isReadOnly()).toBe(false);
      });
    } finally {
      await edit.close();
    }
  });

  test("As a user, I can tag a notebook, folder, and document individually and via bulk multi-select, and search by tag", async ({
    pageWorkspace,
    clientFolders,
    clientDocuments,
  }) => {
    const notebookName = uniqueName("e2e-tag-nb");
    const folderName = uniqueName("e2e-tag-folder");
    const docName = uniqueName("e2e-tag-doc");
    const tagShared = uniqueName("e2e-tag-shared");
    const tagFullNotebook = uniqueName("e2e-tag-fullnb");
    const tagPicture = uniqueName("e2e-tag-picture");

    await test.step("Given a notebook, a folder, and a document exist", async () => {
      await clientFolders.create({ name: notebookName, notebook: true });
      const folder = await clientFolders.create({ name: folderName });
      await clientDocuments.create({ name: docName, parentFolderId: folder.parentFolderId });
    });

    await test.step("When I tag the notebook with two tags via Add/Remove Tags", async () => {
      await pageWorkspace.open();
      await pageWorkspace.table.selectRecord(notebookName);
      const dialog = await pageWorkspace.selectionBar.addRemoveTags();
      await dialog.addTag(tagShared);
      await dialog.addTag(tagFullNotebook);
      await dialog.save();
    });

    await test.step("Then Record Info shows both tags on the notebook", async () => {
      await pageWorkspace.open();
      const info = await pageWorkspace.table.openInfoFor(notebookName);
      expect(await info.getTags()).toEqual(expect.arrayContaining([tagShared, tagFullNotebook]));
      await info.close();
    });

    await test.step("And Add/Remove Tags is available as an action for the notebook", async () => {
      await pageWorkspace.open();
      await pageWorkspace.table.selectRecord(notebookName);
      expect(await pageWorkspace.selectionBar.isActionVisible("Add/Remove Tags")).toBe(true);
    });

    await test.step("When I add a new free-text tag and remove one of the original tags", async () => {
      const dialog = await pageWorkspace.selectionBar.addRemoveTags();
      await dialog.addTag(tagPicture);
      await dialog.removeTag(tagShared);
      await dialog.save();
    });

    await test.step("Then Record Info reflects the updated tags", async () => {
      await pageWorkspace.open();
      const info = await pageWorkspace.table.openInfoFor(notebookName);
      const tags = await info.getTags();
      expect(tags).toEqual(expect.arrayContaining([tagFullNotebook, tagPicture]));
      expect(tags).not.toContain(tagShared);
      await info.close();
    });

    await test.step("When I select the notebook, folder, and document together", async () => {
      await pageWorkspace.open();
      await pageWorkspace.pagination.setItemsPerPage(50);
      await pageWorkspace.table.selectRecords(notebookName, folderName, docName);
    });

    await test.step("Then Add/Remove Tags shows no common tags across the selection, and adding one applies it to all three", async () => {
      // addRemoveTags() already waits for getTagsForRecords to resolve before returning, so
      // this asserts the dialog's first opening directly — retrying past a wrong first result
      // would hide the exact stale-fetch race documented in
      // .claude/automation/tag-dialog-stale-fetch-race-2026-08-31.md instead of catching it.
      const dialog = await pageWorkspace.selectionBar.addRemoveTags();
      expect(await dialog.noCommonTagsAreDisplayed()).toBe(true);
      await dialog.addTag(tagShared);
      await dialog.save();
    });

    await test.step("Then each item individually shows the shared tag", async () => {
      for (const name of [notebookName, folderName, docName]) {
        await pageWorkspace.open();
        const info = await pageWorkspace.table.openInfoFor(name);
        expect(await info.getTags()).toContain(tagShared);
        await info.close();
      }
    });

    await test.step("And searching by that tag finds all three items", async () => {
      await pageWorkspace.open();
      await pageWorkspace.searchBar.openAdvanced();
      await pageWorkspace.searchBar.addRow();
      await pageWorkspace.searchBar.setRowType(0, "Tag(s)");
      await pageWorkspace.searchBar.setRowTag(0, tagShared);
      await pageWorkspace.searchBar.submitAdvanced();
      for (const name of [notebookName, folderName, docName]) {
        await expect(pageWorkspace.table.row(name)).toBeVisible();
      }
    });
  });

  test("As a PI, enforcing ontologies blocks free-text tags for group members, and sharing an ontology file with the group allows its tags through", async ({
    browser,
    browserContextOptions,
    appUser,
    page,
    pageWorkspace,
    pageDocument,
    pageGroupView,
    clientSysadmin,
  }) => {
    test.setTimeout(120_000);
    const groupName = uniqueName("e2e-enforce-group");
    const ontologyDocName = uniqueName("e2e-enforce-ont-doc");
    const ontologyTag = alphaNumericUnique("e2eEnforceTag");

    const { groupId, memberUsername } = await test.step("Given a PI and a grouped member exist", async () => {
      const { username: memberUsername } = await createDynamicUser(
        clientSysadmin,
        "ROLE_USER",
        "e2eEnfMember",
        "EnfMember",
      );
      const group = await clientSysadmin.createGroup({
        displayName: groupName,
        type: "LAB_GROUP",
        users: [
          { username: appUser.username, roleInGroup: "PI" },
          { username: memberUsername, roleInGroup: "DEFAULT" },
        ],
      });
      return { groupId: group.id, memberUsername };
    });

    await test.step("When the PI enables Enforce Ontologies for the group", async () => {
      await pageGroupView.open(groupId);
      await pageGroupView.toggleEnforceOntologies();
      expect(await pageGroupView.isOntologiesEnforced()).toBe(true);
    });

    const piDocName = uniqueName("e2e-enforce-pi-doc");
    await test.step("Then the PI is also blocked from free-text tags by their own policy", async () => {
      await pageWorkspace.open();
      const editor = await pageWorkspace.createBasicDocument();
      await editor.header.rename(piDocName);
      await editor.header.addForbiddenTag(ontologyTag);
      expect(await editor.header.tagInfoDialogText.innerText()).toBe(ENFORCED_MESSAGE);
      expect(await editor.header.getTags()).toEqual([]);
      await editor.editToolbar.saveAndClose();
    });

    const member = await loginAsWorkspaceUser(browser, browserContextOptions, memberUsername);
    try {
      const memberWorkspace = member.workspace;

      const memberDoc = await test.step("Then the grouped member cannot add a free-text tag", async () => {
        await memberWorkspace.open();
        const editor = await memberWorkspace.createBasicDocument();
        await editor.header.addForbiddenTag(ontologyTag);
        expect(await editor.header.tagInfoDialogText.innerText()).toBe(ENFORCED_MESSAGE);
        expect(await editor.header.getTags()).toEqual([]);
        return editor;
      });

      await test.step("When the PI creates an ontology document defining that tag, and shares it with the group", async () => {
        await pageWorkspace.open();
        await pageWorkspace.toolbar.createMenu.createFromCustomForm("RSpace Tags from Ontologies");
        await pageDocument.isLoaded();
        await pageDocument.header.rename(ontologyDocName);
        const field = await pageDocument.editField(ONTOLOGY_FIELD_NAME);
        await field.typeLines([ontologyTag]);
        await field.save();

        await pageWorkspace.open();
        await pageWorkspace.searchBar.search(ontologyDocName);
        await pageWorkspace.table.selectRecord(ontologyDocName);
        const shareDialog = await pageWorkspace.selectionBar.share();
        await shareDialog.addRecipient(groupName);
        await shareDialog.setPermission(groupName, "EDIT");
        await shareDialog.save();
      });

      await test.step("Then the member can now add that ontology-derived tag", async () => {
        await member.page.reload();

        await expect
          .poll(() => memberDoc.header.getSuggestedTags(), { timeout: 30_000, intervals: [3_000] })
          .toContain(ontologyTag);
        await memberDoc.header.addTag(ontologyTag);
        await member.page.reload();
        expect(await memberDoc.header.getTags()).toContain(ontologyTag);
      });

      await test.step("And still cannot add an unrelated free-text tag", async () => {
        const otherTag = alphaNumericUnique("e2eEnforceOther");
        await memberDoc.header.addForbiddenTag(otherTag);
        expect(await memberDoc.header.tagInfoDialogText.innerText()).toBe(ENFORCED_MESSAGE);
      });
    } finally {
      await member.close();
    }

    await test.step("Then the PI can also add the ontology-derived tag, but still not an unrelated one", async () => {
      await pageWorkspace.open();
      await pageWorkspace.searchBar.search(piDocName);
      await pageWorkspace.table.openRecord(piDocName);
      await pageDocument.isLoaded();

      await expect
        .poll(() => pageDocument.header.getSuggestedTags(), { timeout: 30_000, intervals: [3_000] })
        .toContain(ontologyTag);
      await pageDocument.header.addTag(ontologyTag);
      await page.reload();
      expect(await pageDocument.header.getTags()).toContain(ontologyTag);

      const otherTag = alphaNumericUnique("e2eEnforceOtherPi");
      await pageDocument.header.addForbiddenTag(otherTag);
      expect(await pageDocument.header.tagInfoDialogText.innerText()).toBe(ENFORCED_MESSAGE);
    });
  });
});
