package com.researchspace.dao.hibernate;

import com.researchspace.core.util.ISearchResults;
import com.researchspace.core.util.SearchResultsImpl;
import com.researchspace.dao.FolderDao;
import com.researchspace.dao.GenericDaoHibernate;
import com.researchspace.model.DefaultGroupNamingStrategy;
import com.researchspace.model.Group;
import com.researchspace.model.IGroupNamingStrategy;
import com.researchspace.model.PaginationCriteria;
import com.researchspace.model.User;
import com.researchspace.model.core.RecordType;
import com.researchspace.model.record.BaseRecord;
import com.researchspace.model.record.Folder;
import com.researchspace.model.views.TreeViewItem;
import java.util.List;
import java.util.Optional;
import org.hibernate.query.Query;
import org.springframework.cache.annotation.CachePut;
import org.springframework.stereotype.Repository;

@Repository(value = "folderDao")
@SuppressWarnings({"unchecked"})
public class FolderDaoHibernateImpl extends GenericDaoHibernate<Folder, Long> implements FolderDao {

  public FolderDaoHibernateImpl() {
    super(Folder.class);
  }

  // updates cache if record has global identifier
  @CachePut(
      value = "com.researchspace.model.record.BaseRecord",
      key = "#a0.oid",
      condition = "(#a0.id ne null)")
  public Folder save(Folder object) {
    // overridden to allow liniage to be generated by save
    // object.generateLineage();
    return super.save(object);
  }

  public Folder getRootRecordForUser(User user) {
    Query<Folder> q =
        getSession()
            .createQuery(
                "select f from Folder f where f.owner.id=:userId and"
                    + " f.editInfo.name=:folderName and f.type like :type",
                Folder.class);
    q.setParameter("type", "%" + RecordType.ROOT.name() + "%");
    q.setParameter("userId", user.getId());
    q.setParameter("folderName", user.getUsername());
    return q.uniqueResult();
  }

  public Folder getGalleryRootFolderForUser(User user) {
    Query<Folder> q =
        getSession()
            .createQuery(
                "select f from Folder f where f.type like :type and f.owner.id=:id", Folder.class);
    q.setParameter("type", "%" + RecordType.ROOT_MEDIA.name() + "%");
    q.setParameter("id", user.getId());
    return getFirstResultOrNull(q);
  }

  @Override
  public List<Folder> getParentFolders(Long childId) {
    Query<Folder> q =
        getSession()
            .createQuery(
                "SELECT rtf.folder FROM RecordToFolder rtf WHERE rtf.record.id = :childId",
                Folder.class);
    q.setParameter("childId", childId);
    return q.list();
  }

  @Override
  public ISearchResults<TreeViewItem> getFolderListingForTreeView(
      Long folderId, PaginationCriteria<TreeViewItem> pgCrit) {

    Query<TreeViewItem> q =
        getSession()
            .createQuery(
                "select new com.researchspace.model.views.TreeViewItem (br.id,br.editInfo.name,"
                    + " br.type, br.deleted, br.editInfo.creationDateMillis,"
                    + " br.editInfo.modificationDateMillis, emf.extension) from BaseRecord br left"
                    + " join EcatMediaFile emf on br.id=emf.id inner join RecordToFolder rtf on"
                    + " rtf.record.id=br.id where rtf.folder.id=:folderId and br.deleted=false and"
                    + " rtf.recordInFolderDeleted=false order by br.editInfo.modificationDateMillis"
                    + " desc",
                TreeViewItem.class)
            .setParameter("folderId", folderId);
    List<TreeViewItem> results = q.list();
    ISearchResults<TreeViewItem> rc = new SearchResultsImpl<>(results, pgCrit, results.size());
    return rc;
  }

  public Folder getSystemFolderForUserByName(User user, String systemFolderName) {
    Query<Folder> q =
        getSession()
            .createQuery(
                "from Folder where  owner.id=:id and editInfo.name=:name and type like :type",
                Folder.class);
    q.setParameter("type", "%" + RecordType.SYSTEM.name() + "%")
        .setParameter("name", systemFolderName);
    q.setParameter("id", user.getId());
    return getFirstResultOrNull(q);
  }

  @Override
  public List<Long> getFolderChildrenIds(Folder fd) {
    Long pid = fd.getId();
    return getSession()
        .createQuery("SELECT rtf.record.id FROM RecordToFolder rtf WHERE rtf.folder.id = :parentId")
        .setParameter("parentId", pid)
        .list();
  }

  @Override
  public Folder getLabGroupFolderForUser(User u) {
    return getSystemFolder(Folder.LAB_GROUPS_FOLDER_NAME, u);
  }

  @Override
  public Long getLabGroupFolderIdForUser(User user) {
    Query<Long> q =
        getSession()
            .createQuery(
                "select f.id from Folder f "
                    + "where f.owner.id = :id "
                    + "and f.editInfo.name=:name "
                    + "and f.systemFolder = true",
                Long.class)
            .setParameter("name", Folder.LAB_GROUPS_FOLDER_NAME)
            .setParameter("id", user.getId());
    return q.uniqueResult();
  }

  @Override
  public Folder getIndividualSharedItemsFolderForUser(User u) {
    return getSystemFolder(Folder.INDIVIDUAL_SHARE_ITEMS_FLDER_NAME, u);
  }

  @Override
  public Folder getCollaborationGroupsSharedFolderForUser(User u) {
    return getSystemFolder(Folder.COLLABORATION_GROUPS_FLDER_NAME, u);
  }

  @Override
  public Folder getProjectGroupsSharedFolderForUser(User u) {
    return getSystemFolder(Folder.PROJECT_GROUPS_FOLDER_NAME, u);
  }

  private Folder getSystemFolder(String systemFolderName, User user) {
    return getSession()
        .createQuery(
            "from Folder f join fetch f.owner owner "
                + "where owner.id = :userId "
                + "and f.editInfo.name=:folderName "
                + "and f.systemFolder = true",
            Folder.class)
        .setParameter("userId", user.getId())
        .setParameter("folderName", systemFolderName)
        .uniqueResult();
  }

  public Folder getSharedFolderForGroup(Group group) {
    return get(group.getCommunalGroupFolderId());
  }

  @Override
  public Folder getSharedSnippetFolderForGroup(Group group) {
    return get(group.getSharedSnippetGroupFolderId());
  }

  public Folder getIndividualSharedFolderForUsers(
      User sharer, User sharee, BaseRecord docOrNotebook) {
    IGroupNamingStrategy namingStrgy = new DefaultGroupNamingStrategy();
    String flderName = namingStrgy.getIndividualSharedFolderName(sharer, sharee);
    if (docOrNotebook != null && docOrNotebook.isSnippet()) {
      flderName = namingStrgy.getIndividualSharedSnippetsFolderName(sharer, sharee);
    }
    return getSession()
        .createQuery(
            "from Folder f where f.editInfo.name=:name and f.systemFolder=true and f.owner in"
                + " (:owners)",
            Folder.class)
        .setParameter("name", flderName)
        .setParameterList("owners", List.of(sharer, sharee))
        .uniqueResult();
  }

  @Override
  public Folder getUserSharedFolder(User u) {
    return getSession()
        .createQuery(
            "from Folder f where f.editInfo.name=:name and f.owner=:owner and f.systemFolder=true"
                + " and f.type not like :rootMedia and f.deleted=false",
            Folder.class)
        .setParameter("name", Folder.SHARED_FOLDER_NAME)
        .setParameter("owner", u)
        .setParameter("rootMedia", "%" + RecordType.ROOT_MEDIA.name() + "%")
        .uniqueResult();
  }

  @Override
  public List<Folder> getSubFolders(Folder rootFolder) {
    Query<Folder> query =
        getSession()
            .createQuery(
                "SELECT f FROM RecordToFolder rtf JOIN BaseRecord br ON rtf.record.id = br.id JOIN"
                    + " Folder f ON br.id = f.id WHERE rtf.folder.id = :rootFolderId AND "
                    + " br.deleted = false",
                Folder.class)
            .setParameter("rootFolderId", rootFolder.getId());
    List<Folder> folders = query.list();
    return folders;
  }

  @Override
  public Folder getTemplateFolderForUser(User user) {
    List<Folder> folders =
        getSession()
            .createQuery(
                "from Folder f where f.editInfo.name=:name and f.owner=:owner and"
                    + " f.systemFolder=true and f.type like :templateType",
                Folder.class)
            .setParameter("name", Folder.TEMPLATE_MEDIA_FOLDER_NAME)
            .setParameter("owner", user)
            .setParameter("templateType", "%" + RecordType.TEMPLATE.name() + "%")
            .list();
    return folders.isEmpty() ? null : folders.get(0);
  }

  @Override
  public Optional<Folder> getApiFolderForContentType(String folderName, User subject) {
    return Optional.ofNullable(
        getSession()
            .createQuery(
                "select f from Folder f join f.parents parents join parents.folder parent where"
                    + " f.editInfo.name=:name and f.owner=:owner and f.systemFolder=true and"
                    + " f.type like :apiType and parent.editInfo.name=:parentName",
                Folder.class)
            .setParameter("name", Folder.API_INBOX_FOLDER_NAME)
            .setParameter("owner", subject)
            .setParameter("apiType", "%" + RecordType.API_INBOX.name() + "%")
            .setParameter("parentName", folderName)
            .uniqueResult());
  }

  @Override
  public Optional<Folder> getApiInboxSubFolderByName(
      Folder apiFolder, String folderName, User subject) {
    List<Folder> folderList =
        getSession()
            .createQuery(
                "select f from Folder f join f.parents parents join parents.folder parent where"
                    + " f.editInfo.name=:name and f.owner=:owner and f.systemFolder=true and"
                    + " parent.id=:parentId",
                Folder.class)
            .setParameter("name", folderName)
            .setParameter("owner", subject)
            .setParameter("parentId", apiFolder.getId())
            .list();
    return folderList.isEmpty() ? Optional.empty() : Optional.of(folderList.get(0));
  }

  @Override
  public Optional<Folder> getImportFolder(User subject) {
    return Optional.ofNullable(
        getSession()
            .createQuery(
                "from Folder f where f.editInfo.name=:name and f.owner=:owner and"
                    + " f.systemFolder=true and f.type like :importsType",
                Folder.class)
            .setParameter("name", Folder.IMPORTS_INBOX_FOLDER_NAME)
            .setParameter("owner", subject)
            .setParameter("importsType", "%" + RecordType.IMPORTS.name() + "%")
            .uniqueResult());
  }
}
