netfilestores.login.dialog.title=Login Required
netfilestores.login.dialog.intro=Please authenticate to File System:
netfilestores.login.username.label=Username:
netfilestores.login.password.label=Password:
netfilestores.login.user.dir.label=Directory:
netfilestores.login.no.file.paths.in.dir=No paths in directory name

net.filestores.error.invalidUrl=Invalid connection URL. Try connecting to another Filestore or contact your System Admin
net.filestores.error.auth.password=Authentication problem, check your username and password or contact your System Admin
net.filestores.error.auth.publicKey=Authentication problem, verify that your public key is properly registered or contact your System Admin
net.filestores.error.connection=Connection problem, please try again or contact your System Admin
net.filestores.error.download=Couldn't retrieve the file, please try again or contact your System Admin

net.filestores.validation.no.username=Please provide the username
net.filestores.validation.no.password=Please provide the password
net.filestores.validation.no.key=Please generate ssh key first
