netfilestores.login.dialog.title=Login Required
netfilestores.login.dialog.intro=Please authenticate to File System:
netfilestores.login.username.label=Username:
netfilestores.login.password.label=Password:
netfilestores.login.user.dir.label=Directory:
netfilestores.login.no.file.paths.in.dir=No paths in directory name

net.filestores.error.invalidUrl=Invalid connection URL. Try connecting to another Filestore or contact your System Admin
net.filestores.error.auth.password=Authentication problem, check your username and password or contact your System Admin
net.filestores.error.auth.publicKey=Authentication problem, verify that your public key is properly registered or contact your System Admin
net.filestores.error.connection=Connection problem, please try again or contact your System Admin
net.filestores.error.download=Couldn't retrieve the file, please try again or contact your System Admin
net.filestores.error.disabled=This file system has been disabled, please contact your System Admin

net.filestores.validation.no.username=Please provide the username
net.filestores.validation.no.password=Please provide the password
net.filestores.validation.no.key=Please generate ssh key first

netfilestores.acl.denied.read=User ''{0}'' has no read access to filesystem ''{1}''
netfilestores.acl.denied.write=User ''{0}'' has no write access to filesystem ''{1}''
netfilestores.s3.delete.denied.notCreator=You can only delete filestore items that you created
netfilestores.s3.delete.denied.noMetadata=This item has no creation record and cannot be deleted
netfilestores.s3.delete.denied.tooOld=Filestore items can only be deleted within {0} minutes of their creation
netfilestores.write.folderName.mandatory=folderName is mandatory
netfilestores.write.folderName.invalid=Folder name cannot contain '/' or start or end with spaces
netfilestores.write.cannot.modify.root=Cannot move or delete the filestore root
netfilestores.write.filestore.notFound=Could not find file store with id: {0}
netfilestores.acl.users.in.both.lists=These users are listed for both read and write access; please remove them from one of the lists: {0}

archive.export.nfs.user.not.logged.in=user not logged into ''{0}'' File System
archive.export.nfs.no.read.access=no read access to ''{0}'' File System
archive.export.nfs.file.skipped=file skipped ({0})
archive.export.nfs.download.error=download error: {0}
archive.export.nfs.file.too.large=file larger than provided size limit
archive.export.nfs.file.extension.excluded=file extension ''{0}'' excluded
archive.export.nfs.folder.empty=empty folder
archive.export.nfs.folder.skipped.as.subfolder=skipped as subfolder
archive.export.nfs.folder.included.label=Included
archive.export.nfs.folder.skipped.label=Skipped
archive.export.nfs.subfolder.not.included=subfolder of linked folder
archive.export.nfs.resource.not.accessible=resource not accessible
archive.export.nfs.not.logged.in=not logged into connected File System
