netfilestores.login.no.file.paths.in.dir=No paths in directory name
net.filestores.error.auth.password=Authentication problem, check your username and password or contact your System Admin
net.filestores.error.auth.publicKey=Authentication problem, verify that your public key is properly registered or contact your System Admin

net.filestores.validation.no.username=Please provide the username
net.filestores.validation.no.password=Please provide the password
net.filestores.validation.no.key=Please generate ssh key first
