package com.researchspace.model.comms;

import com.researchspace.model.comms.data.NotificationData;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Lob;
import jakarta.persistence.Transient;
import java.io.Serializable;

/** A simple one-way message, usually will be generated by the system. */
@Entity
public class Notification extends Communication implements Serializable {

  /**
   * @deprecated Notification messages are no longer truncated at this former limit.
   */
  @Deprecated public static final int MAX_MESSAGE_LENGTH = 2000;

  private static final long serialVersionUID = 8300022086445850773L;

  private NotificationType notificationType;
  private String notificationMessage;
  private String notificationData;

  public NotificationType getNotificationType() {
    return notificationType;
  }

  public void setNotificationType(NotificationType notificationType) {
    this.notificationType = notificationType;
  }

  /**
   * Ssytem-generated message describing the notification for human readers.
   *
   * @return
   */
  @Column(columnDefinition = "TEXT")
  public String getNotificationMessage() {
    return notificationMessage;
  }

  /** Sets the complete system-generated notification message. */
  public void setNotificationMessage(String notificationMessage) {
    this.notificationMessage = notificationMessage;
  }

  @Lob
  public String getNotificationData() {
    return this.notificationData;
  }

  public void setNotificationData(String jsonData) {
    this.notificationData = jsonData;
  }

  @Transient
  public NotificationData getNotificationDataObject() {
    return NotificationData.createFromJson(this.notificationType, this.notificationData);
  }

  public void setNotificationDataObject(NotificationData notificationData) {
    this.notificationData = (notificationData == null) ? null : notificationData.toJson();
  }

  @Transient
  public boolean isNotification() {
    return true;
  }

  /**
   * Whether the document should be linked to in messages derived from this notification. For
   * example if notification is about a document that is deleted or unshared then providing a link
   * that won't resolve is to be avoided.
   *
   * @return <code>true</code> if document should not be linked to, <code>false</code> otherwise.
   */
  @Transient
  public boolean isIgnoreRecordLinkInMessage() {
    return NotificationType.NOTIFICATION_DOCUMENT_DELETED.equals(notificationType)
        || NotificationType.NOTIFICATION_DOCUMENT_UNSHARED.equals(notificationType);
  }
}
