// Generated by scripts/generate-feature-flags.mjs. Do not edit.

package com.researchspace.featureflags;

public final class FeatureFlags {

  public static final String BOOKING_ENABLED = "bookingEnabled";

  private FeatureFlags() {}
}
