// Generated by scripts/generate-feature-flags.mjs. Do not edit.
export const FEATURE_FLAGS = {
  bookingEnabled: "bookingEnabled",
} as const;

export type FeatureFlagName = (typeof FEATURE_FLAGS)[keyof typeof FEATURE_FLAGS];
