SET FOREIGN_KEY_CHECKS = 0;

drop table if exists UserConnection;
drop table if exists DATABASECHANGELOG;
drop table if exists DATABASECHANGELOGLOCK;
drop table if exists SD_AUD_TEMP;
drop table if exists BR_AUD_TEMP;
drop table if exists RSPAC1009_OK;
drop table if exists FieldAutosaveLog;

DROP TABLE IF EXISTS BATCH_STEP_EXECUTION_CONTEXT ;
DROP TABLE IF EXISTS BATCH_JOB_EXECUTION_CONTEXT ;
DROP TABLE IF EXISTS BATCH_STEP_EXECUTION ;
DROP TABLE IF EXISTS BATCH_JOB_EXECUTION_PARAMS ;
DROP TABLE IF EXISTS BATCH_JOB_EXECUTION ;
DROP TABLE IF EXISTS BATCH_JOB_INSTANCE ;

DROP TABLE IF EXISTS BATCH_STEP_EXECUTION_SEQ ;
DROP TABLE IF EXISTS BATCH_JOB_EXECUTION_SEQ ;
DROP TABLE IF EXISTS BATCH_JOB_SEQ ;


SET FOREIGN_KEY_CHECKS = 1;