workspace.title=Workspace
workspace.list.options.header=Select
workspace.list.type.header=Type
workspace.list.name.header=Name
workspace.list.id.header=ID
workspace.list.owner.header=Owner
workspace.list.date.header=Modified
workspace.list.creationDate.header=Created
workspace.list.selectAll.header=Select All
workspace.list.selectNone.header=Select None

#  messages on server
repository.submitFailureMsg=There was a problem submitting the request: {0}

workspace.export.msgSuccess=Your export [{0}] is now available in the Exports section of <a href="{1}">the Gallery</a>.
workspace.export.msgFailure=Your export [{0}] failed for the following reason: {1}
workspace.export.noDiskSpace=RSpace has not enough disk space to start archive export process. Please contact your System Admin.
pdfArchiving.submission.successMsg=Your export generation request has been submitted to the server. \
 RSpace will notify you when the export is ready.
archive.download.failure.msg=Export could not be downloaded because the file does not exist: it may have already been removed from the server. \
 Contact us at support@researchspace.com for help with export.
dialogs.renameRecord.label.newName=Please enter a new name

dialogs.moveRecord.instruction=Use the tree below to choose a destination folder for the selected documents
dialogs.moveRecord.selection=Your path selection is

dialogs.share.instruction.individuals=Select individuals to share with
dialogs.share.header.group=Group name
dialogs.share.header.user=User name
dialogs.share.header.select=Select
dialogs.share.header.permission=Permission
dialogs.share.instruction.users.selectedCount=user(s) selected

dialogs.createCalendarEntry.eventTitle.title=Event title
dialogs.createCalendarEntry.eventStart.title=Event start
dialogs.createCalendarEntry.eventEnd.title=Event end
dialogs.createCalendarEntry.includeLinkCheckbox.title=Include links to resources
dialogs.createCalendarEntry.repeatEvent.title=Repeat event
dialogs.createCalendarEntry.description.title=Description

importArchive.badformat.msg=Please supply an RSpace archive file in zip or .eln format
importArchive.failure.msg=There was an error importing the archive:
importArchive.report.title=Import Report
importArchive.report.header=Archive Import Report
importArchive.report.workspace.label=Back to workspace
importArchive.report.another.label=Import another archive
importExport.title=Import and Export Archives
importExport.export.selection.help1=If you want to export a selection of your work, return to the Workspace and use the list checkboxes to choose documents or folders to be exported.\
 Then, choose the Export button in the list of options under the toolbar.
importExport.export.all.help1=If you want to export all of your work and files, click the button below.
importExport.import.help1=Use this facility to import an archive of work into Research Space.
importExport.import.help2=This process imports a single Zip (or .eln) file containing an XML format archive produced by a previous RSpace XML/ELN export. Importing creates new documents in RSpace using the \
 archived files and folders.
importExport.import.help3=Click to import selected file
importExport.import.findFile=Find your file

exportArchive.report.title=Export Report

template.creation.success.msg=The new template has been created in the Templates folder successfully.
template.creation.failure.msg=The template could not be created.
template.creation.nofields.msg=Please choose at least one field to put in the template.

 restore.failure.message=Could not restore - this document is not editable by you. Edit status is {0}

clipboard.title=Copy {0} to your Clipboard
rename.failed.msg=The document could not be renamed. It may be signed or locked for editing.
## createMenu
workspace.create.fromMSWord.replace.error.notbasic=Only a Basic Document can be updated by  Import
workspace.create.fromMSWord.replace.error.1only=When replacing content, only 1 Word file can be imported.
workspace.create.form.label=New Form

##rename
folder.create.placeholder=Enter a name, /or/a/path to create multiple folders
notebook.create.placeholder=Please enter a name for this notebook

## notebook
notebook.title=Notebook Document
notebook.nestednotebook.error=Notebooks and folders cannot be created inside notebooks.
notebook.no_notebook_in_gallery.error=You can only create a Notebook in the Workspace, not the Gallery folder tree

## word import:
workspace.word.import.nofiles.error.msg=No files were submitted! Please choose some Word or text files to upload.

# sharing
sharing.permission.read=Read
sharing.permission.write=Edit
sharing.groups.title=Share with a group
sharing.users.title=Share with users
sharing.others.title=Share with others
sharing.others.msg=Enter the email of a colleague that you would like to share your document(s) with. If they accept your invitation, your content will automatically be shared with them.
sharing.remove.label=Remove
sharing.add.label=Add
sharing.notice.manage.shared.document=To unshare, or to change permissions of shared documents, go to the <a href="/record/share/manage" target="_blank">Shared Documents</a> page.
publish.notice.manage.shared.document=To unpublish go to the <a href="/record/share/published/manage" target="_blank">Published Documents</a> page.
publish.notice.documentation=Read the documentation for <a href="https://researchspace.helpdocs.io/article/lqxsej13hv-publication-of-documents" target="_blank">Publication of documents </a>
#Deleting
document.delete.failure.msg=Document {0} cannot be deleted as it is currently edited by {1}

# moving
workspace.move.success=Move action successful
workspace.move.some.not.moved=Some records were not moved. You may lack permissions to move the records from their current location, or into the new location.
workspace.share.owned.into.shared.owned=Nothing was moved. A shared document owned by a specific user cannot be shared into a notebook owned by the same user. If the document should be a part of the notebook, the owner can `move` it into the notebook on their Workspace.