import type { FieldName, SortRule } from "@/modules/common/collection/collectionConfig";

export type ApiV2FilterOperator =
  | "=="
  | "!="
  | "=gt="
  | "=ge="
  | "=lt="
  | "=le="
  | "=in="
  | "=out="
  | "=contains="
  | "=like="
  | "=exists=";

export type ApiV2FilterLimits = {
  maximumComparisons: number;
  maximumLikeComparisons: number;
  maximumNesting: number;
  maximumArguments: number;
  maximumWhereLength: number;
};

export type ApiV2PrimitiveFieldType = "text" | "number" | "boolean" | "dateTime";

/** Endpoint rules generated by the API V2 OpenAPI document. */
export type ApiV2CollectionMetadata<TDocument> = {
  resourceName: string;
  fields: readonly FieldName<TDocument>[];
  sorting: {
    fields: readonly FieldName<TDocument>[];
    default: readonly SortRule<TDocument>[];
    maximumFields: number;
  };
  filtering: {
    selectors: Readonly<
      Partial<
        Record<
          string,
          {
            operators: readonly ApiV2FilterOperator[];
            wildcards: boolean;
            title?: string;
            fieldType?: ApiV2PrimitiveFieldType | null;
          }
        >
      >
    >;
    limits: ApiV2FilterLimits;
  };
  pagination: {
    defaultLimit: number;
    maximumLimit: number;
  };
};

const filterOperators = new Set<ApiV2FilterOperator>([
  "==",
  "!=",
  "=gt=",
  "=ge=",
  "=lt=",
  "=le=",
  "=in=",
  "=out=",
  "=contains=",
  "=like=",
  "=exists=",
]);

function object(value: unknown, role: string): Record<string, unknown> {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    throw new Error(`OpenAPI ${role} must be an object`);
  }
  return value as Record<string, unknown>;
}

function number(value: unknown, role: string): number {
  if (typeof value !== "number" || !Number.isFinite(value)) throw new Error(`OpenAPI ${role} must be a number`);
  return value;
}

function strings(value: unknown, role: string): string[] {
  if (!Array.isArray(value) || value.some((item) => typeof item !== "string")) {
    throw new Error(`OpenAPI ${role} must be a string array`);
  }
  return value;
}

function primitiveFieldType(schema: unknown): ApiV2PrimitiveFieldType | null {
  if (typeof schema !== "object" || schema === null || Array.isArray(schema)) return "text";
  const { type, format } = schema as Record<string, unknown>;
  if (type === "boolean") return "boolean";
  if (type === "integer" || type === "number") return "number";
  if (type === "string") return format === "date-time" ? "dateTime" : "text";
  return type === "object" || type === "array" ? null : "text";
}

function queryParameter(operation: Record<string, unknown>, name: string): Record<string, unknown> {
  const parameters = operation.parameters;
  if (!Array.isArray(parameters)) throw new Error("OpenAPI list parameters must be an array");
  const parameter = parameters.find((candidate) => object(candidate, "parameter").name === name);
  if (!parameter) throw new Error(`OpenAPI list operation has no ${name} parameter`);
  return object(parameter, `${name} parameter`);
}

export function apiV2CollectionMetadataFromOpenApi<TDocument>(
  document: unknown,
  resourceName: string,
): ApiV2CollectionMetadata<TDocument> {
  const paths = object(object(document, "document").paths, "paths");
  const operation = object(object(paths[`/api/v2/${resourceName}`], `${resourceName} path`).get, "list operation");
  const sort = object(queryParameter(operation, "sort")["x-rspace-sort"], "sort metadata");
  const whereParameter = queryParameter(operation, "where");
  const where = object(whereParameter["x-rspace-filter"], "filter metadata");
  const whereSchema = object(whereParameter.schema, "where schema");
  const limitSchema = object(queryParameter(operation, "limit").schema, "limit schema");
  const fieldsParameter = queryParameter(operation, "fields");
  const allowedFields = object(fieldsParameter["x-rspace-allowed-fields"], "allowed fields");
  const selectorInput = object(where.selectors, "filter selectors");
  const selectors: Record<
    string,
    {
      operators: ApiV2FilterOperator[];
      wildcards: boolean;
      title?: string;
      fieldType: ApiV2PrimitiveFieldType | null;
    }
  > = {};
  for (const [name, input] of Object.entries(selectorInput)) {
    const selector = object(input, `filter selector ${name}`);
    const operators = strings(selector.operators, `operators for ${name}`);
    if (operators.some((operator) => !filterOperators.has(operator as ApiV2FilterOperator))) {
      throw new Error(`OpenAPI filter selector ${name} has an unknown operator`);
    }
    selectors[name] = {
      operators: operators as ApiV2FilterOperator[],
      wildcards: selector.wildcards === true,
      fieldType: primitiveFieldType(selector.schema),
      // Present for a selector of a relationship target, whose label belongs to the target's own
      // resource rather than to this collection.
      ...(typeof selector.title === "string" ? { title: selector.title } : {}),
    };
  }
  const defaultSort = strings(sort.default, "default sort").map((value) => ({
    field: (value.startsWith("-") ? value.slice(1) : value) as FieldName<TDocument>,
    direction: value.startsWith("-") ? ("desc" as const) : ("asc" as const),
  }));

  return {
    resourceName,
    fields: strings(allowedFields[resourceName], `allowed fields for ${resourceName}`) as FieldName<TDocument>[],
    sorting: {
      fields: strings(sort.fields, "sortable fields") as FieldName<TDocument>[],
      default: defaultSort,
      maximumFields: number(sort.maximumFields, "maximum sort fields"),
    },
    filtering: {
      selectors: selectors as unknown as ApiV2CollectionMetadata<TDocument>["filtering"]["selectors"],
      limits: {
        maximumComparisons: number(where.maximumComparisons, "maximum comparisons"),
        maximumLikeComparisons: number(where.maximumLikeComparisons, "maximum like comparisons"),
        maximumNesting: number(where.maximumNesting, "maximum filter nesting"),
        maximumArguments: number(where.maximumArguments, "maximum filter arguments"),
        maximumWhereLength: number(whereSchema.maxLength, "maximum where length"),
      },
    },
    pagination: {
      defaultLimit: number(limitSchema.default, "default page size"),
      maximumLimit: number(limitSchema.maximum, "maximum page size"),
    },
  };
}

export async function fetchApiV2CollectionMetadata<TDocument>(
  resourceName: string,
  options: { fetch?: typeof globalThis.fetch; signal?: AbortSignal } = {},
): Promise<ApiV2CollectionMetadata<TDocument>> {
  const response = await (options.fetch ?? globalThis.fetch)("/api/v2/openapi.json", {
    headers: { "X-Requested-With": "XMLHttpRequest" },
    signal: options.signal,
  });
  if (!response.ok) throw new Error(`API V2 OpenAPI request failed with status ${response.status}`);
  const document: unknown = await response.json();
  return apiV2CollectionMetadataFromOpenApi<TDocument>(document, resourceName);
}
