import type { FieldName, RelationshipFilterPicker, SortRule } from "@/modules/common/collection/collectionConfig";

import { validateRuntimeFieldCatalogUrl } from "./runtimeFieldCatalog";

export type ApiV2FilterOperator =
  | "=="
  | "!="
  | "=gt="
  | "=ge="
  | "=lt="
  | "=le="
  | "=in="
  | "=out="
  | "=contains="
  | "=like="
  | "=exists=";

export type ApiV2FilterLimits = {
  maximumComparisons: number;
  maximumLikeComparisons: number;
  maximumNesting: number;
  maximumArguments: number;
  maximumWhereLength: number;
};

export type ApiV2PrimitiveFieldType = "text" | "number" | "boolean" | "dateTime";

export type ApiV2RuntimeFieldNamespace = {
  namespace: string;
  catalog: string;
  responseField: string;
  filterable: boolean;
  columnSelectable: boolean;
  sortable: boolean;
  maximumProjections: number;
  catalogDefaultLimit: number;
  catalogMaximumLimit: number;
  catalogMaximumIds: number;
  via: string;
  viaResource: string;
};

/** Endpoint rules generated by the API V2 OpenAPI document. */
export type ApiV2CollectionMetadata<TDocument> = {
  resourceName: string;
  fields: readonly FieldName<TDocument>[];
  sorting: {
    fields: readonly FieldName<TDocument>[];
    default: readonly SortRule<TDocument>[];
    maximumFields: number;
  };
  filtering: {
    selectors: Readonly<
      Partial<
        Record<
          string,
          {
            operators: readonly ApiV2FilterOperator[];
            wildcards: boolean;
            title?: string;
            fieldType?: ApiV2PrimitiveFieldType | null;
            picker?: RelationshipFilterPicker;
          }
        >
      >
    >;
    limits: ApiV2FilterLimits;
  };
  relationshipFields?: Readonly<
    Record<
      string,
      {
        operators: readonly ApiV2FilterOperator[];
        wildcards: boolean;
        title?: string;
        viaTitle?: string;
        fieldType: ApiV2PrimitiveFieldType | null;
      }
    >
  >;
  runtimeFields?: readonly ApiV2RuntimeFieldNamespace[];
  pagination: {
    defaultLimit: number;
    maximumLimit: number;
  };
};

const filterOperators = new Set<ApiV2FilterOperator>([
  "==",
  "!=",
  "=gt=",
  "=ge=",
  "=lt=",
  "=le=",
  "=in=",
  "=out=",
  "=contains=",
  "=like=",
  "=exists=",
]);

function object(value: unknown, role: string): Record<string, unknown> {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    throw new Error(`OpenAPI ${role} must be an object`);
  }
  return value as Record<string, unknown>;
}

function number(value: unknown, role: string): number {
  if (typeof value !== "number" || !Number.isFinite(value)) throw new Error(`OpenAPI ${role} must be a number`);
  return value;
}

function strings(value: unknown, role: string): string[] {
  if (!Array.isArray(value) || value.some((item) => typeof item !== "string")) {
    throw new Error(`OpenAPI ${role} must be a string array`);
  }
  return value;
}

function primitiveFieldType(schema: unknown): ApiV2PrimitiveFieldType | null {
  if (typeof schema !== "object" || schema === null || Array.isArray(schema)) return "text";
  const { type: declared, format } = schema as Record<string, unknown>;
  const type = Array.isArray(declared) ? declared.find((entry) => entry !== "null") : declared;
  if (type === "boolean") return "boolean";
  if (type === "integer" || type === "number") return "number";
  if (type === "string") return format === "date-time" ? "dateTime" : "text";
  return type === "object" || type === "array" ? null : "text";
}

function relationshipPicker(value: unknown, selector: string): RelationshipFilterPicker | undefined {
  if (value === undefined) return undefined;
  const picker = object(value, `picker for ${selector}`);
  if (
    !/^[A-Za-z][A-Za-z0-9_]*$/.test(selector) ||
    typeof picker.resource !== "string" ||
    !/^[a-z][a-z0-9-]*$/.test(picker.resource) ||
    picker.identity !== "globalId" ||
    typeof picker.globalIdPrefix !== "string" ||
    !/^[A-Z]+$/.test(picker.globalIdPrefix)
  )
    throw new Error(`OpenAPI filter selector ${selector} has an invalid picker`);
  return { resource: picker.resource, identity: "globalId", globalIdPrefix: picker.globalIdPrefix };
}

function validateSelectorName(name: string, role: string): void {
  const parts = name.split(".");
  if (parts.length > 2 || parts.some((part) => !/^[A-Za-z][A-Za-z0-9_-]*$/.test(part))) {
    throw new Error(`OpenAPI ${role} ${name} must have at most one relationship hop`);
  }
}

function relationshipFields(
  whereParameter: Record<string, unknown>,
): NonNullable<ApiV2CollectionMetadata<unknown>["relationshipFields"]> {
  const declared = whereParameter["x-rspace-relationship-fields"];
  if (declared === undefined) return {};
  const fields: Record<
    string,
    {
      operators: ApiV2FilterOperator[];
      wildcards: boolean;
      title?: string;
      viaTitle?: string;
      fieldType: ApiV2PrimitiveFieldType | null;
    }
  > = {};
  for (const [name, input] of Object.entries(object(declared, "relationship fields"))) {
    validateSelectorName(name, "relationship field");
    if (!name.includes(".")) {
      throw new Error(`OpenAPI relationship field ${name} must have one hop`);
    }
    const descriptor = object(input, `relationship field ${name}`);
    const operators = strings(descriptor.operators, `operators for ${name}`);
    if (operators.some((operator) => !filterOperators.has(operator as ApiV2FilterOperator))) {
      throw new Error(`OpenAPI relationship field ${name} has an unknown operator`);
    }
    fields[name] = {
      operators: operators as ApiV2FilterOperator[],
      wildcards: descriptor.wildcards === true,
      fieldType: primitiveFieldType(descriptor.schema),
      ...(typeof descriptor.title === "string" ? { title: descriptor.title } : {}),
      ...(typeof descriptor.viaTitle === "string" ? { viaTitle: descriptor.viaTitle } : {}),
    };
  }
  return fields;
}

function runtimeFieldNamespaces(whereParameter: Record<string, unknown>): ApiV2RuntimeFieldNamespace[] {
  const declared = whereParameter["x-rspace-runtime-fields"];
  if (declared === undefined) return [];
  if (!Array.isArray(declared)) throw new Error("OpenAPI runtime fields must be an array");
  const namespaces = new Set<string>();
  return declared.map((input) => {
    const descriptor = object(input, "runtime field namespace");
    const namespace = descriptor.namespace;
    const catalog = descriptor.catalog;
    const responseField = descriptor.responseField;
    if (typeof namespace !== "string" || namespace === "") throw new Error("Runtime field namespace must be a string");
    if (typeof catalog !== "string" || catalog === "") throw new Error("Runtime field catalog must be a URL");
    validateRuntimeFieldCatalogUrl(catalog);
    if (typeof responseField !== "string") throw new Error("Runtime field response field must be a string");
    const parts = namespace.split(".");
    const terminal = parts.at(-1);
    if (
      parts.length > 2 ||
      parts.some((part) => !/^[A-Za-z][A-Za-z0-9_-]*$/.test(part)) ||
      (terminal !== "customFields" && terminal !== "extraFields")
    ) {
      throw new Error(`Runtime field namespace ${namespace} must name one supported field catalog`);
    }
    const catalogTerminal = catalog.endsWith("/customFields")
      ? "customFields"
      : catalog.endsWith("/extraFields")
        ? "extraFields"
        : "";
    if (catalogTerminal !== terminal) {
      throw new Error(`Runtime field namespace ${namespace} does not match its catalog`);
    }
    const via = typeof descriptor.via === "string" ? descriptor.via : "";
    const viaResource = typeof descriptor.viaResource === "string" ? descriptor.viaResource : "";
    if (
      (descriptor.via !== undefined && typeof descriptor.via !== "string") ||
      (descriptor.viaResource !== undefined && typeof descriptor.viaResource !== "string") ||
      (parts.length === 1 && (via !== "" || viaResource !== "")) ||
      (parts.length === 2 && (via !== parts[0] || !/^[a-z][a-z0-9-]*$/.test(viaResource)))
    ) {
      throw new Error(`Runtime field namespace ${namespace} has an unsupported relationship source`);
    }
    if (namespaces.has(namespace)) throw new Error(`Duplicate runtime field namespace ${namespace}`);
    namespaces.add(namespace);
    return {
      namespace,
      catalog,
      responseField,
      filterable: descriptor.filterable === true,
      columnSelectable: descriptor.columnSelectable === true,
      sortable: descriptor.sortable === true,
      maximumProjections: number(descriptor.maximumProjections, "maximum runtime projections"),
      catalogDefaultLimit: typeof descriptor.catalogDefaultLimit === "number" ? descriptor.catalogDefaultLimit : 50,
      catalogMaximumLimit: typeof descriptor.catalogMaximumLimit === "number" ? descriptor.catalogMaximumLimit : 200,
      catalogMaximumIds:
        typeof descriptor.catalogMaximumIds === "number"
          ? descriptor.catalogMaximumIds
          : number(descriptor.maximumProjections, "maximum runtime projections"),
      via: typeof descriptor.via === "string" ? descriptor.via : "",
      viaResource: typeof descriptor.viaResource === "string" ? descriptor.viaResource : "",
    };
  });
}

function queryParameter(operation: Record<string, unknown>, name: string): Record<string, unknown> {
  const parameters = operation.parameters;
  if (!Array.isArray(parameters)) throw new Error("OpenAPI list parameters must be an array");
  const parameter = parameters.find((candidate) => object(candidate, "parameter").name === name);
  if (!parameter) throw new Error(`OpenAPI list operation has no ${name} parameter`);
  return object(parameter, `${name} parameter`);
}

export function apiV2CollectionMetadataFromOpenApi<TDocument>(
  document: unknown,
  resourceName: string,
): ApiV2CollectionMetadata<TDocument> {
  const paths = object(object(document, "document").paths, "paths");
  const operation = object(object(paths[`/api/v2/${resourceName}`], `${resourceName} path`).get, "list operation");
  const sort = object(queryParameter(operation, "sort")["x-rspace-sort"], "sort metadata");
  const whereParameter = queryParameter(operation, "where");
  const where = object(whereParameter["x-rspace-filter"], "filter metadata");
  const whereSchema = object(whereParameter.schema, "where schema");
  const limitSchema = object(queryParameter(operation, "limit").schema, "limit schema");
  const fieldsParameter = queryParameter(operation, "fields");
  const allowedFields = object(fieldsParameter["x-rspace-allowed-fields"], "allowed fields");
  const selectorInput = object(where.selectors, "filter selectors");
  const selectors: Record<
    string,
    {
      operators: ApiV2FilterOperator[];
      wildcards: boolean;
      title?: string;
      fieldType: ApiV2PrimitiveFieldType | null;
      picker?: RelationshipFilterPicker;
    }
  > = {};
  for (const [name, input] of Object.entries(selectorInput)) {
    validateSelectorName(name, "filter selector");
    const selector = object(input, `filter selector ${name}`);
    const operators = strings(selector.operators, `operators for ${name}`);
    if (operators.some((operator) => !filterOperators.has(operator as ApiV2FilterOperator))) {
      throw new Error(`OpenAPI filter selector ${name} has an unknown operator`);
    }
    const picker = relationshipPicker(selector.picker, name);
    selectors[name] = {
      ...(picker === undefined ? {} : { picker }),
      operators: operators as ApiV2FilterOperator[],
      wildcards: selector.wildcards === true,
      fieldType: primitiveFieldType(selector.schema),
      // Present for a selector of a relationship target, whose label belongs to the target's own
      // resource rather than to this collection.
      ...(typeof selector.title === "string" ? { title: selector.title } : {}),
    };
  }
  const defaultSort = strings(sort.default, "default sort").map((value) => ({
    field: (value.startsWith("-") ? value.slice(1) : value) as FieldName<TDocument>,
    direction: value.startsWith("-") ? ("desc" as const) : ("asc" as const),
  }));

  return {
    resourceName,
    fields: strings(allowedFields[resourceName], `allowed fields for ${resourceName}`) as FieldName<TDocument>[],
    sorting: {
      fields: strings(sort.fields, "sortable fields") as FieldName<TDocument>[],
      default: defaultSort,
      maximumFields: number(sort.maximumFields, "maximum sort fields"),
    },
    filtering: {
      selectors: selectors as unknown as ApiV2CollectionMetadata<TDocument>["filtering"]["selectors"],
      limits: {
        maximumComparisons: number(where.maximumComparisons, "maximum comparisons"),
        maximumLikeComparisons: number(where.maximumLikeComparisons, "maximum like comparisons"),
        maximumNesting: number(where.maximumNesting, "maximum filter nesting"),
        maximumArguments: number(where.maximumArguments, "maximum filter arguments"),
        maximumWhereLength: number(whereSchema.maxLength, "maximum where length"),
      },
    },
    relationshipFields: relationshipFields(whereParameter),
    runtimeFields: runtimeFieldNamespaces(whereParameter),
    pagination: {
      defaultLimit: number(limitSchema.default, "default page size"),
      maximumLimit: number(limitSchema.maximum, "maximum page size"),
    },
  };
}

export async function fetchApiV2CollectionMetadata<TDocument>(
  resourceName: string,
  options: { fetch?: typeof globalThis.fetch; signal?: AbortSignal } = {},
): Promise<ApiV2CollectionMetadata<TDocument>> {
  const response = await (options.fetch ?? globalThis.fetch)("/api/v2/openapi.json", {
    headers: { "X-Requested-With": "XMLHttpRequest" },
    signal: options.signal,
  });
  if (!response.ok) throw new Error(`API V2 OpenAPI request failed with status ${response.status}`);
  const document: unknown = await response.json();
  return apiV2CollectionMetadataFromOpenApi<TDocument>(document, resourceName);
}
