package com.researchspace.service.aws;

import com.researchspace.service.archive.export.ExportFailureException;
import com.researchspace.service.aws.impl.S3UtilitiesImpl.S3FolderContentItem;
import java.io.File;
import java.util.List;
import java.util.Map;
import software.amazon.awssdk.http.SdkHttpResponse;
import software.amazon.awssdk.services.s3.model.DeleteObjectResponse;

/** Interface for utility class that interacts with S3 code in AWS SDK. */
public interface S3Utilities {

  /**
   * Checks if an archive object is stored in S3
   *
   * @param folderPath the path to the folder to check
   * @param fileName the file name to check
   * @return true or false as to whether the object exists in S3
   */
  boolean isFileInS3(String folderPath, String fileName);

  /**
   * Export a file to S3 using the aws sdk. Note that this is a blocking method, it won't return
   * until the file has been completely uploaded and returned successfully.
   *
   * @param folderPath the path to the folder to upload to
   * @param file The file to export
   * @return SdkHttpResponse received from aws
   * @throws ExportFailureException if an exception occurs during the export
   */
  SdkHttpResponse uploadToS3(String folderPath, File file);

  /**
   * Variant of {@link #uploadToS3(String, File)} that attaches user-defined S3 object metadata
   * (translated to {@code x-amz-meta-*} headers on the wire). Pass an empty map for no metadata.
   */
  SdkHttpResponse uploadToS3(String folderPath, File file, Map<String, String> metadata);

  /**
   * Downloads a file from S3 to a local file.
   *
   * @param filePath the path within the bucket to the file to download
   * @param destinationFile the local file to write the downloaded content to
   * @throws ExportFailureException if an exception occurs during the download
   */
  void downloadFromS3(String filePath, File destinationFile);

  /**
   * Lists the contents of a folder in S3.
   *
   * @param folderPath the path to the folder to list
   * @return List of S3FolderItem objects representing files and subfolders
   * @throws ExportFailureException if an exception occurs during the listing
   */
  List<S3FolderContentItem> listFolderContents(String folderPath);

  /**
   * Gets details for a single item in S3.
   *
   * @param path the path to the item
   * @return S3FolderContentItem or null if not found
   */
  S3FolderContentItem getObjectDetails(String path);

  /**
   * Deletes an object from s3 using the aws sdk, this is a blocking method and wont return until it
   * completes.
   *
   * @param fileName the file name to delete
   * @return DeleteObjectResponse the response object generated by aws
   * @throws ExportFailureException
   */
  DeleteObjectResponse deleteFromS3(String folderPath, String fileName);

  /**
   * Creates a "folder" on S3. S3 has no native folders, so this writes a zero-byte object whose key
   * is {@code folderPath} with a single trailing {@code /} (added if not already present). The
   * given metadata (e.g. {@code rspace-created-by} / {@code rspace-created-at}) is attached to the
   * placeholder object so the folder is subject to the same creator/age delete rules as files.
   *
   * @param folderPath the folder key, with or without a trailing slash
   * @param metadata user-defined metadata to attach (may be empty)
   */
  void createFolder(String folderPath, Map<String, String> metadata);

  /**
   * Deletes a single object by its exact key (which may be a folder placeholder key ending in
   * {@code /}). Uses the S3 {@code DeleteObject} API. This is the single-object delete primitive;
   * {@link #deleteFromS3(String, String)} is a {@code (folder, file)} convenience wrapper over it.
   *
   * @param key the full object key to delete
   * @return the {@code DeleteObjectResponse} from S3
   */
  DeleteObjectResponse deleteObject(String key);

  /**
   * Server-side copies an object from another bucket (the source) into this S3Utilities's bucket
   * (the destination). Uses S3 {@code CopyObject}, so data does not flow through the RSpace server.
   * Requires that the configured credentials grant {@code GetObject} on the source and {@code
   * PutObject} on the destination.
   *
   * @param sourceBucket the source S3 bucket name
   * @param sourceKey the source object key
   * @param destKey the destination object key (within this instance's bucket)
   */
  void copyObjectFromBucket(String sourceBucket, String sourceKey, String destKey);

  /**
   * Variant of {@link #copyObjectFromBucket(String, String, String)} that overrides the destination
   * object's user-defined metadata. A non-empty {@code metadata} map causes {@code
   * MetadataDirective.REPLACE} to be applied, so the destination object will carry exactly the
   * given map. An empty map preserves the source object's metadata (default COPY directive).
   */
  void copyObjectFromBucket(
      String sourceBucket, String sourceKey, String destKey, Map<String, String> metadata);

  /**
   * @return the configured S3 bucket name for this instance
   */
  String getBucketName();
}
