package com.researchspace.service.aws;

import com.researchspace.service.archive.export.ExportFailureException;
import com.researchspace.service.aws.impl.S3UtilitiesImpl.S3FolderContentItem;
import java.io.File;
import java.net.URL;
import java.util.Collections;
import java.util.List;
import software.amazon.awssdk.http.SdkHttpResponse;
import software.amazon.awssdk.services.s3.model.DeleteObjectResponse;

/** Interface containing utility method for interacting with S3 code in AWS SDK. */
public interface S3Utilities {
  /**
   * Checks if an object is stored in S3
   *
   * @param fileName the file name to check
   * @return true or false as to whether the object exists in S3
   */
  boolean isArchiveInS3(String fileName);

  /**
   * Generates a pre-signed url which can be used to download an object from S3, this will only
   * generate a url for an object that currently exists in S3 otherwise it will return null
   *
   * @param fileName the file name to generate the url for
   * @return URL the presigned url which can be used to download the object from S3
   * @throws ExportFailureException if an exception occurs while generating the pre-signed url.
   */
  URL getPresignedUrlForArchiveDownload(String fileName);

  /**
   * Export a file to S3 using the aws sdk. Note that this is a blocking method, it won't return
   * until the file has been completely uploaded and returned successfully.
   *
   * @param file The file to export
   * @return SdkHttpResponse received from aws
   * @throws ExportFailureException if an exception occurs during the export
   *
   */
  SdkHttpResponse uploadToS3(File file);


  /**
   * Deletes an object from s3 using the aws sdk, this is a blocking method and wont return until it
   * completes.
   *
   * @param fileName the file name to delete
   * @return DeleteObjectResponse the response object generated by aws
   * @throws ExportFailureException
   */
  DeleteObjectResponse deleteArchiveFromS3(String fileName);

  /**
   * Downloads a file from S3 to a local file.
   *
   * @param filePath the path within the bucket to the file to download
   * @param destinationFile the local file to write the downloaded content to
   * @throws ExportFailureException if an exception occurs during the download
   */
  void downloadFromS3(String filePath, File destinationFile);

  /**
   * Lists the contents of a folder in S3.
   *
   * @param folderPath the path to the folder to list
   * @return List of S3FolderItem objects representing files and subfolders
   * @throws ExportFailureException if an exception occurs during the listing
   */
  List<S3FolderContentItem> listFolderContents(String folderPath);

  /** No-op implementation for when parameter hasS3Access is false. */
  S3Utilities NOOP_S3Utilities =
      new S3Utilities() {

        @Override
        public boolean isArchiveInS3(String fileName) {
          return false;
        }

        @Override
        public URL getPresignedUrlForArchiveDownload(String fileName) {
          return null;
        }

        @Override
        public DeleteObjectResponse deleteArchiveFromS3(String fileName) {
          return null;
        }

        @Override
        public SdkHttpResponse uploadToS3(File file) {
          return SdkHttpResponse.builder().statusCode(400).build();
        }

        @Override
        public void downloadFromS3(String filePath, File destinationFile) {
          // no-op
        }

        @Override
        public List<S3FolderContentItem> listFolderContents(String folderPath) {
          return Collections.emptyList();
        }
      };
}
