package com.researchspace.service.aws;

import com.researchspace.service.archive.export.ExportFailureException;
import com.researchspace.service.aws.impl.S3UtilitiesImpl.S3FolderContentItem;
import java.io.File;
import java.util.List;
import software.amazon.awssdk.http.SdkHttpResponse;
import software.amazon.awssdk.services.s3.model.DeleteObjectResponse;

/** Interface for utility class that interacts with S3 code in AWS SDK. */
public interface S3Utilities {

  /**
   * Checks if an archive object is stored in S3
   *
   * @param folderPath the path to the folder to check
   * @param fileName the file name to check
   * @return true or false as to whether the object exists in S3
   */
  boolean isFileInS3(String folderPath, String fileName);

  /**
   * Export a file to S3 using the aws sdk. Note that this is a blocking method, it won't return
   * until the file has been completely uploaded and returned successfully.
   *
   * @param folderPath the path to the folder to upload to
   * @param file The file to export
   * @return SdkHttpResponse received from aws
   * @throws ExportFailureException if an exception occurs during the export
   */
  SdkHttpResponse uploadToS3(String folderPath, File file);

  /**
   * Downloads a file from S3 to a local file.
   *
   * @param filePath the path within the bucket to the file to download
   * @param destinationFile the local file to write the downloaded content to
   * @throws ExportFailureException if an exception occurs during the download
   */
  void downloadFromS3(String filePath, File destinationFile);

  /**
   * Lists the contents of a folder in S3.
   *
   * @param folderPath the path to the folder to list
   * @return List of S3FolderItem objects representing files and subfolders
   * @throws ExportFailureException if an exception occurs during the listing
   */
  List<S3FolderContentItem> listFolderContents(String folderPath);

  /**
   * Gets details for a single item in S3.
   *
   * @param path the path to the item
   * @return S3FolderContentItem or null if not found
   */
  S3FolderContentItem getObjectDetails(String path);

  /**
   * Deletes an object from s3 using the aws sdk, this is a blocking method and wont return until it
   * completes.
   *
   * @param fileName the file name to delete
   * @return DeleteObjectResponse the response object generated by aws
   * @throws ExportFailureException
   */
  DeleteObjectResponse deleteFromS3(String folderPath, String fileName);
}
