/*
  * Javascript file to provide sorting, paginating and management of messages
  *  
  * listings generated by messages.tag.
  * This js file provides javascript for html defined in messages.tag.
  * You also need to use notifications.js as well since the poll() method is defined there.
  * 
  * To use this in an HTML page there are 3 things to set up:
  * 
  * 1) include messagetoolbar; this is where polling results go:
  * <div id="messageToolbar" style="height: 15px; text-align: center;">
	<span class="messagebox" id="noMessages"></span>
	</div>
	*
	* 2) in your document.ready() function, call:
	* doPoll();//poll immediately for notifications
		//set up 10s poll interval for new notifications.
		pollForNewNotificationsAtInterval();
	* which sets up the polling.
	*
  */
    $(document).ready(function (){
    	
        // handles order-by pagination
    	$('body').on("click", '.orderBy', function(event) {
    		var contentDiv$=$(this).closest('.myrequestList');
    		var orderBy = $(this).attr('id').split("_")[1];
    		$.get(createURL('/dashboard/ajax/listMyRequests?orderBy='+orderBy+'&sortOrder='+'DESC'),
    				function (xhr) {
    			contentDiv$.html(xhr);
    		});
    	});
    	
    	// opens new page of results
    	$('body').on("click", '.page_link', function(event) {
    		var contentDiv$=$(this).closest('.myrequestList');
    		var link = $(this).attr('id').split("_")[1];
    		$.get(createURL(link),
    				function (xhr) {
    			contentDiv$.html(xhr);
    		});
    	});
    	
        $('body').on("click", '.cancelRequestLnk', function(e){
        	e.preventDefault();
        	var contentDiv$=$(this).closest('.myrequestList');
            var tr$ = $(this).closest('tr');
    		var id = getNotificnIDArrayFromRows (tr$);
    		var postData={
    				messageOrRequestId:id[0],
    			};
    		$.post(createURL('/dashboard/ajax/cancelRequest'), postData,
				function (xhr) {
					tr$.hide("fade", function () {
						if( $('tr.myrequestRow').filter(":visible").size() == 0 ) {
			          		contentDiv$.html("No requests sent.");
			          	}
					});
				}
    		);
    	});
    });
    
    // gets notification id from link id in form 'descriptor_XXX' where XXX is the id.
    function getNotificnIDArrayFromRows (wrappedRow$){
        return 	wrappedRow$.map(function (index, item){
    			  return $(item).attr('id').split("_")[1];
    		}).get();
    }